<?php
declare(strict_types=1);
$schema=$data['schema'];$preview=is_array($data['preview']??null)?$data['preview']:null;$result=$data['result']??null;$error=$data['error']??null;
?>
<header class="page-header"><div><p class="eyebrow"><?=e(ucfirst($schema->module))?> data exchange</p><h1>Import <?=e($schema->label)?></h1><p>CSV and genuine Excel XLSX are supported. Formulas are rejected and Test Import makes no database changes.</p></div><div class="filter-actions"><a class="btn btn-secondary" href="/office_app/public/data-exchange/<?=e($schema->entity)?>/template?format=xlsx">Download XLSX Template</a><a class="btn btn-secondary" href="/office_app/public/data-exchange/<?=e($schema->entity)?>/template?format=csv">CSV Template</a></div></header>
<?php if(is_string($error)):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<?php if($result!==null):?><section class="card"><h2>Import result</h2><div class="finance-summary-grid"><div><strong><?=e($result->rowsRead)?></strong><span>Rows read</span></div><div><strong><?=e($result->created)?></strong><span>Created</span></div><div><strong><?=e($result->updated)?></strong><span>Updated</span></div><div><strong><?=e($result->skipped)?></strong><span>Skipped</span></div><div><strong><?=e($result->failed)?></strong><span>Failed</span></div></div><?php foreach($result->errors as $item):?><div class="alert alert-danger">Row <?=e($item['row'])?> · <?=e($item['field'])?> · <?=e($item['message'])?></div><?php endforeach;?></section><?php endif;?>
<?php if($preview===null):?><section class="card"><form method="post" enctype="multipart/form-data" action="/office_app/public/data-exchange/<?=e($schema->entity)?>/preview"><?=csrfField()?><div class="form-field"><label for="exchange_file">Spreadsheet file</label><input id="exchange_file" name="file" type="file" accept=".xlsx,.csv" required><small>Maximum 10 MB, 10,000 rows and 100 columns.</small></div><button class="btn btn-primary">Upload and preview</button></form></section><?php else:?>
<section class="card"><h2>Column mapping</h2><p>Rows read: <?=e($preview['result']->rowsRead)?> · Valid: <?=e($preview['result']->valid)?> · Errors: <?=e(count($preview['result']->errors))?></p><form method="post" action="/office_app/public/data-exchange/<?=e($schema->entity)?>/import"><?=csrfField()?><input type="hidden" name="upload_token" value="<?=e($preview['token'])?>"><div class="table-responsive"><table class="data-table"><thead><tr><th>Spreadsheet column</th><th>OfficeApp field</th></tr></thead><tbody><?php foreach($preview['headers'] as $index=>$header):?><tr><td><?=e($header)?></td><td><select name="mapping[<?=e($index)?>]"><option value="">Do not import</option><?php foreach($schema->fields as $field):?><option value="<?=e($field->key)?>" <?=($preview['mapping'][$index]??null)===$field->key?'selected':''?>><?=e($field->label)?><?= $field->required?' *':''?></option><?php endforeach;?></select></td></tr><?php endforeach;?></tbody></table></div><div class="filter-actions"><button class="btn btn-secondary" name="action" value="test">Test Import</button><?php if($schema->canImport):?><button class="btn btn-primary" name="action" value="import" <?=count($preview['result']->errors)>0?'disabled':''?>>Import</button><?php endif;?></div></form></section>
<section class="card table-card"><h2>Preview</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>Row</th><?php foreach($preview['headers'] as $header):?><th><?=e($header)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($preview['rows'] as $offset=>$row):?><tr><td><?=e($offset+2)?></td><?php foreach($row as $value):?><td><?=e($value)?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php foreach($preview['result']->errors as $item):?><div class="alert alert-danger">Row <?=e($item['row'])?> · <?=e($item['field'])?> · <?=e($item['message'])?></div><?php endforeach;?></section><?php endif;?>
