<?php
declare(strict_types=1);
namespace App\Services;

use App\Repositories\MySql\SettlementRepository;
use PDO;

final class CommercialDocumentService
{
    public function __construct(private ?PdfDocumentService $pdf=null){$this->pdf??=new PdfDocumentService();}
    public function invoice(int $companyId,int $invoiceId): array
    {
        $invoice=(new FinanceOperationsService())->customerInvoice($invoiceId);if($invoice===null)throw new \RuntimeException('Invoice was not found.');$branding=(new SettlementRepository())->branding($companyId);$draft=$invoice['status']==='draft';$title=$draft?'DRAFT CUSTOMER INVOICE':'CUSTOMER INVOICE';$body=$this->header($branding,$title,$invoice['invoice_number']).'<p><b>Customer:</b> '.htmlspecialchars($invoice['customer_name']).' · <b>Sales order:</b> '.htmlspecialchars((string)($invoice['order_number']??'—')).'<br><b>Invoice date:</b> '.htmlspecialchars($invoice['invoice_date']).' · <b>Due:</b> '.htmlspecialchars($invoice['due_date']).'</p>'.$this->lines($invoice['lines'],$invoice['currency']).$this->totals($invoice,$invoice['currency']).'<p><b>Amount in words:</b> '.htmlspecialchars((new EtbAmountInWords())->convert($invoice['total_amount'])).'</p>';if($draft)$body='<div style="position:fixed;top:42%;left:20%;font-size:72px;color:#e3e7ee;transform:rotate(-25deg)">DRAFT</div>'.$body;return ['filename'=>($draft?'DRAFT-':'INVOICE-').$invoice['invoice_number'].'.pdf','content'=>$this->pdf->render($title,$body)];
    }
    public function receipt(int $companyId,int $paymentId): array
    {
        $s=\db()->prepare("SELECT p.*,a.amount receipt_amount,i.invoice_number,i.total_amount,i.residual_amount,o.order_number,c.name customer_name,u.display_name recorded_by FROM finance_payments p JOIN finance_payment_allocations a ON a.company_id=p.company_id AND a.payment_id=p.payment_id JOIN finance_invoices i ON i.company_id=a.company_id AND i.invoice_id=a.invoice_id LEFT JOIN sales_orders o ON o.company_id=i.company_id AND o.order_id=i.sales_order_id JOIN sales_customers c ON c.company_id=p.company_id AND c.customer_id=p.customer_id LEFT JOIN users u ON u.user_id=p.created_by WHERE p.company_id=:c AND p.payment_id=:id AND p.direction='inbound' AND p.status='posted'");$s->execute(['c'=>$companyId,'id'=>$paymentId]);$p=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($p))throw new \RuntimeException('A receipt is available only for a real posted customer payment.');$branding=(new SettlementRepository())->branding($companyId);$previous=max(0,(float)$p['total_amount']-(float)$p['residual_amount']-(float)$p['receipt_amount']);$body=$this->header($branding,'PAYMENT RECEIPT',$p['payment_number']).'<table class="grid"><tr><th>Customer</th><td>'.htmlspecialchars($p['customer_name']).'</td></tr><tr><th>Date</th><td>'.htmlspecialchars($p['payment_date']).'</td></tr><tr><th>Invoice / Sales order</th><td>'.htmlspecialchars($p['invoice_number'].' / '.($p['order_number']??'—')).'</td></tr><tr><th>Method / Reference</th><td>'.htmlspecialchars($p['method'].' / '.($p['reference_number']??'—')).'</td></tr><tr><th>Invoice total</th><td>'.number_format((float)$p['total_amount'],2).'</td></tr><tr><th>Previously paid</th><td>'.number_format($previous,2).'</td></tr><tr><th>This receipt</th><td>'.number_format((float)$p['receipt_amount'],2).'</td></tr><tr><th>Remaining balance</th><td>'.number_format((float)$p['residual_amount'],2).'</td></tr></table><p><b>Amount in words:</b> '.htmlspecialchars((new EtbAmountInWords())->convert($p['receipt_amount'])).'</p><p>Recorded by: '.htmlspecialchars((string)($p['recorded_by']??'—')).'</p>';return ['filename'=>'RECEIPT-'.$p['payment_number'].'.pdf','content'=>$this->pdf->render('Payment Receipt',$body)];
    }
    public function proforma(int $companyId,int $quotationId): array
    {
        $s=\db()->prepare('SELECT q.*,c.name customer_name FROM sales_quotations q JOIN sales_customers c ON c.company_id=q.company_id AND c.customer_id=q.customer_id WHERE q.company_id=:c AND q.quotation_id=:id');$s->execute(['c'=>$companyId,'id'=>$quotationId]);$q=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($q)||$q['status']==='cancelled')throw new \RuntimeException('Quotation was not found.');$l=\db()->prepare('SELECT ql.*,p.sku,p.name product_name FROM sales_quotation_lines ql LEFT JOIN sales_products p ON p.company_id=ql.company_id AND p.product_id=ql.product_id WHERE ql.company_id=:c AND ql.quotation_id=:id ORDER BY ql.sequence');$l->execute(['c'=>$companyId,'id'=>$quotationId]);$q['lines']=$l->fetchAll(PDO::FETCH_ASSOC);$q['discount_amount']=array_sum(array_map(fn($x)=>(float)$x['discount_amount'],$q['lines']));$q['residual_amount']=$q['total_amount'];$branding=(new SettlementRepository())->branding($companyId);$body=$this->header($branding,'PROFORMA INVOICE',$q['quotation_number']).'<p><b>Not a Tax Invoice</b></p><p><b>Customer:</b> '.htmlspecialchars($q['customer_name']).' · <b>Date:</b> '.htmlspecialchars($q['quotation_date']).' · <b>Valid until:</b> '.htmlspecialchars((string)($q['expiration_date']??'—')).'</p>'.$this->lines($q['lines'],$q['currency']).$this->totals($q,$q['currency']).'<p><b>Amount in words:</b> '.htmlspecialchars((new EtbAmountInWords())->convert($q['total_amount'])).'</p>';return ['filename'=>'PROFORMA-'.$q['quotation_number'].'.pdf','content'=>$this->pdf->render('Proforma Invoice',$body)];
    }
    private function header(array $b,string $title,string $number): string{return '<h1>'.htmlspecialchars((string)($b['legal_name']?:$b['company_name']??'Company')).'</h1><p class="muted">'.htmlspecialchars((string)($b['document_address']??'')).' · '.htmlspecialchars((string)($b['document_phone']??$b['contact_phone']??'')).' · '.htmlspecialchars((string)($b['document_email']??$b['contact_email']??'')).'<br>TIN: '.htmlspecialchars((string)($b['tin']??'—')).' · VAT: '.htmlspecialchars((string)($b['vat_registration_number']??'—')).'</p><h2>'.$title.'</h2><p><b>Number:</b> '.htmlspecialchars($number).'</p>';}
    private function lines(array $lines,string $currency): string{$h='<table class="grid"><thead><tr><th>No.</th><th>SKU</th><th>Description</th><th>Qty</th><th>Unit</th><th class="money">Price</th><th class="money">Discount</th><th>Tax</th><th class="money">Total</th></tr></thead><tbody>';foreach($lines as $i=>$l)$h.='<tr><td>'.($i+1).'</td><td>'.htmlspecialchars((string)($l['sku']??'')).'</td><td>'.htmlspecialchars((string)($l['description']??$l['product_name']??'')).'</td><td>'.htmlspecialchars((string)$l['quantity']).'</td><td>'.htmlspecialchars((string)($l['unit_of_measure']??'')).'</td><td class="money">'.number_format((float)$l['unit_price'],2).'</td><td class="money">'.number_format((float)$l['discount_amount'],2).'</td><td>'.number_format((float)$l['tax_rate'],2).'%</td><td class="money">'.number_format((float)($l['total_amount']??$l['line_total']),2).'</td></tr>';return $h.'</tbody></table>';}
    private function totals(array $d,string $currency): string{return '<table class="grid totals"><tr><th>Subtotal</th><td class="money">'.$currency.' '.number_format((float)($d['untaxed_amount']??0)+(float)($d['discount_amount']??0),2).'</td></tr><tr><th>Discount</th><td class="money">'.number_format((float)($d['discount_amount']??0),2).'</td></tr><tr><th>Tax</th><td class="money">'.number_format((float)$d['tax_amount'],2).'</td></tr><tr><th>Grand total</th><td class="money">'.number_format((float)$d['total_amount'],2).'</td></tr></table>';}
}
