<?php
// Included inside a vacancy's details element; all output uses the ERP escaping helper.
$state=$data['publicationStates'][$v['id']]??[];
$questions=$data['careers']->criteria((int)$v['id'],false);
?>
<section class="card"><h3>Public Careers</h3><p><?= e(ucfirst($v['public_status'])) ?> · Revision <?= e($v['public_revision']) ?> · <?= (int)($state['published_revision']??-1)===(int)$v['public_revision']?'Synchronized':'Awaiting publication / synchronization' ?></p>
<?php if(!empty($state['last_error'])): ?><p role="status"><?= e($state['last_error']) ?></p><?php endif; ?>
<?php if($v['public_slug']): ?><p>Public reference: <?= e($v['public_slug']) ?></p><?php endif; ?>
<p>CV and application letter are required. Questions and vacancy edits stay private until you explicitly publish a new revision. Closing the vacancy stops imports and queues closure on the website.</p>
<?php if($can('publish')): ?><form method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="publication"><input type="hidden" name="id" value="<?= e($v['id']) ?>"><?php $select('state','Publication action',['published'=>'Publish current vacancy and questions','closed'=>'Close public applications','private'=>'Withdraw from website']); ?><button class="btn">Confirm publication change</button></form><?php endif; ?>
</section>
<h3>Screening questions</h3><p>Use a small number of job-related questions. Do not ask about protected or sensitive personal characteristics. Free text and fields of study always require human review.</p>
<?php if($can('edit')): $questions[]=['id'=>0,'label'=>'','help_text'=>'','criterion_type'=>'experience_years','operator'=>'gte','expected'=>'3','options'=>[],'decision_mode'=>'minimum','required'=>1,'active'=>1,'sort_order'=>count($questions)*10]; endif; ?>
<?php foreach($questions as $q): ?><details class="card"><summary><?= $q['id']?e($q['label']).(!$q['active']?' · Inactive':''):'Add a question' ?></summary><form method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="criterion"><input type="hidden" name="id" value="<?= e($v['id']) ?>"><input type="hidden" name="criterion_id" value="<?= e($q['id']) ?>">
<?php $field('label','Question',$q['label']); $field('help_text','Help for the applicant',$q['help_text']); ?>
<div class="rec-grid"><?php $select('criterion_type','Answer type',['experience_years'=>'Years of relevant experience','education_level'=>'Education level','field_of_study'=>'Field of study (human review)','boolean'=>'Yes / No','single_choice'=>'Single choice','multiple_choice'=>'Multiple choices','text'=>'Short text (human review)','location'=>'Work-site availability','document_required'=>'Required document confirmation'],$q['criterion_type']); $select('decision_mode','Requirement',['minimum'=>'Minimum requirement','review'=>'Human review required','preference'=>'Preference only'],$q['decision_mode']); $select('comparison','Answer should be',['eq'=>'Exactly this answer','gte'=>'At least this number','lte'=>'At most this number','in'=>'One of these accepted answers','contains'=>'Include all these choices'],$q['operator']); $field('sort_order','Display order',$q['sort_order'],'number'); ?></div>
<label>Choices (one per line, for choice and availability questions)<textarea name="choices" rows="4"><?= e(implode("\n",$q['options'])) ?></textarea></label><label>Accepted answer or minimum value (one per line for accepted choices; use yes or no for Yes / No)<textarea name="accepted" rows="3"><?= e(is_array($q['expected'])?implode("\n",$q['expected']):(string)$q['expected']) ?></textarea></label>
<label><input type="checkbox" name="required" value="1" <?= $q['required']?'checked':'' ?>>Applicant must answer</label><label><input type="checkbox" name="active" value="1" <?= $q['active']?'checked':'' ?>>Include this question</label><p>An explicit minimum failure is shown to HR as “Minimum requirement not met”. Final recruitment decisions always require HR action.</p><?php if($can('edit')): ?><button class="btn">Save question</button><?php endif; ?></form></details><?php endforeach; ?>
