<?php
declare(strict_types=1);
use App\Services\Recruitment\Rules;
$screen=$data['screen']; $can=fn($p)=>in_array($p,$data['permissions'],true);
$url=fn($path)=>appUrl('/hr/recruitment'.$path);
$token=fn()=>'<input type="hidden" name="_token" value="'.e(csrfToken()).'">';
$field=static function(string $name,string $label,mixed $value='',string $type='text'): void { ?>
<label><?= e($label) ?><input class="form-control" name="<?= e($name) ?>" type="<?= e($type) ?>" value="<?= e($value) ?>"></label>
<?php };
$select=static function(string $name,string $label,array $options,mixed $selected=''): void { ?>
<label><?= e($label) ?><select class="form-control" name="<?= e($name) ?>"><option value="">— Select —</option><?php foreach($options as $key=>$value): ?><option value="<?= e($key) ?>" <?= (string)$key===(string)$selected?'selected':'' ?>><?= e($value) ?></option><?php endforeach; ?></select></label>
<?php };
$vacancies=array_column($data['vacancies']??[],'title','id'); $reviewers=array_column($data['reviewers']??[],'display_name','user_id');
?>
<style>.recruitment .rec-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1rem}.recruitment label{display:block;margin:8px 0}.recruitment input,.recruitment select,.recruitment textarea{display:block;width:100%;padding:8px}.recruitment .card{padding:1rem;margin:1rem 0}.recruitment table{width:100%;border-collapse:collapse}.recruitment th,.recruitment td{padding:10px;text-align:left;border-bottom:1px solid #ddd}.recruitment pre{white-space:pre-wrap;overflow-wrap:anywhere}.recruitment input[type=checkbox]{display:inline-block;width:auto}.recruitment nav{display:flex;gap:1rem;flex-wrap:wrap}.recruitment .rec-scroll{overflow:auto}</style>
<section class="recruitment">
<nav><?php if($can('view')): ?><a href="<?= e($url('')) ?>">Applications & dashboard</a><a href="<?= e($url('/vacancies')) ?>">Vacancies</a><a href="<?= e($url('/applicants')) ?>">Applicants</a><a href="<?= e($url('?queue=1')) ?>">Review queue</a><?php endif; ?><?php if($can('edit')): ?><a href="<?= e($url('/create')) ?>">Add application</a><?php endif; ?><?php if($can('mailboxes')): ?><a href="<?= e($url('/mailboxes')) ?>">Mailbox administration</a><?php endif; ?></nav>
<?php if($data['notice']): ?><div class="alert" role="status"><?= e($data['notice']) ?></div><?php endif; ?>
<?php if($screen==='list'): ?>
<h2>Applications requiring attention</h2><nav class="card"><a href="<?= e($url('?view=attention')) ?>">Needs attention · <?= e(($data['summary']['New']??0)+($data['summary']['Under Review']??0)) ?></a><?php foreach(['needs_review'=>'Needs review','minimum_met'=>'Minimum met','minimum_not_met'=>'Minimum not met'] as $outcome=>$label): ?><a href="<?= e($url('?screening='.$outcome)) ?>"><?= e($label) ?> · <?= e($data['screeningCounts'][$outcome]??0) ?></a><?php endforeach; ?><a href="<?= e($url('?source=email&unmatched=1')) ?>">Unmatched email</a><a href="<?= e($url('?view=recent')) ?>">Recently received</a></nav>
<form method="get" class="card"><div class="rec-grid">
<?php $field('q','Search name, email or phone',$_GET['q']??''); $select('vacancy','Vacancy',$vacancies,$_GET['vacancy']??''); $select('status','Status',array_combine(Rules::STATUSES,Rules::STATUSES),$_GET['status']??''); $field('from','Received from',$_GET['from']??'','date'); $field('to','Received through',$_GET['to']??'','date'); $select('source','Source',['manual'=>'Manual','email'=>'Email','website'=>'Website'],$_GET['source']??''); $select('reviewer','Assigned HR',$reviewers,$_GET['reviewer']??''); $select('screening','Screening',['minimum_met'=>'Minimum met','minimum_not_met'=>'Minimum not met','needs_review'=>'Needs review','pending'=>'Unscreened'],$_GET['screening']??''); $select('document','Documents',['quarantine'=>'Quarantined','missing'=>'Missing'],$_GET['document']??''); $select('view','Show',['attention'=>'Needs attention','all'=>'All stages'],$_GET['view']??(!$_GET?'attention':'all')); ?>
</div><label><input type="checkbox" name="unmatched" value="1" <?= !empty($_GET['unmatched'])?'checked':'' ?>>Unmatched vacancy</label><label><input type="checkbox" name="needs_review" value="1" <?= !empty($_GET['needs_review'])?'checked':'' ?>>Needs review</label><label><input type="checkbox" name="queue" value="1" <?= !empty($_GET['queue'])?'checked':'' ?>>Missing details, unmatched vacancy, possible duplicate or unreviewed</label><button class="btn btn-primary">Apply filters</button></form>
<?php if($can('export')): ?><a class="btn" href="<?= e($url('/export?'.http_build_query(array_diff_key($_GET,['page'=>true])))) ?>">Export filtered Excel</a><?php endif; ?>
<div class="card rec-scroll"><table><thead><tr><th>Application</th><th>Applicant</th><th>Source / Screening</th><th>Vacancy</th><th>Received</th><th>Status</th><th>Reviewer</th></tr></thead><tbody>
<?php foreach($data['applications'] as $row): ?><tr><td><a href="<?= e($url('/show?id='.$row['id'])) ?>">#<?= e($row['id']) ?></a></td><td><?= e($row['name']) ?> <?= !$row['identity_verified']?'(identity review)':'' ?></td><td><?= e(ucfirst($row['source'])) ?><br><?= e(['minimum_met'=>'Minimum met','minimum_not_met'=>'Minimum not met','needs_review'=>'Needs review','pending'=>'Unscreened'][$row['screening_outcome']]) ?><br><?= $row['needs_review']?'Awaiting review':'Reviewed' ?></td><td><?= e($row['reference']??'Unmatched') ?></td><td><?= e($row['received_at']) ?> UTC</td><td><?= e($row['status']) ?></td><td><?= e($row['reviewer_name']) ?></td></tr><?php endforeach; ?>
<?php if(!$data['applications']): ?><tr><td colspan="7">No applications match these filters.</td></tr><?php endif; ?></tbody></table></div>
<nav><?php if($data['page']>1): ?><a href="<?= e($url('?'.http_build_query(array_replace($_GET,['page'=>$data['page']-1])))) ?>">Previous</a><?php endif; ?><span>Page <?= e($data['page']) ?></span><?php if(count($data['applications'])===50): ?><a href="<?= e($url('?'.http_build_query(array_replace($_GET,['page'=>$data['page']+1])))) ?>">Next</a><?php endif; ?></nav>
<?php if(!empty($_GET['queue'])): ?><div class="card"><h2>Failed or pending imports</h2><p>Retry from mailbox administration. Saved original messages remain available even when extraction fails.</p><?php foreach($data['failed'] as $mail): ?><p>#<?= e($mail['id']) ?> · mailbox <?= e($mail['mailbox_id']) ?> · UID <?= e($mail['uid']) ?> · <?= e($mail['processing_status']) ?> · <?= e($mail['error_code']) ?> <?php if($can('mailboxes')&&$can('quarantine')): ?><a href="<?= e($url('/raw?id='.$mail['id'])) ?>">Download quarantined original</a><?php endif; ?></p><?php endforeach; ?></div><?php endif; ?>
<?php elseif($screen==='applicants'): ?>
<form class="card" method="get"><?php $field('q','Search applicant name, email or phone',$_GET['q']??''); ?><button class="btn">Search applicants</button></form>
<div class="card rec-scroll"><table><tr><th>Applicant</th><th>Email</th><th>Phone</th><th>Identity</th><th>Applications</th></tr><?php foreach($data['applicants'] as $p): ?><tr><td><?= e($p['name']) ?></td><td><?= e($p['email_original']) ?></td><td><?= e($p['phone']) ?></td><td><?= $p['identity_verified']?'Confirmed':'Needs review' ?></td><td><a href="<?= e($url('?applicant='.$p['id'])) ?>"><?= e($p['application_count']) ?> applications</a></td></tr><?php endforeach; ?></table></div>
<nav><?php if($data['page']>1): ?><a href="<?= e($url('/applicants?'.http_build_query(array_replace($_GET,['page'=>$data['page']-1])))) ?>">Previous</a><?php endif; ?><?php if(count($data['applicants'])===50): ?><a href="<?= e($url('/applicants?'.http_build_query(array_replace($_GET,['page'=>$data['page']+1])))) ?>">Next</a><?php endif; ?></nav>
<?php elseif($screen==='create'): ?>
<form class="card" method="post" enctype="multipart/form-data" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="create"><h2>Manual application</h2><div class="rec-grid">
<?php $select('applicant_id','Existing applicant (optional)',array_column(array_filter($data['applicants'],fn($p)=>!$p['merged_into']),'name','id')); $field('name','New applicant name'); $field('email','Email','','email'); $field('phone','Phone'); $field('contact_details','Contact details'); $select('vacancy_id','Vacancy (optional)',$vacancies); ?>
</div><label>Notes<textarea name="notes" rows="3"></textarea></label><label>CV or supporting document<input type="file" name="document" accept=".pdf,.doc,.docx,.txt,.jpg,.jpeg,.png"></label><p>Documents remain in quarantine until scanned. Choose an existing applicant deliberately when they apply again.</p><button class="btn btn-primary">Create application</button></form>
<?php elseif($screen==='vacancies'): ?>
<?php if($can('edit')): ?><form method="post" class="card" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="vacancy"><h2>Create vacancy</h2><div class="rec-grid"><?php $field('reference','Vacancy reference'); $field('title','Job title'); $field('department','Department'); $field('location','Location'); $field('opens_on','Opening date','','date'); $field('closes_on','Closing date','','date'); $select('status','Status',['draft'=>'Draft','open'=>'Open','closed'=>'Closed'],'draft'); ?></div><label>Description<textarea name="description"></textarea></label><button class="btn btn-primary">Save vacancy</button></form><?php endif; ?>
<?php foreach($data['vacancies'] as $v): ?><details class="card"><summary><?= e($v['reference'].' · '.$v['title'].' · '.$v['status']) ?></summary><form method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="vacancy"><input type="hidden" name="id" value="<?= e($v['id']) ?>"><div class="rec-grid"><?php foreach(['reference'=>'Reference','title'=>'Title','department'=>'Department','location'=>'Location'] as $key=>$label) $field($key,$label,$v[$key]); $field('opens_on','Opening date',$v['opens_on'],'date'); $field('closes_on','Closing date',$v['closes_on'],'date'); $select('status','Status',['draft'=>'Draft','open'=>'Open','closed'=>'Closed'],$v['status']); ?></div><label>Description<textarea name="description"><?= e($v['description']) ?></textarea></label><?php if($can('edit')): ?><button class="btn">Update vacancy</button><?php endif; ?></form><?php require __DIR__.'/careers-vacancy.php'; ?></details><?php endforeach; ?>
<?php elseif($screen==='details'): $app=$data['app']; $p=$data['p']; ?>
<h2>Application #<?= e($app['id']) ?> · <?= e($p['name']) ?></h2><p><?= e($app['source']) ?> · <?= e($app['received_at']) ?> UTC · <?= e($app['status']) ?></p>
<form class="card" method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?= e($app['id']) ?>"><div class="rec-grid"><?php $field('name','Applicant name',$p['name']); $field('email','Email',$p['email_original'],'email'); $field('phone','Phone',$p['phone']); $field('contact_details','Contact details',$p['contact_details']); $select('vacancy_id','Vacancy',$vacancies,$app['vacancy_id']); $select('status','Recruitment status',array_combine(Rules::STATUSES,Rules::STATUSES),$app['status']); $select('reviewer_id','HR reviewer',$reviewers,$app['reviewer_id']); ?></div>
<?php foreach(['identity_verified'=>'Identity confirmed by HR','email_verified'=>'Email verified by HR','needs_review'=>'Keep in review queue'] as $key=>$label): ?><label><input type="checkbox" name="<?= e($key) ?>" value="1" <?= ($key==='needs_review'?$app[$key]:$p[$key])?'checked':'' ?>><?= e($label) ?></label><?php endforeach; ?>
<label>Notes<textarea rows="4" name="notes"><?= e($app['notes']) ?></textarea></label><p>Hired requires hiring permission, confirmed identity and a vacancy. Employee creation remains a separate HR action.</p><?php if($can('edit')): ?><button class="btn btn-primary">Update application</button><?php endif; ?></form>
<?php require __DIR__.'/careers-screening.php'; ?>
<div class="card"><h2>Documents</h2><p>Unscanned files are quarantined. Privileged quarantine downloads require explicit acknowledgement.</p><?php foreach($data['attachments'] as $file): ?><p><?= e($file['original_name']) ?> · <?= e($file['size_bytes']) ?> bytes · <?= e($file['detected_type']) ?> · <?= e($file['validation_status']) ?> · <?= e($file['scan_status']) ?> <?php if($file['scan_status']==='clean'&&$file['validation_status']==='accepted'): ?><a href="<?= e($url('/download?id='.$file['id'])) ?>">Download</a><?php elseif($can('quarantine')): ?><a href="<?= e($url('/download?id='.$file['id'].'&acknowledge=quarantine')) ?>">Acknowledge quarantine risk & download</a><?php endif; ?></p><?php endforeach; ?>
<?php if($can('edit')): ?><form method="post" enctype="multipart/form-data" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="upload"><input type="hidden" name="id" value="<?= e($app['id']) ?>"><input type="file" name="document" required><button class="btn">Upload supporting document</button></form><?php endif; ?></div>
<?php foreach($data['emails'] as $mail): ?><details class="card"><summary><?= e($mail['subject']) ?> · <?= e($mail['processing_status']) ?></summary><p>From <?= e($mail['sender']) ?> · To <?= e($mail['recipients']) ?> · <?= e($mail['received_at']) ?> UTC</p><pre><?= e($mail['body_text']) ?></pre><?php if($can('edit')): ?><form method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="link"><input type="hidden" name="id" value="<?= e($mail['id']) ?>"><?php $field('application_id','Link this email and its attachments to application ID','','number'); ?><button class="btn">Confirm email link</button></form><?php endif; ?></details><?php endforeach; ?>
<div class="card"><h2>Status history</h2><?php foreach($data['history'] as $history): ?><p><?= e($history['created_at']) ?> UTC · <?= e($history['from_status']??'Created') ?> → <?= e($history['to_status']) ?> · <?= e($history['display_name']??'Import worker') ?></p><?php endforeach; ?></div>
<div class="card"><h2>Possible duplicate applicants</h2><p>Suggestions use email, phone or document checksum. HR must confirm the identity; names alone never trigger a merge.</p><?php foreach($data['duplicates'] as $dup): ?><p>#<?= e($dup['id']) ?> · <?= e($dup['name']) ?> · <?= e($dup['email_original']) ?> · <?= e($dup['phone']) ?></p><?php endforeach; ?><?php if($can('merge')): ?><form method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="merge"><input type="hidden" name="from" value="<?= e($p['id']) ?>"><?php $field('into','Retained applicant ID','','number'); $field('reason','Reason for confirmed merge'); $field('confirm','Type MERGE to confirm'); ?><button class="btn">Merge applicant records</button></form><?php endif; ?></div>
<?php if($can('delete')): ?><form class="card" method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="archive"><input type="hidden" name="id" value="<?= e($app['id']) ?>"><p>Archiving removes this application from the active register. Documents and history are preserved.</p><button class="btn">Archive application</button></form><?php endif; ?>
<?php elseif($screen==='mailboxes'): ?>
<div class="card"><p>Mailboxes are read using verified TLS without changing read state. Configure a server host allowlist and encryption key first. No mailbox is enabled until its historical range is previewed and confirmed. Blank passwords preserve stored credentials. Retention is advisory; automatic deletion is disabled.</p><p>Scanner availability: no scanner configured by this module. All files remain quarantined.</p></div>
<?php if($data['preview']): $preview=$data['preview']; ?><form class="card" method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="sync"><input type="hidden" name="id" value="<?= e($preview['id']) ?>"><input type="hidden" name="preview_token" value="<?= e($preview['token']) ?>"><p>Preview: <?= e($preview['count']) ?> messages in <?= e($preview['folder']) ?> since <?= e($preview['since']) ?>. Messages are imported in bounded batches. Confirmation enables subsequent scheduled batches.</p><button class="btn btn-primary">Confirm historical import & enable sync</button></form><?php endif; ?>
<?php foreach(array_merge([['id'=>0,'host'=>'','port'=>993,'username'=>'','folder'=>'INBOX','initial_date'=>date('Y-m-d'),'interval_minutes'=>5,'retention_days'=>'','enabled'=>0]],$data['mailboxes']) as $m): ?>
<details class="card" <?= !$m['id']?'open':'' ?>><summary><?= $m['id']?'Mailbox #'.e($m['id']).' · '.e($m['host']).' · '.($m['enabled']?'Enabled':'Paused'):'Add mailbox' ?></summary>
<?php if($m['id']): ?><p>Last sync: <?= e($m['last_sync']??'Never') ?> UTC · Last UID <?= e($m['last_uid']) ?> · <?= e($m['last_error']) ?></p><?php endif; ?>
<form method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="action" value="mailbox"><input type="hidden" name="id" value="<?= e($m['id']) ?>"><div class="rec-grid"><?php foreach(['host'=>'IMAP host','port'=>'TLS port (993 or 143)','username'=>'Mailbox username','folder'=>'Recruitment folder','initial_date'=>'Initial import date','interval_minutes'=>'Sync interval (minutes)','retention_days'=>'Advisory retention days (blank disables)'] as $key=>$label) $field($key,$label,$m[$key],$key==='initial_date'?'date':'text'); $field('password','New password (never displayed)','','password'); ?></div><label><input type="checkbox" name="enabled" value="1" <?= $m['enabled']?'checked':'' ?>>Keep enabled (new configuration requires preview)</label><button class="btn">Save configuration</button></form>
<?php if($m['id']): ?><nav><?php foreach(['test'=>'Test TLS connection','preview'=>'Preview historical range','sync'=>'Sync / retry now'] as $action=>$label): ?><form method="post" action="<?= e($url('/save')) ?>"><?= $token() ?><input type="hidden" name="id" value="<?= e($m['id']) ?>"><button class="btn" name="action" value="<?= e($action) ?>"><?= e($label) ?></button></form><?php endforeach; ?></nav><?php endif; ?></details><?php endforeach; ?>
<div class="card rec-scroll"><h2>Import runs</h2><table><tr><th>Mailbox</th><th>Started UTC</th><th>Status</th><th>Processed</th><th>Failed</th><th>Error</th></tr><?php foreach(array_slice($data['runs'],0,100) as $run): ?><tr><td><?= e($run['mailbox_id']) ?></td><td><?= e($run['created_at']) ?></td><td><?= e($run['status']) ?></td><td><?= e($run['processed']) ?></td><td><?= e($run['failed']) ?></td><td><?= e($run['error_code']) ?></td></tr><?php endforeach; ?></table></div>
<?php endif; ?>
</section>
