<?php
declare(strict_types=1);
require_once __DIR__.'/../app/helpers/bootstrap.php';
use App\Services\ApprovalPolicyService;use App\Services\IntegrationEventOperationsService;
$passed=0;$failed=[];$check=static function(bool $ok,string $label)use(&$passed,&$failed):void{fwrite($ok?STDOUT:STDERR,($ok?'PASS ':'FAIL ').$label.PHP_EOL);$ok?$passed++:$failed[]=$label;};$throws=static function(callable $f,string $label)use($check):void{try{$f();$check(false,$label);}catch(Throwable){$check(true,$label);}};$pdo=db();$company=(int)$pdo->query('SELECT company_id FROM company_users GROUP BY company_id HAVING COUNT(DISTINCT user_id)>=2 ORDER BY company_id LIMIT 1')->fetchColumn();$actors=$pdo->query("SELECT user_id FROM company_users WHERE company_id=$company ORDER BY user_id LIMIT 2")->fetchAll(PDO::FETCH_COLUMN);$maker=(int)($actors[0]??0);$checker=(int)($actors[1]??0);$ownerRole=(int)$pdo->query("SELECT role_id FROM roles WHERE code='company_owner' LIMIT 1")->fetchColumn();if(min($company,$maker,$checker,$ownerRole)>0){$grant=$pdo->prepare('INSERT IGNORE INTO company_user_roles(company_id,user_id,role_id,assigned_by) VALUES(:company,:checker,:role,:maker)');$grant->execute(['company'=>$company,'checker'=>$checker,'role'=>$ownerRole,'maker'=>$maker]);}$_SESSION['auth']=['user_id'=>$maker,'company'=>['company_id'=>$company]];
try{$permissionStatement=$pdo->prepare('SELECT p.code FROM company_user_roles ur JOIN company_role_permissions rp ON rp.company_id=ur.company_id AND rp.role_id=ur.role_id JOIN permissions p ON p.permission_id=rp.permission_id AND p.active=TRUE WHERE ur.company_id=:company AND ur.user_id=:checker ORDER BY p.code LIMIT 1');$permissionStatement->execute(['company'=>$company,'checker'=>$checker]);$permission=(string)$permissionStatement->fetchColumn();$check(min($company,$maker,$checker)>0&&$permission!=='','Maker/checker fixtures and checker permission exist');
 $suffix=bin2hex(random_bytes(4));$policy=new ApprovalPolicyService();$policyId=$policy->save($company,['action_type'=>'integration.test.'.$suffix,'maker_checker_enabled'=>1,'minimum_amount'=>100,'maximum_amount'=>1000,'required_permission'=>$permission],$maker);$check($policyId>0,'Company policy persists configurable minimum and maximum thresholds');
 $policy->assertAndRecord($company,'integration.test.'.$suffix,'test_subject',10001,50,$maker,$maker);$check((int)$pdo->query("SELECT COUNT(*) FROM company_approval_decisions WHERE approval_policy_id=$policyId")->fetchColumn()===0,'Below-threshold action does not require a checker');
 $throws(fn()=>$policy->assertAndRecord($company,'integration.test.'.$suffix,'test_subject',10002,500,$maker,$maker),'Creator cannot approve own threshold-controlled action');
 $policy->assertAndRecord($company,'integration.test.'.$suffix,'test_subject',10002,500,$maker,$checker);$check((int)$pdo->query("SELECT COUNT(*) FROM company_approval_decisions WHERE approval_policy_id=$policyId AND maker_user_id<>checker_user_id")->fetchColumn()===1,'Independent authorized checker creates an immutable decision');
 $throws(fn()=>$policy->assertAndRecord($company,'integration.test.'.$suffix,'test_subject',10002,500,$maker,$checker),'Concurrent or duplicate approval cannot complete twice');
 $migration059=implode("\n",(require __DIR__.'/../database/migrations/mysql/059_company_approval_policies.php')['statements']);$check(str_contains($migration059,'ck_company_approval_separation')&&str_contains($migration059,'uq_company_approval_decision'),'Database enforces separation and one final decision');
 $event=sprintf('%s-%s-%s-%s-%s',bin2hex(random_bytes(4)),bin2hex(random_bytes(2)),bin2hex(random_bytes(2)),bin2hex(random_bytes(2)),bin2hex(random_bytes(6)));$insert=$pdo->prepare("INSERT INTO integration_outbox(event_id,company_id,event_type,aggregate_type,aggregate_id,payload_json,status,attempts,available_at,last_error) VALUES(:event,:company,'OperationsProof','test','1','{}','failed',3,NOW(),'Controlled failure')");$insert->execute(['event'=>$event,'company'=>$company]);$operations=new IntegrationEventOperationsService();$listed=$operations->listing(['status'=>'failed','event_type'=>'OperationsProof']);$check(count(array_filter($listed['events'],fn($row)=>$row['event_id']===$event))===1,'Failed integration event is visible in the active tenant monitor');
 $operations->retry($event,$maker);$check($pdo->query("SELECT status FROM integration_outbox WHERE event_id='$event'")->fetchColumn()==='pending','Safe retry requeues failed event without changing payload');$throws(fn()=>$operations->retry($event,$maker),'Pending or successful event cannot be casually replayed');
 $other=(int)$pdo->query("SELECT company_id FROM companies WHERE company_id<>$company ORDER BY company_id LIMIT 1")->fetchColumn();$_SESSION['auth']['company']['company_id']=$other;$check(count(array_filter($operations->listing(['event_type'=>'OperationsProof'])['events'],fn($row)=>$row['event_id']===$event))===0,'Integration monitor enforces tenant isolation');$_SESSION['auth']['company']['company_id']=$company;
 $runner=(string)file_get_contents(__DIR__.'/../bin/run-production-task.php');$check(str_contains($runner,'GET_LOCK')&&str_contains($runner,'operations_task_runs'),'Production runner has non-overlap locking and durable health state');
 $compose=(string)file_get_contents(__DIR__.'/../compose.production.yaml');$check(str_contains($compose,'integration-worker:')&&str_contains($compose,'webhook-worker:')&&str_contains($compose,'attendance-scheduler:'),'Production compose supervises all required task categories');
}catch(Throwable $e){$check(false,'Unexpected approval/operations error: '.$e->getMessage());}
fwrite(STDOUT,sprintf("Approval and operations: %d passed, %d failed.%s",$passed,count($failed),PHP_EOL));exit($failed===[]?0:1);
