<?php
declare(strict_types=1);
require __DIR__.'/../app/helpers/bootstrap.php';
require __DIR__.'/../careers/src/bootstrap.php';
use App\Services\Recruitment\{Repository,RecruitmentService,DocumentStore,CareersContract as C,CareersRequestSigner,CareersPublicationService,ScreeningService,ExternalSubmissionImporter};
if(getenv('APP_ENV')!=='testing'||getenv('DB_DATABASE')!=='office_app_test') throw new RuntimeException('Disposable database required.');
set_exception_handler(function($e){fwrite(STDERR,$e->getMessage()."\n".$e->getTraceAsString()."\n");exit(1);});
$checks=0;
$check=function($ok,$label)use(&$checks){if(!$ok)throw new RuntimeException('FAIL '.$label);$checks++;echo 'PASS '.$label."\n";};
$reject=static function($call){try{$call();return false;}catch(Throwable $e){return true;}};
$pdo=db(); $company=(int)$pdo->query("SELECT company_id FROM companies WHERE code='default'")->fetchColumn();
$r=new Repository($pdo,$company); $s=new RecruitmentService($r,new DocumentStore()); $publication=new CareersPublicationService($r);
$actor=(int)$pdo->query("SELECT user_id FROM users WHERE username='rec_fixture_owner'")->fetchColumn();
$_SESSION['auth']=['user_id'=>$actor,'company'=>['company_id'=>$company]];
$reference='CAREERS-'.bin2hex(random_bytes(5));
$vacancy=$s->vacancy(['reference'=>$reference,'title'=>'Network specialist','status'=>'draft','description'=>'Work on reliable networks','closes_on'=>gmdate('Y-m-d',time()+86400*10)],$actor);
$check($reject(fn()=>$publication->publish($vacancy,'published',$actor)),'Draft vacancy cannot publish');
$check($r->find('vacancies',$vacancy)['public_status']==='private','Saving a vacancy does not publish');
$s->vacancy(['id'=>$vacancy,'reference'=>$reference,'title'=>'Network specialist','status'=>'open','closes_on'=>gmdate('Y-m-d',time()+86400*10)],$actor);
$base=['label'=>'Years of relevant experience','criterion_type'=>'experience_years','operator'=>'gte','expected'=>'3','options'=>[],'decision_mode'=>'minimum','required'=>true,'active'=>1,'sort_order'=>10];
$criterion=$publication->saveCriterion($vacancy,$base,$actor);
$check($criterion>0,'Criterion created');
$publication->saveCriterion($vacancy,['criterion_id'=>$criterion,'label'=>'Relevant experience']+$base,$actor);
$check($publication->criteria($vacancy)[0]['label']==='Relevant experience','Criterion updated');
$other=(int)$pdo->query("SELECT company_id FROM companies WHERE company_id<>$company LIMIT 1")->fetchColumn();
$foreign=new CareersPublicationService(new Repository($pdo,$other));
$check($reject(fn()=>$foreign->saveCriterion($vacancy,$base,$actor)),'Cross-tenant criterion write denied');
$check($reject(fn()=>$foreign->publish($vacancy,'published',$actor)),'Cross-tenant publication denied');
$check($reject(fn()=>C::criterion(['criterion_type'=>'unknown']+$base)),'Unknown question type rejected');
$check($reject(fn()=>C::criterion(['operator'=>'contains']+$base)),'Invalid numeric comparison rejected');
$check($reject(fn()=>C::criterion(['expected'=>'infinity']+$base)),'Invalid numeric minimum rejected');
$temporary=$publication->saveCriterion($vacancy,['sort_order'=>0,'label'=>'Earlier question']+$base,$actor);
$check((int)$publication->criteria($vacancy)[0]['id']===$temporary,'Questions use configured order');
$publication->saveCriterion($vacancy,['criterion_id'=>$temporary,'active'=>0]+$base,$actor);
$check(count($publication->criteria($vacancy))===1,'Deactivated question excluded');
$c=C::criterion($base)+['code'=>'experience']; $engine=new ScreeningService();
$check($engine->evaluate([$c],['experience'=>'4'])['outcome']==='minimum_met','Explicit numeric minimum passes');
$failed=$engine->evaluate([$c],['experience'=>'1']);
$check($failed['outcome']==='minimum_not_met'&&$failed['answers'][0]['required']==='3'&&$failed['answers'][0]['answer']==='1','Explicit failure preserves objective explanation');
$check($engine->evaluate([$c],[])['outcome']==='needs_review','Missing mandatory answer requires review');
$check($engine->evaluate([$c],['experience'=>['bad']])['outcome']==='needs_review','Malformed answer never becomes failure');
$check($engine->evaluate([['decision_mode'=>'preference']+$c],['experience'=>'1'])['outcome']==='minimum_met','Preference cannot disqualify');
$manual=C::criterion(['criterion_type'=>'field_of_study','operator'=>'eq','expected'=>'IT','label'=>'Field']+$base)+['code'=>'field'];
$check($engine->evaluate([$manual],['field'=>'Computer Engineering'])['outcome']==='needs_review','Ambiguous field of study requires human review');
foreach(['education_level','single_choice','multiple_choice','location','boolean','document_required','text'] as $type) {
    $question=C::criterion(['criterion_type'=>$type,'operator'=>$type==='multiple_choice'?'contains':'eq','decision_mode'=>'review','options'=>['A','B']]+$base);
    // Multiple-choice comparisons are limited to deterministic set operations.
    $check($question['criterion_type']===$type,'Supported question type '.$type);
}
$revision=$publication->publish($vacancy,'published',$actor);
$v=$r->find('vacancies',$vacancy); $snapshot=C::json($r->query('SELECT payload FROM recruitment_publication_revisions WHERE company_id=? AND vacancy_id=? AND revision=?',[$company,$vacancy,$revision])->fetchColumn());
$check($revision===1&&$v['public_status']==='published','Explicit publication creates first revision');
$check(!isset($snapshot['id'])&&!isset($snapshot['company_id']),'Public payload contains no internal numeric identity');
$check($publication->publish($vacancy,'published',$actor)===2,'Publication revisions increase');
$check($publication->publish($vacancy,'closed',$actor)===3,'Closure creates a revision');
$closed=C::json($r->query('SELECT payload FROM recruitment_publication_revisions WHERE company_id=? AND vacancy_id=? AND revision=3',[$company,$vacancy])->fetchColumn());
$check(!isset($closed['questions'])&&!isset($closed['title'])&&$closed['state']==='closed','Closed payload excludes publication content');
$publication->publish($vacancy,'published',$actor);

// Separate public-site schema, synthetic fixtures only.
foreach((new App\Database\SqlStatementSplitter())->split(file_get_contents(__DIR__.'/../careers/schema.sql')) as $sql) {
    // A dedicated website test database is provided by the test setup.
    $website??=new PDO('mysql:host='.getenv('DB_HOST').';dbname=careers_test',getenv('DB_USERNAME'),getenv('DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);
    $website->exec($sql);
}
$storage=sys_get_temp_dir().'/careers-test-'.bin2hex(random_bytes(8)); mkdir($storage,0700);
$key=str_repeat('synthetic-careers-only-',3); $portal=new Careers\Portal($website,$storage,'https://careers.example.test',$key); $signer=new CareersRequestSigner($key);
$call=function($operation,$payload)use($portal,$signer){$path='/careers/integration/'.$operation;$body=json_encode($payload,JSON_THROW_ON_ERROR);$time=(string)time();$nonce=bin2hex(random_bytes(32));return $portal->integration($path,$body,['time'=>$time,'nonce'=>$nonce,'signature'=>$signer->sign('POST',$path,$time,$nonce,$body)]);};
$check($call('publication',$snapshot)['revision']===1,'Valid signed publication accepted');
$check($call('publication',$snapshot)['revision']===1,'Same publication revision is idempotent');
$check($reject(fn()=>$call('publication',['title'=>'Altered']+$snapshot)),'Changed payload at same revision rejected');
$path='/careers/integration/pending';$body='{"limit":20}';$time=(string)time();$nonce=bin2hex(random_bytes(32));$headers=['time'=>$time,'nonce'=>$nonce,'signature'=>$signer->sign('POST',$path,$time,$nonce,$body)];
$portal->integration($path,$body,$headers);
$check($reject(fn()=>$portal->integration($path,$body,$headers)),'Nonce replay denied');
$check($reject(fn()=>$portal->integration($path,$body,['signature'=>str_repeat('0',64)]+$headers)),'Bad HMAC denied');
$expired=(string)(time()-301);$newNonce=bin2hex(random_bytes(32));
$check($reject(fn()=>$portal->integration($path,$body,['time'=>$expired,'nonce'=>$newNonce,'signature'=>$signer->sign('POST',$path,$expired,$newNonce,$body)])),'Expired signed request denied');
$check($reject(fn()=>C::origin('http://careers.example.test')),'HTTP integration origin rejected');
$check($reject(fn()=>C::origin('https://user:pass@careers.example.test')),'Credentials in configured origin rejected');
$check($reject(fn()=>C::origin('https://careers.example.test/other')),'Origin cannot inject path or query');
$check($reject(fn()=>C::json('{bad')),'Malformed JSON rejected');
$check($reject(fn()=>C::json(str_repeat('a',101),100)),'Oversized JSON rejected');
$check($reject(fn()=>new CareersRequestSigner('short')),'Missing or short integration key rejected');
$pdf="%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF\n";
$files=['cv'=>['name'=>'cv.pdf','bytes'=>$pdf],'letter'=>['name'=>'letter.pdf','bytes'=>$pdf]];
$code=$snapshot['questions'][0]['code']; $input=['name'=>'Synthetic Candidate','email'=>'candidate@example.test','phone'=>'+254 700 000 000','answers'=>[$code=>'1'],'consent'=>'yes','revision'=>'1'];
$check($portal->validate($snapshot,$input,$files)===[],'Complete public form validates');
$check(isset($portal->validate($snapshot,['email'=>'bad']+$input,$files)['email']),'Public email error is field-specific');
$check(isset($portal->validate($snapshot,$input,['cv'=>$files['cv']])['letter']),'Application letter is required');
$check($reject(fn()=>C::document('cv.pdf','MZfake')),'Executable upload denied');
$check($reject(fn()=>C::document('cv.txt','plain text')),'Website only accepts PDF DOC DOCX');
$check($reject(fn()=>C::document('cv.pdf',str_repeat('a',C::MAX_FILE+1))),'Oversized document denied');
$submission=bin2hex(random_bytes(16));
$check($portal->submit($snapshot['reference'],$submission,$input,$files)===$submission,'Public form creates opaque confirmation reference');
$check($portal->submit($snapshot['reference'],$submission,$input,$files)===$submission,'Public retry returns same reference');
$check(count($portal->vacancies())===1,'Published vacancy appears in public listing');
$check(in_array($submission,$call('pending',['limit'=>20])['ids'],true),'Submitted application enters pull queue');
$payload=$call('submission',['id'=>$submission]); $importer=new ExternalSubmissionImporter($s);
$application=$importer->import($payload); $details=$s->details($application);
$check($details['app']['status']==='New'&&$details['screening']['outcome']==='minimum_not_met','Minimum failure does not reject application');
$check(count($details['attachments'])===2&&array_unique(array_column($details['attachments'],'scan_status'))===['quarantine'],'Website documents remain quarantined');
$check($importer->import($payload)===$application,'Exact ERP retry is idempotent');
$check($reject(fn()=>$importer->import(['consent'=>false]+$payload)),'Changed submission under same identity rejected');
$check($reject(fn()=>(new ExternalSubmissionImporter(new RecruitmentService(new Repository($pdo,$other),$s->store)))->import($payload)),'Foreign tenant cannot import website vacancy');
$check(count($r->applications(['source'=>'website','vacancy'=>$vacancy,'screening'=>'minimum_not_met']))===1,'Server-side source vacancy screening filters combine');
$check(count($r->applications(['source'=>'website','needs_review'=>1]))===1,'Needs-review filter finds imported application');
$check(count($r->applications(['source'=>'website'],1,1))===0,'Bounded pagination respects offset');
$check(count((new Repository($pdo,$other))->applications(['source'=>'website','vacancy'=>$vacancy]))===0,'Filter queries isolate tenants');
$check(count($r->applications(['source'=>'website','document'=>'quarantine']))===1,'Quarantine filter finds website documents');
$second=['id'=>bin2hex(random_bytes(16))]+$payload; $secondId=$importer->import($second);
$check($secondId!==$application&&str_contains($r->find('applications',$secondId)['notes'],'Possible repeat'),'Different submission imports and repeat email is flagged without merging');
$publication->saveCriterion($vacancy,['criterion_id'=>$criterion,'expected'=>'10']+$base,$actor);
$third=$importer->import(['id'=>bin2hex(random_bytes(16)),'answers'=>[$code=>'4']]+$payload);
$check($s->details($third)['screening']['outcome']==='minimum_met','Import evaluates immutable published requirement despite later HR edits');
$fourth=$importer->import(['id'=>bin2hex(random_bytes(16)),'answers'=>[$code=>['ambiguous']]]+$payload);
$check($s->details($fourth)['screening']['outcome']==='needs_review','Malformed structured answer imports for human review without rejection');
$fifth=$importer->import(['id'=>bin2hex(random_bytes(16)),'answers'=>[]]+$payload);
$check($s->details($fifth)['screening']['outcome']==='needs_review','ERP independently treats missing required answers as review');
$bad=['id'=>bin2hex(random_bytes(16)),'reference'=>'unknown']+$payload;
$check($reject(fn()=>$importer->import($bad)),'Unknown vacancy rejected');
$check($reject(fn()=>$importer->import(['id'=>bin2hex(random_bytes(16)),'revision'=>[1]]+$payload)),'Malformed revision type is rejected');
$check($reject(fn()=>$importer->import(['id'=>bin2hex(random_bytes(16)),'person'=>['name'=>['bad'],'email'=>'valid@example.test','phone'=>'123']]+$payload)),'Malformed applicant details are rejected before persistence');
$before=(int)$r->query('SELECT COUNT(*) FROM recruitment_applications WHERE company_id=?',[$company])->fetchColumn();
$pdo->exec("CREATE TRIGGER careers_attachment_failure BEFORE INSERT ON recruitment_attachments FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Synthetic failure'");
try {$check($reject(fn()=>$importer->import(['id'=>bin2hex(random_bytes(16))]+$payload)),'Injected attachment persistence failure rejects import');}finally{$pdo->exec('DROP TRIGGER careers_attachment_failure');}
$check((int)$r->query('SELECT COUNT(*) FROM recruitment_applications WHERE company_id=?',[$company])->fetchColumn()===$before,'Failed import rolls back application transaction');
$check($call('ack',['id'=>$submission,'checksum'=>hash('sha256',json_encode($payload,JSON_THROW_ON_ERROR))])['acknowledged'],'Acknowledgement matches imported content');
$check(!in_array($submission,$call('pending',['limit'=>20])['ids'],true),'Acknowledged submission leaves pending queue');
$publication->review($application,$actor);
$check($s->details($application)['screening']['reviewed_by']==$actor,'Manual screening review records actor');
$publication->publish($vacancy,'closed',$actor);
$check($reject(fn()=>$importer->import(['id'=>bin2hex(random_bytes(16))]+$payload)),'ERP independently rejects closed vacancy intake');
$check($importer->import($payload)===$application,'Completed import remains idempotent after vacancy closes');
$call('publication',$closed);
$check($portal->vacancies()===[],'Closed vacancy removed from public listing');
$check($reject(fn()=>$portal->submit($snapshot['reference'],bin2hex(random_bytes(16)),$input,$files)),'Website rejects submissions after closing');
$check($portal->submit($snapshot['reference'],$submission,$input,$files)===$submission,'Public retry remains idempotent after closing');
for($i=0;$i<10;$i++)$portal->limit('192.0.2.10');
$check($reject(fn()=>$portal->limit('192.0.2.10')),'Persistent rate limit denies excess attempts');
$check((int)$r->query("SELECT COUNT(*) FROM recruitment_external_submissions WHERE company_id=? AND source_submission_id=?",[$company,$submission])->fetchColumn()===1,'Database has one durable external identity');
$check($reject(fn()=>$r->insert('external_submissions',['source_submission_id'=>$submission,'source_vacancy_reference'=>$snapshot['reference'],'submitted_at'=>gmdate('Y-m-d H:i:s'),'payload_checksum'=>str_repeat('a',64)])),'Database uniqueness rejects duplicate source identity');
$check($reject(fn()=>$r->query('INSERT INTO recruitment_application_answers(company_id,application_id,criterion_id,question_snapshot) VALUES(?,?,?,?)',[$other,$application,$criterion,'{}'])),'Composite tenant foreign keys reject crossed answers');
echo "$checks careers integration checks passed\n";
