<?php
declare(strict_types=1);
use App\Services\SalesService;
require_once __DIR__.'/../app/helpers/bootstrap.php';
$company=(int)db()->query("SELECT company_id FROM companies WHERE code='default' LIMIT 1")->fetchColumn();
$actor=(int)db()->query('SELECT user_id FROM users ORDER BY user_id LIMIT 1')->fetchColumn();
$_SESSION['auth']=['user_id'=>$actor,'company'=>['company_id'=>$company]];$s=new SalesService();$x=strtoupper(bin2hex(random_bytes(3)));$f=[];
$check=function(bool $ok,string $m)use(&$f){fwrite($ok?STDOUT:STDERR,($ok?'PASS ':'FAIL ').$m.PHP_EOL);if(!$ok)$f[]=$m;};
try{
$territory=$s->createTerritory(['code'=>'CT-'.$x,'name'=>'Commercial '.$x],$actor);
$agent=$s->createAgent(['agent_code'=>'CA-'.$x,'name'=>'Seller '.$x,'agent_type'=>'DSA','territory_id'=>$territory['id']],$actor);
$customer=$s->createCustomer(['customer_number'=>'CC-'.$x,'name'=>'Customer '.$x,'customer_type'=>'business','preferred_currency'=>'ETB','credit_mode'=>'unlimited','credit_limit'=>0,'payment_terms_days'=>30],$actor);
$product=$s->createProduct(['sku'=>'CP-'.$x,'name'=>'Product '.$x,'product_type'=>'service','unit_of_measure'=>'unit','unit_price'=>100,'commission_rate'=>0],$actor);
$price=$s->createPricelist(['name'=>'Price '.$x,'currency'=>'ETB','product_id'=>$product['id'],'minimum_quantity'=>1,'calculation'=>'fixed','fixed_price'=>90,'priority'=>10],$actor);
$team=$s->createSalesTeam(['name'=>'Team '.$x,'leader_agent_id'=>$agent['id'],'territory_id'=>$territory['id'],'member_ids'=>[$agent['id']]],$actor);
$customerEdit=$s->updateCustomer((int)$customer['id'],['customer_number'=>'CC-'.$x,'name'=>'Customer '.$x,'legal_name'=>'Legal '.$x,'customer_type'=>'business','tax_number'=>'VAT-'.$x,'email'=>strtolower($x).'@example.test','phone'=>'111','mobile'=>'222','address'=>'Billing contact','street'=>'Main Street','street2'=>'Suite 2','city'=>'Addis Ababa','state_region'=>'Addis Ababa','postal_code'=>'1000','country'=>'Ethiopia','preferred_currency'=>'ETB','credit_mode'=>'unlimited','credit_limit'=>0,'credit_status'=>'active','payment_terms_days'=>30,'territory_id'=>$territory['id'],'agent_id'=>$agent['id'],'team_id'=>$team['id'],'pricelist_id'=>$price['id']],$actor);$customerStored=$s->customer((int)$customer['id']);
$check(!empty($customerEdit['successful'])&&$customerStored['legal_name']==='Legal '.$x&&$customerStored['mobile']==='222'&&(int)$customerStored['team_id']===(int)$team['id']&&(int)$customerStored['pricelist_id']===(int)$price['id'],'Expanded customer fields and commercial assignments persist and reload');
$productEdit=$s->updateProduct((int)$product['id'],['sku'=>'CP-'.$x,'name'=>'Product '.$x,'category'=>'Services','product_type'=>'service','unit_of_measure'=>'license','unit_price'=>100,'commission_rate'=>0],$actor);$productStored=$s->product((int)$product['id']);
$check(!empty($productEdit['successful'])&&$productStored['category']==='Services'&&$productStored['product_type']==='service'&&$productStored['unit_of_measure']==='license','Shared product Sales fields persist and reload');
$quote=$s->createQuotation(['customer_id'=>$customer['id'],'agent_id'=>$agent['id'],'team_id'=>$team['id'],'pricelist_id'=>$price['id'],'quotation_date'=>date('Y-m-d'),'expiration_date'=>date('Y-m-d',strtotime('+7 days')),'payment_terms_days'=>30,'currency'=>'ETB','lines'=>[['product_id'=>$product['id'],'quantity'=>2,'discount_amount'=>10,'tax_rate'=>15]]],$actor);
$workspace=$s->workspace();$stored=array_values(array_filter($workspace['quotations'],fn($q)=>(int)$q['quotation_id']===(int)$quote['id']))[0]??null;
$check(!empty($price['successful'])&&!empty($team['successful'])&&!empty($quote['successful'])&&is_array($stored),'Pricelist, sales team and quotation persist and reload');
$line=db()->query('SELECT unit_price,untaxed_amount,line_total FROM sales_quotation_lines WHERE quotation_id='.(int)$quote['id'])->fetch(PDO::FETCH_ASSOC);
$check((float)$line['unit_price']===90.0&&(float)$line['untaxed_amount']===170.0&&(float)$line['line_total']===195.5,'Pricelist price is resolved before discount and tax and stored as a snapshot');
$edited=$s->updateQuotation((int)$quote['id'],['customer_id'=>$customer['id'],'agent_id'=>$agent['id'],'team_id'=>$team['id'],'pricelist_id'=>$price['id'],'quotation_date'=>date('Y-m-d'),'expiration_date'=>date('Y-m-d',strtotime('+10 days')),'payment_terms_days'=>45,'currency'=>'ETB','billing_address'=>'Billing '.$x,'delivery_address'=>'Delivery '.$x,'notes'=>'Edited '.$x,'lines'=>[['product_id'=>$product['id'],'quantity'=>3,'discount_amount'=>0,'tax_rate'=>15]]],$actor);
$reloaded=$s->quotation((int)$quote['id']);
$check(!empty($edited['successful'])&&$reloaded['notes']==='Edited '.$x&&(float)$reloaded['lines'][0]['quantity']===3.0&&(float)$reloaded['total_amount']===310.5,'Draft quotation edit recalculates, persists and reloads');
$priceDetail=$s->pricelist((int)$price['id']);$ruleId=(int)$priceDetail['rules'][0]['rule_id'];$changed=$s->updatePricelistRule((int)$price['id'],$ruleId,['product_id'=>$product['id'],'minimum_quantity'=>1,'calculation'=>'fixed','fixed_price'=>80,'priority'=>10]);$historical=$s->quotation((int)$quote['id']);$newQuote=$s->createQuotation(['customer_id'=>$customer['id'],'pricelist_id'=>$price['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>[['product_id'=>$product['id'],'quantity'=>1,'tax_rate'=>0]]],$actor);$newStored=$s->quotation((int)$newQuote['id']);
$check(!empty($changed['successful'])&&(float)$historical['lines'][0]['unit_price']===90.0&&(float)$newStored['lines'][0]['unit_price']===80.0,'Pricelist rule edit affects new quotations while historical price remains unchanged');
$percent=$s->createPricelist(['name'=>'Percent '.$x,'currency'=>'ETB','product_id'=>$product['id'],'minimum_quantity'=>1,'calculation'=>'percentage','percentage_adjustment'=>-10,'priority'=>20],$actor);$percentQuote=$s->createQuotation(['customer_id'=>$customer['id'],'pricelist_id'=>$percent['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>[['product_id'=>$product['id'],'quantity'=>1]]],$actor);$percentStored=$s->quotation((int)$percentQuote['id']);
$check((float)$percentStored['lines'][0]['unit_price']===90.0,'Percentage pricelist rule resolves server-side');
$tier=$s->createPricelist(['name'=>'Tier '.$x,'currency'=>'ETB','product_id'=>$product['id'],'minimum_quantity'=>1,'calculation'=>'fixed','fixed_price'=>95,'priority'=>50],$actor);$tierRule=$s->addPricelistRule((int)$tier['id'],['product_id'=>$product['id'],'minimum_quantity'=>5,'calculation'=>'fixed','fixed_price'=>75,'priority'=>50]);$one=$s->createQuotation(['customer_id'=>$customer['id'],'pricelist_id'=>$tier['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>[['product_id'=>$product['id'],'quantity'=>1]]],$actor);$five=$s->createQuotation(['customer_id'=>$customer['id'],'pricelist_id'=>$tier['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>[['product_id'=>$product['id'],'quantity'=>5]]],$actor);$invalid=$s->addPricelistRule((int)$tier['id'],['minimum_quantity'=>1,'calculation'=>'fixed','fixed_price'=>1,'rule_from'=>date('Y-m-d',strtotime('+2 days')),'rule_to'=>date('Y-m-d')]);
$check((float)$s->quotation((int)$one['id'])['lines'][0]['unit_price']===95.0&&(float)$s->quotation((int)$five['id'])['lines'][0]['unit_price']===75.0&&empty($invalid['successful']),'Minimum quantity precedence is deterministic and invalid validity is rejected');
$makeLines=static fn(int $count):array=>array_fill(0,$count,['product_id'=>$product['id'],'quantity'=>1,'discount_amount'=>0,'tax_rate'=>0]);
$oneLine=$s->createQuotation(['customer_id'=>$customer['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>$makeLines(1)],$actor);
$sixLine=$s->createQuotation(['customer_id'=>$customer['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>$makeLines(6)],$actor);
$twentyLine=$s->createQuotation(['customer_id'=>$customer['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>$makeLines(20)],$actor);
$check(count($s->quotation((int)$oneLine['id'])['lines'])===1,'Dynamic quotation accepts one line');
$check(count($s->quotation((int)$sixLine['id'])['lines'])===6,'Dynamic quotation accepts six lines');
$check(count($s->quotation((int)$twentyLine['id'])['lines'])===20,'Dynamic quotation accepts twenty lines atomically');
$withEmpty=$makeLines(2);array_splice($withEmpty,1,0,[['product_id'=>'','quantity'=>'']]);$emptyIgnored=$s->createQuotation(['customer_id'=>$customer['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>$withEmpty],$actor);
$check(count($s->quotation((int)$emptyIgnored['id'])['lines'])===2,'Completely empty temporary quotation row is ignored');
$zero=$s->createQuotation(['customer_id'=>$customer['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>[['product_id'=>$product['id'],'quantity'=>0]]],$actor);
$negative=$s->createQuotation(['customer_id'=>$customer['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>[['product_id'=>$product['id'],'quantity'=>-1]]],$actor);
$badProduct=$s->createQuotation(['customer_id'=>$customer['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>[['product_id'=>PHP_INT_MAX,'quantity'=>1]]],$actor);
$check(empty($zero['successful'])&&str_contains(implode(' ',$zero['errors']),'greater than zero'),'Zero quotation quantity is rejected');
$check(empty($negative['successful']),'Negative quotation quantity is rejected');
$check(empty($badProduct['successful']),'Invalid or cross-tenant product identifier is rejected');
$viewSource=file_get_contents(__DIR__.'/../resources/views/sales/quotation.php');
$controllerSource=file_get_contents(__DIR__.'/../app/controllers/SalesController.php');
$check(str_contains($viewSource,'data-add-line')&&str_contains($viewSource,'data-remove-line')&&str_contains($controllerSource,"\$_POST['lines']"),'Quotation client and server use variable nested line arrays');
$confirmed=$s->transitionQuotation((int)$quote['id'],'confirm',$actor);$replay=$s->transitionQuotation((int)$quote['id'],'confirm',$actor);
$count=(int)db()->query('SELECT COUNT(*) FROM sales_orders WHERE order_id='.(int)($confirmed['orderId']??0))->fetchColumn();
$orderId=(int)($confirmed['orderId']??0);$submittedOrder=$s->orderDetail($orderId);
$pickingBeforeApproval=(int)db()->query('SELECT COUNT(*) FROM inventory_pickings WHERE sales_order_id='.$orderId." AND picking_type='delivery'")->fetchColumn();
$check(!empty($confirmed['successful'])&&$count===1&&!empty($replay['replayed'])&&($submittedOrder['status']??'')==='submitted'&&$pickingBeforeApproval===0,'Quotation confirmation creates one idempotent Submitted sales order without auto-approval or delivery');

$approval=$s->transitionOrder($orderId,'approve',null,$actor,'commercial-approve-'.$x);$approvedOrder=$s->orderDetail($orderId);
$pickingBeforeConfirm=(int)db()->query('SELECT COUNT(*) FROM inventory_pickings WHERE sales_order_id='.$orderId." AND picking_type='delivery'")->fetchColumn();
$check(!empty($approval['successful'])&&($approvedOrder['status']??'')==='approved'&&$pickingBeforeConfirm===0,'Sales Order requires explicit manual approval and approval does not prepare delivery');

$confirmation=$s->transitionOrder($orderId,'confirm',null,$actor,'commercial-confirm-'.$x);$confirmedOrder=$s->orderDetail($orderId);
$pickingAfterConfirm=(int)db()->query('SELECT COUNT(*) FROM inventory_pickings WHERE sales_order_id='.$orderId." AND picking_type='delivery'")->fetchColumn();
$check(!empty($confirmation['successful'])&&($confirmedOrder['status']??'')==='confirmed'&&$pickingAfterConfirm===0&&empty($confirmation['deliveryRequired']),'Explicit manual confirmation confirms a service-only Sales Order without creating Inventory delivery');

$invoice=$s->createInvoice($orderId,'ordered',$actor);$invoiceReplay=$s->createInvoice($orderId,'ordered',$actor);$orderDetail=$s->orderDetail($orderId);
$check(($orderDetail['status']??'')==='confirmed'&&!empty($invoice['successful'])&&!empty($invoiceReplay['successful'])&&(int)$invoice['invoiceId']===(int)$invoiceReplay['invoiceId']&&(float)$orderDetail['lines'][0]['invoiced_quantity']===3.0,'Confirmed Sales Order supports idempotent ordered-policy invoicing without duplicating quantity');$locked=$s->updateQuotation((int)$quote['id'],['customer_id'=>$customer['id'],'quotation_date'=>date('Y-m-d'),'currency'=>'ETB','lines'=>[['product_id'=>$product['id'],'quantity'=>1]]],$actor);
$check(empty($locked['successful']),'Confirmed quotation cannot be edited');
}catch(Throwable $e){$f[]=$e::class.': '.$e->getMessage();fwrite(STDERR,'FAIL '.end($f).PHP_EOL);}
fwrite(STDOUT,"Sales commercial integration: ".count($f)." failure(s)\n");exit($f===[]?0:1);
