<?php
declare(strict_types=1);
require_once __DIR__.'/../app/helpers/bootstrap.php';
use App\Repositories\MySql\SettlementRepository;
use App\Services\BankIntegration\BankConnectorInterface;
use App\Services\BankIntegration\ManualBankConnector;
use App\Services\EtbAmountInWords;
use App\Services\SalesSettlementDocumentService;

$passed=0;$failed=0;$check=static function(bool $ok,string $label)use(&$passed,&$failed):void{echo ($ok?'PASS ':'FAIL ').$label.PHP_EOL;$ok?$passed++:$failed++;};
$companies=db()->query('SELECT company_id FROM companies ORDER BY company_id')->fetchAll(PDO::FETCH_COLUMN);$users=db()->query('SELECT user_id FROM users ORDER BY user_id LIMIT 2')->fetchAll(PDO::FETCH_COLUMN);
$company=(int)($companies[1]??$companies[0]??0);$other=(int)($companies[2]??$companies[0]??0);$maker=(int)($users[0]??0);$checker=(int)($users[1]??$maker+1);$repo=new SettlementRepository();
try{
 $check((new ManualBankConnector()) instanceof BankConnectorInterface,'Bank connector is provider-swappable');$check((new ManualBankConnector())->testConnection()['available']===true,'Manual confirmation provider is active without claiming a live API');
 $words=new EtbAmountInWords();$check($words->convert(0)==='Zero Ethiopian Birr Only','ETB words handles zero');$check(str_contains($words->convert('12345.50'),'Twelve Thousand')&&str_contains($words->convert('12345.50'),'Fifty Cents'),'ETB words handles business values and cents');
 $bank=$repo->saveBankAccount($company,['bank_name'=>'Integration Bank','account_name'=>'OfficeApp Test','account_number'=>'TEST-'.bin2hex(random_bytes(4)),'branch'=>'Head Office','currency'=>'ETB','swift_bic'=>'TESTETAA','provider_code'=>'manual','is_default'=>true],$maker);$check($bank>0,'Company-scoped bank account is created');
 $insert=db()->prepare("INSERT INTO sales_settlements(company_id,settlement_number,bank_account_id,currency,expected_amount,variance_amount,remaining_amount,reconciliation_status,workflow_status,created_by,submitted_by,submitted_at) VALUES(:c,:n,:b,'ETB',100000,-100000,100000,'awaiting_confirmation','submitted',:creator,:submitter,NOW())");
 $insert->execute(['c'=>$company,'n'=>'SET-E2E-MATCH-'.bin2hex(random_bytes(3)),'b'=>$bank,'creator'=>$maker,'submitter'=>$maker]);$matched=(int)db()->lastInsertId();
 $repo->addConfirmation($company,$matched,['bank_reference'=>'MATCH-'.bin2hex(random_bytes(3)),'transaction_date'=>date('Y-m-d'),'confirmed_amount'=>100000,'evidence_path'=>__FILE__,'evidence_original_name'=>'bank-receipt.pdf','evidence_mime'=>'application/pdf','evidence_size'=>filesize(__FILE__),'evidence_sha256'=>hash_file('sha256',__FILE__)],$maker);$row=$repo->find($company,$matched);$check($row['reconciliation_status']==='matched'&&(float)$row['variance_amount']===0.0&&(float)$row['remaining_amount']===0.0,'Exact confirmation automatically reconciles as matched');
 $repo->transition($company,$matched,'review','Supervisor checked evidence',$checker);$repo->transition($company,$matched,'reconcile','Finance verified bank credit',$checker);$selfBlocked=false;try{$repo->transition($company,$matched,'approve','',$maker);}catch(Throwable){$selfBlocked=true;}$check($selfBlocked,'Maker cannot self-final-approve');$repo->transition($company,$matched,'approve','Authorized checker approval',$checker);$row=$repo->find($company,$matched);$check($row['workflow_status']==='closed','Matched settlement completes maker/checker workflow and closes');
 $advice=(new SalesSettlementDocumentService())->settlement($company,$matched,'advice');$recon=(new SalesSettlementDocumentService())->settlement($company,$matched,'reconciliation');$check(str_starts_with($advice['content'],'%PDF')&&strlen($advice['content'])>1000,'Deposit Advice is a non-empty PDF');$check(str_starts_with($recon['content'],'%PDF')&&strlen($recon['content'])>1000,'Settlement Reconciliation is a non-empty PDF');$check($repo->find($other,$matched)===null,'Settlement lookup enforces tenant isolation');
 $insert=db()->prepare("INSERT INTO sales_settlements(company_id,settlement_number,bank_account_id,currency,expected_amount,variance_amount,remaining_amount,reconciliation_status,workflow_status,created_by,submitted_at) VALUES(:c,:n,:b,'ETB',100000,-100000,100000,'awaiting_confirmation','submitted',:u,NOW())");
 $insert->execute(['c'=>$company,'n'=>'SET-E2E-MISMATCH-'.bin2hex(random_bytes(3)),'b'=>$bank,'u'=>$maker]);$mismatch=(int)db()->lastInsertId();$repo->addConfirmation($company,$mismatch,['bank_reference'=>'MISMATCH-'.bin2hex(random_bytes(3)),'transaction_date'=>date('Y-m-d'),'confirmed_amount'=>95000,'evidence_path'=>__FILE__,'evidence_original_name'=>'bank-receipt.png','evidence_mime'=>'image/png','evidence_size'=>filesize(__FILE__),'evidence_sha256'=>hash_file('sha256',__FILE__)],$maker);$row=$repo->find($company,$mismatch);$check($row['reconciliation_status']==='partial'&&(float)$row['variance_amount']===-5000.0&&(float)$row['remaining_amount']===5000.0,'95,000 against 100,000 remains partial with -5,000 variance');$repo->transition($company,$mismatch,'review','Mismatch acknowledged',$checker);$repo->transition($company,$mismatch,'reconcile','Finance review required',$checker);$closeBlocked=false;try{$repo->transition($company,$mismatch,'approve','',$checker);}catch(Throwable){$closeBlocked=true;}$check($closeBlocked&&$repo->find($company,$mismatch)['workflow_status']==='finance_reconciled','Mismatch cannot silently approve or close');
 $duplicateBlocked=false;try{$repo->addConfirmation($company,$mismatch,['bank_reference'=>$row['confirmations'][0]['bank_reference'],'transaction_date'=>date('Y-m-d'),'confirmed_amount'=>5000,'evidence_path'=>__FILE__,'evidence_original_name'=>'duplicate.pdf','evidence_mime'=>'application/pdf','evidence_size'=>filesize(__FILE__),'evidence_sha256'=>hash_file('sha256',__FILE__)],$maker);}catch(Throwable){$duplicateBlocked=true;}$check($duplicateBlocked,'Duplicate bank reference is rejected safely');
 $check((int)db()->query("SELECT COUNT(*) FROM sales_settlement_events WHERE company_id=$company AND settlement_id IN($matched,$mismatch)")->fetchColumn()>=7,'Settlement actions retain an audit timeline');
}catch(Throwable $e){echo 'FAIL unexpected: '.$e->getMessage().PHP_EOL;$failed++;}
echo PHP_EOL.($passed+$failed).' settlement checks, '.$failed.' failures'.PHP_EOL;exit($failed===0?0:1);
