<?php
declare(strict_types=1);
require_once __DIR__.'/../app/helpers/bootstrap.php';
require_once __DIR__.'/support/licensed-import-fixture.php';
use App\Services\DataExchange\{ImportService,ExternalIdService,ImportConfirmation};
use App\Services\SalesService;
use App\Repositories\AuditLogWriter;
if(getenv('APP_ENV')!=='testing')throw new RuntimeException('Isolated testing database required.');
set_exception_handler(static function(Throwable $e):void{fwrite(STDERR,$e->getMessage().PHP_EOL.$e->getTraceAsString().PHP_EOL);exit(1);});
$db=db();$checks=0;$oldAuth=$_SESSION['auth']??null;$prefix='IMP'.strtoupper(bin2hex(random_bytes(4)));
$check=static function(bool $ok,string $label)use(&$checks):void{if(!$ok)throw new RuntimeException('FAIL '.$label);++$checks;echo 'PASS '.$label.PHP_EOL;};
$scalar=static function(string $sql,array $args=[])use($db):mixed{$q=$db->prepare($sql);$q->execute($args);return $q->fetchColumn();};
$company=(int)$scalar('SELECT company_id FROM companies WHERE deleted_at IS NULL ORDER BY company_id LIMIT 1');
$db->beginTransaction();
try {
    $actor=licensedImportFixture($db,$company,$prefix);$service=new ImportService();$ids=new ExternalIdService();
    $mapping=[0=>'external_id',1=>'customer_number',2=>'name',3=>'email'];$rows=[];
    for($i=1;$i<=105;++$i)$rows[]=[$prefix.'C'.$i,$prefix.'C'.$i,'Customer '.$i,$prefix.$i.'@example.test'];
    $count=(int)$scalar('SELECT COUNT(*) FROM sales_customers');
    $preview=$service->test('customers',$rows,$mapping)['result'];
    $check($preview->valid===105&&$preview->errors===[]&&(int)$scalar('SELECT COUNT(*) FROM sales_customers')===$count,'Preview validates all 105 rows without writes');
    $bad=$rows;$bad[104][3]='invalid';$result=$service->import('customers',$bad,$mapping,$actor);
    $check($result->created===0&&$result->invalidRows===1&&$result->errors[0]['row']===106&&(int)$scalar('SELECT COUNT(*) FROM sales_customers')===$count,'Invalid row 106 blocks every write and reports the actual row');
    $duplicate=$rows;$duplicate[104][1]=$duplicate[0][1];$result=$service->test('customers',$duplicate,$mapping)['result'];
    $check($result->duplicateRows===1&&$result->failed>0,'Duplicate business codes across distant rows are rejected');
    $result=$service->import('customers',$rows,$mapping,$actor);
    $check($result->created===105&&$result->failed===0,'Create mode imports all 105 valid customers');
    $result=$service->import('customers',$rows,$mapping,$actor);
    $check($result->created===0&&$result->duplicateRows===105,'Create replay cannot silently overwrite existing records');
    $first=$ids->resolve($company,'customers',$rows[0][0]);
    $db->prepare("UPDATE sales_customers SET phone='KEEP',credit_mode='fixed',credit_limit=500,street='Keep street',active=0 WHERE customer_id=?")->execute([$first]);
    $rows[0][2]='Updated name';$result=$service->import('customers',[$rows[0]],$mapping,$actor,'update');
    $check($result->updated===1&&$result->failed===0,'Explicit update resolves an existing company External ID');
    $check((int)$scalar("SELECT COUNT(*) FROM sales_customers WHERE customer_id=? AND name='Updated name' AND phone='KEEP' AND credit_limit=500 AND credit_mode='fixed' AND street='Keep street' AND active=0",[$first])===1,'Customer update preserves unmapped address, credit policy and active status');
    $result=$service->test('customers',[[$prefix.'UNKNOWN',$prefix.'OTHER','Unknown','a@example.test']],$mapping,'update')['result'];
    $check($result->failed>0,'Update mode rejects unknown External IDs');
    $result=$service->test('customers',[[$prefix.' invalid',$prefix.'BAD','Invalid ID','a@example.test']],$mapping)['result'];
    $check($result->failed>0,'Invalid External IDs fail during preview');
    $result=$service->test('customers',[[$prefix.'NEG',$prefix.'NEG','Negative','-1']],[0=>'external_id',1=>'customer_number',2=>'name',3=>'credit_limit'])['result'];
    $check($result->failed>0,'Negative credit limit fails preview');
    $productRows=[[$prefix.'P',$prefix.'P','Product','stockable','piece','1']];$productMap=[0=>'external_id',1=>'sku',2=>'name',3=>'product_type',4=>'unit_of_measure',5=>'serial_tracking'];
    $result=$service->import('products',$productRows,$productMap,$actor);
    $check($result->created===1,'Product master import uses supported domain fields');
    $product=$ids->resolve($company,'products',$prefix.'P');
    $db->prepare('UPDATE sales_products SET commission_rate=7.5 WHERE product_id=?')->execute([$product]);
    $result=$service->import('products',[[$prefix.'P',$prefix.'P','Renamed product']],[0=>'external_id',1=>'sku',2=>'name'],$actor,'update');
    $check($result->updated===1&&(int)$scalar("SELECT COUNT(*) FROM sales_products WHERE product_id=? AND serial_tracking=1 AND product_type='stockable' AND unit_of_measure='piece' AND commission_rate=7.5",[$product])===1,'Product update preserves unmapped operational fields');
    $badProduct=$productRows;$badProduct[0][0].='B';$badProduct[0][1].='B';$badProduct[0][3]='made_up';$badProduct[0][5]='maybe';
    $check($service->test('products',$badProduct,$productMap)['result']->failed>=2,'Product type and boolean domains are checked during preview');
    $check($service->test('products',$productRows,$productMap+[6=>'unit_price'])['result']->failed>0,'Import cannot accept an unsupported pricing override');
    $quote=[[$prefix.'Q',$rows[1][1],$prefix.'P','2','2026-01-05','Note'],[$prefix.'Q',$rows[1][1],$prefix.'P','3','2026-01-05','Note']];
    $quoteMap=[0=>'external_id',1=>'customer',2=>'product',3=>'quantity',4=>'quotation_date',5=>'notes'];
    $check($service->test('quotations',$quote,$quoteMap)['result']->failed>0,'Quotation preview rejects a product without approved pricing');
    $db->prepare("INSERT INTO sales_product_price_changes(company_id,product_id,old_price,proposed_price,currency,effective_from,reason,status,requested_by,requested_at) VALUES(?,?,0,20,'ETB','2024-01-01','Test pricing','approved',?,'2024-01-01')")->execute([$company,$product,$actor]);
    $result=$service->import('quotations',$quote,$quoteMap,$actor);$quotation=$ids->resolve($company,'quotations',$prefix.'Q');
    $check($result->created===1&&(float)$scalar('SELECT total_amount FROM sales_quotations WHERE quotation_id=?',[$quotation])===100.0,'Grouped quotation uses all lines and approved domain pricing');
    $db->prepare("UPDATE sales_quotations SET billing_address='Keep address' WHERE quotation_id=?")->execute([$quotation]);
    $quoteUpdate=[[$prefix.'Q',$rows[1][1],$prefix.'P','4']];$quoteUpdateMap=array_slice($quoteMap,0,4,true);
    $result=$service->import('quotations',$quoteUpdate,$quoteUpdateMap,$actor,'update');
    $check($result->updated===1&&(int)$scalar("SELECT COUNT(*) FROM sales_quotations WHERE quotation_id=? AND total_amount=80 AND quotation_date='2026-01-05' AND notes='Note' AND billing_address='Keep address'",[$quotation])===1,'Draft replacement preserves unmapped header fields and recalculates lines');
    $db->prepare("UPDATE sales_quotations SET status='sent' WHERE quotation_id=?")->execute([$quotation]);
    $check($service->test('quotations',$quoteUpdate,$quoteUpdateMap,'update')['result']->failed>0,'Non-draft quotation updates are rejected before writing');
    $quote[0][0]=$quote[1][0]=$prefix.'BADDATE';$quote[0][4]=$quote[1][4]='2026-02-30';
    $check($service->test('quotations',$quote,$quoteMap)['result']->invalidRows===2,'Impossible calendar dates are rejected on every quotation row');
    $check($service->test('quotations',[[$prefix.'MISSING']],[0=>'external_id'])['result']->failed>0,'Missing quotation fields return validation errors');
    $db->prepare("INSERT INTO sales_products(company_id,sku,name,product_type,unit_price) VALUES(?,?,?,'service',0),(?,?,?,'service',0)")->execute([$company,$prefix.'AMB1','Ambiguous '.$prefix,$company,$prefix.'AMB2','Ambiguous '.$prefix]);
    $check($service->test('quotations',[[$prefix.'AMBQ',$rows[1][1],'Ambiguous '.$prefix,1]],$quoteUpdateMap)['result']->failed>0,'Ambiguous names require a unique business code');
    $badHeader=[[$prefix.'HEADER',$rows[1][1],$prefix.'P',1],[$prefix.'HEADER',$rows[2][1],$prefix.'P',1]];
    $check($service->test('quotations',$badHeader,$quoteUpdateMap)['result']->failed>0,'Grouped quotation cannot mix different customers');
    $fault=new class implements AuditLogWriter {
        private int $writes=0;
        public function record(?int $userId,string $action,string $module,?string $tableName=null,?string $recordId=null,?array $oldValues=null,?array $newValues=null,?int $companyId=null):void {
            if(++$this->writes===2)throw new RuntimeException('Intentional second-row persistence failure');
        }
    };
    $failing=new ImportService(sales:new SalesService(audit:$fault));
    $count=(int)$scalar('SELECT COUNT(*) FROM sales_customers');
    $result=$failing->import('customers',[[$prefix.'FAIL1',$prefix.'FAIL1','First'],[$prefix.'FAIL2',$prefix.'FAIL2','Second']],[0=>'external_id',1=>'customer_number',2=>'name'],$actor);
    $check($result->created===0&&$result->failed>0&&(int)$scalar('SELECT COUNT(*) FROM sales_customers')===$count&&$db->inTransaction(),'Persistence failure rolls back earlier rows within a caller-owned transaction');
    $check($ids->resolve($company,'customers',$prefix.'FAIL1')===null,'Rollback includes External IDs from earlier successful rows');
    $denied=false;try{$service->import('customers',[],$mapping,$actor+1000);}catch(Throwable){$denied=true;}$check($denied,'Import actor cannot impersonate another user');
    $path=tempnam(sys_get_temp_dir(),'confirm-');file_put_contents($path,'immutable upload');
    $stored=ImportConfirmation::context()+['path'=>$path,'validated'=>ImportConfirmation::fingerprint($path,$mapping,'create')];
    ImportConfirmation::assertConfirmed($stored,$mapping,'create');$denied=false;try{ImportConfirmation::assertConfirmed($stored,$mapping,'update');}catch(Throwable){$denied=true;}unlink($path);
    $check($denied,'Confirmation is bound to the reviewed import mode');
    $foreign=(int)$scalar('SELECT company_id FROM companies WHERE company_id<>? AND deleted_at IS NULL LIMIT 1',[$company]);
    if(!$foreign){$db->prepare('INSERT INTO companies(code,name) VALUES(?,?)')->execute([$prefix.'F','Foreign fixture']);$foreign=(int)$db->lastInsertId();}
    licensedImportFixture($db,$foreign,$prefix.'F');
    $check($service->test('customers',[$rows[1]],$mapping,'update')['result']->failed>0,'External IDs cannot resolve into another company');
    $_SESSION['auth']=['user_id'=>0,'company'=>['company_id'=>$company]];$denied=false;try{$service->test('customers',$rows,$mapping);}catch(Throwable){$denied=true;}$check($denied,'Preview requires current effective module permissions');
} finally {if($db->inTransaction())$db->rollBack();$_SESSION['auth']=$oldAuth;}
echo "$checks smart-list import checks passed.\n";
