<?php
declare(strict_types=1);
require_once __DIR__.'/../app/helpers/bootstrap.php';
require_once __DIR__.'/support/licensed-import-fixture.php';
use App\Services\Lists\DocumentListService;
use App\Services\DataExchange\ExportService;
if(getenv('APP_ENV')!=='testing')throw new RuntimeException('Isolated testing database required.');
set_exception_handler(static function(Throwable $e):void{fwrite(STDERR,$e->getMessage().PHP_EOL.$e->getTraceAsString().PHP_EOL);exit(1);});
$db=db();$checks=0;$oldAuth=$_SESSION['auth']??null;$prefix='DOC'.strtoupper(bin2hex(random_bytes(3)));
$check=static function(bool $ok,string $label)use(&$checks):void{if(!$ok)throw new RuntimeException('FAIL '.$label);++$checks;echo 'PASS '.$label.PHP_EOL;};
$insert=static function(string $table,array $v)use($db):int{$db->prepare('INSERT INTO '.$table.' ('.implode(',',array_keys($v)).') VALUES('.implode(',',array_fill(0,count($v),'?')).')')->execute(array_values($v));return (int)$db->lastInsertId();};
$company=(int)$db->query('SELECT company_id FROM companies WHERE deleted_at IS NULL ORDER BY company_id LIMIT 1')->fetchColumn();
$db->beginTransaction();
try{
    $actor=licensedImportFixture($db,$company,$prefix);$base=['company_id'=>$company];
    $customer=$insert('sales_customers',$base+['customer_number'=>$prefix,'name'=>'Fixture customer']);
    $supplier=$insert('purchase_suppliers',$base+['supplier_code'=>$prefix,'business_name'=>'Fixture supplier','currency'=>'ETB']);
    $order=$insert('sales_orders',$base+['order_number'=>$prefix,'customer_id'=>$customer,'order_date'=>'2026-01-01','due_date'=>'2026-01-31','created_by'=>$actor]);
    $purchase=$insert('purchase_orders',$base+['po_number'=>$prefix,'supplier_id'=>$supplier,'order_date'=>'2026-01-01','currency'=>'ETB','subtotal'=>100,'tax_amount'=>0,'total_amount'=>100]);
    $requisition=$insert('purchase_requisitions',$base+['requisition_number'=>$prefix,'requester_user_id'=>$actor,'requested_date'=>'2026-01-01','justification'=>'Fixture']);
    $claim=$insert('sales_incentive_claims',$base+['dsa_dsp_user_id'=>$actor,'responsible_manager_id'=>$actor,'currency'=>'ETB','proposed_amount'=>1000,'approved_amount'=>1000,'submitted_by'=>$actor,'submitted_at'=>'2026-01-01','status'=>'approved']);
    $bank=$insert('company_bank_accounts',$base+['bank_name'=>'Fixture treasury','account_name'=>'Treasury','account_number'=>bin2hex(random_bytes(8)),'currency'=>'ETB']);
    $settlement=$insert('sales_settlements',$base+['settlement_number'=>$prefix,'bank_account_id'=>$bank,'currency'=>'ETB','expected_amount'=>1000,'created_by'=>$actor]);
    $pricelist=$insert('sales_pricelists',$base+['name'=>$prefix,'currency'=>'ETB']);
    $team=$insert('sales_teams',$base+['name'=>$prefix]);
    $warehouse=$insert('inventory_warehouses',$base+['code'=>$prefix,'name'=>'Fixture warehouse','manager_user_id'=>$actor]);
    $location=$insert('inventory_warehouse_locations',$base+['warehouse_id'=>$warehouse,'code'=>$prefix,'name'=>'Fixture location']);
    $destination=$insert('inventory_warehouse_locations',$base+['warehouse_id'=>$warehouse,'code'=>$prefix.'D','name'=>'Fixture destination']);
    $operation=$insert('inventory_operation_types',$base+['warehouse_id'=>$warehouse,'code'=>$prefix,'name'=>'Delivery','operation_kind'=>'delivery','default_source_location_id'=>$location,'default_destination_location_id'=>$location]);
    $pickingBase=$base+['warehouse_id'=>$warehouse,'source_location_id'=>$location,'destination_location_id'=>$destination,'operation_type_id'=>$operation];
    $delivery=$insert('inventory_pickings',$pickingBase+['picking_number'=>$prefix.'BASE','picking_type'=>'delivery']);
    $journal=$insert('finance_journals',$base+['journal_code'=>$prefix,'journal_name'=>'Fixture','journal_type'=>'general']);
    $invoiceBase=$base+['journal_id'=>$journal,'invoice_date'=>'2026-01-01','due_date'=>'2026-01-31','currency'=>'ETB','total_amount'=>100,'residual_amount'=>100];
    $invoice=$insert('finance_invoices',$invoiceBase+['invoice_number'=>$prefix.'BASE','document_type'=>'customer_invoice','customer_id'=>$customer]);
    for($i=1;$i<=105;++$i){
        $ref=$prefix.sprintf('%03d',$i);
        $insert('sales_incentive_settlements',$base+['incentive_claim_id'=>$claim,'settlement_date'=>'2026-01-01','amount'=>1,'currency'=>'ETB','external_payment_reference'=>$ref,'evidence_reference'=>$ref,'idempotency_key'=>$ref,'entered_by'=>$actor,'created_at'=>'2026-01-01']);
        $insert('sales_incentive_events',$base+['incentive_claim_id'=>$claim,'event_type'=>'approved','to_status'=>'approved','actor_id'=>$actor,'reason_reference'=>$ref,'occurred_at'=>'2026-01-01']);
        $insert('bank_confirmations',$base+['settlement_id'=>$settlement,'bank_reference'=>$ref,'transaction_date'=>'2026-01-01','confirmed_amount'=>1,'currency'=>'ETB','evidence_path'=>'PRIVATE-DONT-EXPORT','evidence_original_name'=>'receipt.pdf','evidence_mime'=>'application/pdf','evidence_size'=>1,'evidence_sha256'=>hash('sha256',$ref),'created_by'=>$actor]);
        $insert('sales_settlement_events',$base+['settlement_id'=>$settlement,'action'=>'created','to_status'=>'draft','reason'=>$ref,'actor_id'=>$actor]);
        $insert('sales_pricelist_rules',$base+['pricelist_id'=>$pricelist,'category'=>$ref,'calculation'=>'fixed','fixed_price'=>1,'minimum_quantity'=>1,'priority'=>$i,'active'=>$i===105?0:1]);
        $insert('inventory_pickings',$pickingBase+['original_picking_id'=>$delivery,'sales_order_id'=>$order,'picking_number'=>$ref,'picking_type'=>'customer_return']);
        $insert('finance_invoices',$invoiceBase+['invoice_number'=>$ref.'C','document_type'=>'customer_invoice','customer_id'=>$customer,'sales_order_id'=>$order]);
        $insert('sales_order_revisions',$base+['order_id'=>$order,'revision_number'=>$i,'source_event'=>'resubmit','previous_status'=>'rejected','reason'=>$ref,'header_snapshot_json'=>'{}','actor_id'=>$actor,'created_at'=>'2026-01-01']);
        $insert('purchase_requisition_status_history',$base+['requisition_id'=>$requisition,'from_status'=>'draft','to_status'=>'submitted','action'=>'submit','reason'=>$ref,'actor_id'=>$actor]);
        $insert('company_bank_accounts',$base+['bank_name'=>$ref,'account_name'=>$ref,'account_number'=>$ref,'currency'=>'ETB']);
        $agent=$insert('sales_agents',$base+['agent_code'=>$ref,'name'=>$ref,'agent_type'=>'DSA']);
        $insert('sales_team_members',$base+['team_id'=>$team,'agent_id'=>$agent,'joined_at'=>'2026-01-01']);
        $payment=$insert('finance_payments',$base+['journal_id'=>$journal,'payment_number'=>$ref,'customer_id'=>$customer,'direction'=>'inbound','payment_date'=>'2026-01-01','currency'=>'ETB','amount'=>1,'allocated_amount'=>1,'unallocated_amount'=>0,'method'=>'cash']);
        $insert('finance_payment_allocations',$base+['payment_id'=>$payment,'invoice_id'=>$invoice,'amount'=>1,'allocated_at'=>'2026-01-01']);
        $insert('inventory_goods_receipts',$base+['warehouse_id'=>$warehouse,'operation_type_id'=>$operation,'receipt_number'=>$ref,'receipt_date'=>'2026-01-01','purchase_order_id'=>$purchase]);
        $insert('finance_invoices',$invoiceBase+['invoice_number'=>$ref.'V','document_type'=>'vendor_bill','vendor_id'=>$supplier,'purchase_order_id'=>$purchase]);
        $insert('procurement_vendor_returns',$base+['purchase_order_id'=>$purchase,'supplier_id'=>$supplier,'warehouse_id'=>$warehouse,'return_number'=>$ref,'return_date'=>'2026-01-01','reason'=>$ref,'idempotency_key'=>$ref,'posted_at'=>'2026-01-01']);
    }
    $factory=new DocumentListService();$entities=['incentive-settlements'=>$claim,'incentive-events'=>$claim,'settlement-confirmations'=>$settlement,'settlement-events'=>$settlement,'pricing-rules'=>$pricelist,'delivery-returns'=>$delivery,'order-pickings'=>$order,'order-invoices'=>$order,'order-revisions'=>$order,'requisition-history'=>$requisition,'bank-accounts'=>0,'team-members'=>$team,'invoice-payments'=>$invoice,'purchase-receipts'=>$purchase,'purchase-bills'=>$purchase,'purchase-returns'=>$purchase];
    foreach($entities as $entity=>$parent){
        $namespace=str_replace('-','_',$entity);$input=[$namespace=>['q'=>$prefix]];$list=$factory->listing($entity,$input,$parent);
        $check($list->page()['pagination']['total']===105&&count($list->page()['rows'])===25,"$entity counts the complete scoped result");
        foreach([25,50,100] as $size)$check(count($factory->listing($entity,[$namespace=>['q'=>$prefix,'per_page'=>$size]],$parent)->page()['rows'])===$size,"$entity page size $size");
        $check(count($factory->listing($entity,[$namespace=>['q'=>$prefix,'per_page'=>100,'page'=>2]],$parent)->page()['rows'])===5,"$entity second page");
        $check(count($factory->listing($entity,[$namespace=>['q'=>$prefix.'105']],$parent)->export())===1,"$entity finds a record beyond page one");
        $check($factory->listing($entity,[$namespace=>['q'=>'not-a-document-fixture']],$parent)->export()===[],"$entity preserves zero matches");
        foreach(['csv','xlsx'] as $format){$file=(new ExportService())->register($entity,$format,$factory->columns($entity),$list->export());$check(count($list->export())===105&&strlen($file['contents'])>1000&&!str_contains($file['contents'],'PRIVATE-DONT-EXPORT'),"$entity full $format export uses business columns");}
        $controls=$factory->controls($entity,$list);
        if(isset($controls['filters']['status']))$check(count($controls['filters']['status']['options'])>0,"$entity status domain populated");
        $_SESSION['auth']['company']['company_id']=$company+1000000;
        $check($factory->listing($entity,$input,$parent)->export()===[],"$entity cannot read another company");
        $_SESSION['auth']['company']['company_id']=$company;
        if($entity!=='bank-accounts')$check($factory->listing($entity,$input,$parent+1000000)->export()===[],"$entity requires the matching parent");
        $workspace=$factory->workspace([$entity],$input,$parent,'/document',true);
        ob_start();view('components.document-list',['workspace'=>$workspace,'entity'=>$entity,'title'=>'Test']);$html=ob_get_clean();
        $check(str_contains($html,'register='.$entity)&&str_contains($html,'name="'.$namespace.'[q]"'),"$entity renders its own export and filter controls");
    }

    $salesRepository=new App\Repositories\MySql\SalesRepository();
    $full=$salesRepository->orderDetail($company,$order);$paged=$salesRepository->orderDetail($company,$order,false);
    $check($full!==null&&$paged!==null&&$paged['invoices']===[]&&count($full['invoices'])===105&&array_diff_key($full,array_flip(['invoices','pickings','revisions']))===array_diff_key($paged,array_flip(['invoices','pickings','revisions'])),'Order paging preserves complete payment state, quantities and credit eligibility');
    $full=$salesRepository->pricelist($company,$pricelist);$paged=$salesRepository->pricelist($company,$pricelist,false);
    $check(count($full['rules'])===105&&$paged['rules']===[]&&array_diff_key($full,['rules'=>true])===array_diff_key($paged,['rules'=>true]),'Pricelist detail retains its header while rule reads are paged');
    $financeRepository=new App\Repositories\MySql\FinanceRepository();$full=$financeRepository->customerInvoice($company,$invoice);$paged=$financeRepository->customerInvoice($company,$invoice,false);
    $check(count($full['payments'])===105&&$paged['payments']===[]&&array_diff_key($full,['payments'=>true])===array_diff_key($paged,['payments'=>true]),'Invoice paging preserves financial header and complete document lines');
    $db->prepare('UPDATE inventory_pickings SET sales_order_id=? WHERE company_id=? AND picking_id=?')->execute([$order,$company,$delivery]);
    $inventoryRepository=new App\Repositories\MySql\InventoryRepository();$full=$inventoryRepository->deliveryPicking($company,$delivery);$paged=$inventoryRepository->deliveryPicking($company,$delivery,false);
    $check(count($full['returns'])===105&&$paged['returns']===[]&&array_diff_key($full,['returns'=>true])===array_diff_key($paged,['returns'=>true]),'Delivery paging preserves execution quantities and parent document');
    $db->prepare('UPDATE purchase_orders SET warehouse_id=?,destination_location_id=? WHERE company_id=? AND purchase_order_id=?')->execute([$warehouse,$location,$company,$purchase]);
    $procurement=new App\Services\ProcurementService();$full=$procurement->workspace($purchase)['order'];$paged=$procurement->workspace($purchase,true)['order'];
    $check(count($full['receipts'])===105&&$paged['receipts']===[]&&array_diff_key($full,array_flip(['receipts','bills','returns']))===array_diff_key($paged,array_flip(['receipts','bills','returns'])),'Purchase detail preserves authorized header, warehouse and full line quantities');
    $record=(new App\Services\SalesService())->salesTeam($team,$actor);
    $record['related']=$factory->workspace(['team-members'],['team_members'=>['q'=>$prefix.'105']],$team,'/sales/teams/'.$team,true);
    ob_start();view('sales.commercial',['commercialType'=>'team','record'=>$record,'canManage'=>true,'territories'=>[],'agents'=>$record['members']]);$teamHtml=ob_get_clean();
    preg_match('/<select\s+multiple.*?<\/select>/s',$teamHtml,$memberSelect);
    $check(count($record['members'])===105&&count($record['related']['lists']['team-members']['rows'])===1&&substr_count($memberSelect[0]??'','selected')===105,'Team edit form retains all members when the visible table is filtered');
    $quotation=$insert('sales_quotations',$base+['quotation_number'=>$prefix,'customer_id'=>$customer,'quotation_date'=>'2026-01-01','currency'=>'ETB','untaxed_amount'=>0,'tax_amount'=>0,'total_amount'=>0]);
    $quick=$insert('sales_quick_sales',$base+['quotation_id'=>$quotation,'user_id'=>$actor,'agent_id'=>$agent,'team_id'=>$team,'manager_user_id'=>$actor,'origin_manager_user_id'=>$actor,'warehouse_id'=>$warehouse,'origin_warehouse_id'=>$warehouse]);
    for($i=1;$i<=105;++$i)$insert('audit_logs',$base+['user_id'=>$actor,'module'=>'sales','action'=>'quick_sale.submitted','table_name'=>'sales_quick_sales','record_id'=>(string)$quick,'new_values'=>json_encode(['reason'=>$prefix.sprintf('%03d',$i)])]);
    $insert('audit_logs',$base+['user_id'=>$actor,'module'=>'sales','action'=>'quick_sale.finance_handoff','table_name'=>'sales_quick_sales','record_id'=>(string)$quick,'new_values'=>'{}']);
    $list=$factory->listing('quick-sale-events',[],$quick);
    $check($list->page()['pagination']['total']===105&&count($list->page()['rows'])===25&&count($list->export())===105,'Quick Sale owner handoff exclusion occurs before count, page and export');
    $check(count($factory->listing('quick-sale-events',['quick_sale_events'=>['q'=>$prefix.'105']],$quick)->export())===1,'Quick Sale activity finds a late history reason');
    $options=$factory->controls('quick-sale-events',$list)['filters']['action']['options'];$check(!isset($options['quick_sale.finance_handoff']),'Quick Sale action options preserve owner restrictions');
    $_SESSION['auth']['company']['company_id']=$company+1000000;$check($factory->listing('quick-sale-events',[],$quick)->export()===[],'Quick Sale history company isolation');$_SESSION['auth']['company']['company_id']=$company;
    $detail=(new App\Services\SalesIncentiveService())->detail($claim,$actor,['incentive_settlements'=>['q'=>$prefix.'105']]);
    $check(count($detail['settlements'])===1&&(float)$detail['claim']['settled_amount']===105.0,'Incentive totals include all settlements despite detail filtering');
    $detail=(new App\Services\SettlementService())->find($settlement,['settlement_confirmations'=>['q'=>$prefix.'105']]);
    $check(count($detail['confirmations'])===1&&$detail['related']['lists']['settlement-events']['pagination']['total']===105,'Settlement child filters remain independent');
    $check(count($factory->controls('pricing-rules',$factory->listing('pricing-rules',[],$pricelist))['filters']['category']['options'])===105,'Rule category choices cover all pages');
    $columns=['account_number'=>'Account','amount'=>'Amount','transaction_date'=>'Date','created_at'=>'Created'];
    $xlsx=(new ExportService())->register('typed','xlsx',$columns,[['account_number'=>'001234','amount'=>12.5,'transaction_date'=>'2026-01-02','created_at'=>'2026-01-02 09:30:00']]);
    $path=tempnam(sys_get_temp_dir(),'typed-');file_put_contents($path,$xlsx['contents']);$book=PhpOffice\PhpSpreadsheet\IOFactory::load($path);$sheet=$book->getActiveSheet();
    $check($sheet->getCell('A2')->getValue()==='001234'&&$sheet->getCell('A2')->getDataType()==='s','Register export preserves leading-zero business identifiers');
    $check($sheet->getCell('B2')->getDataType()==='n'&&$sheet->getCell('C2')->getDataType()==='n'&&$sheet->getStyle('D2')->getNumberFormat()->getFormatCode()==='yyyy-mm-dd hh:mm:ss','Register export retains native money, date and timestamp types');
    $book->disconnectWorksheets();unlink($path);
} finally{if($db->inTransaction())$db->rollBack();$_SESSION['auth']=$oldAuth;}
echo "$checks document smart-list checks passed.\n";
