<?php $h=$stockHistory??[];$rows=$h['rows']??[];$details=$h['details']??[];$drill=(string)($_GET['drill']??'');$base=e(appBasePath()).'/inventory/stock-daily-history'; ?>
<div class="module-stack">
<?php if(!empty($error)):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<section class="card"><h2>Stock Daily Movement</h2><p>Completed stock-movement endpoints are expanded into source and destination legs. External Vendors/Customers locations are excluded from internal stock totals. Transfers with zero stored quantity_delta still contribute both legs.</p><?php if(!empty($h['cutover'])):?><p><strong>Reservation cutover:</strong> <?=e($h['cutover']['label'].' · '.$h['cutover']['cutover_at'])?>. Before this cutover, historical Reserved/Available is unavailable—not zero.</p><?php endif;?></section>
<?php if($h!==[]):?><section class="card finance-filter-panel"><h3>Filters</h3><form method="get" action="<?=$base?>" class="finance-filter-form"><label>Business date<input type="date" name="date" value="<?=e($h['date'])?>" required></label><label>Warehouse<select name="warehouse_id" required><?php foreach($h['warehouses'] as $w):?><option value="<?=(int)$w['warehouse_id']?>" <?=(int)$h['warehouseId']===(int)$w['warehouse_id']?'selected':''?>><?=e($w['code'].' — '.$w['name'])?></option><?php endforeach;?></select></label><label>Location<select name="location_id"><option value="">All internal/transit</option><?php foreach($h['locations'] as $l):?><option value="<?=(int)$l['location_id']?>" <?=(int)$h['locationId']===(int)$l['location_id']?'selected':''?>><?=e($l['code'].' — '.$l['name'])?></option><?php endforeach;?></select></label><label>SKU<select name="product_id"><option value="">All products</option><?php foreach($h['products'] as $p):?><option value="<?=(int)$p['product_id']?>" <?=(int)$h['productId']===(int)$p['product_id']?'selected':''?>><?=e($p['sku'].' — '.$p['name'])?></option><?php endforeach;?></select></label><button class="btn btn-primary">Show movement</button></form></section>
<?php $movementLink=static function(array $row,string $category) use($h,$base):string{return $base.'?date='.rawurlencode($h['date']).'&warehouse_id='.(int)$h['warehouseId'].'&location_id='.(int)$h['locationId'].'&product_id='.(int)$row['product_id'].'&drill='.rawurlencode($category).'#movement-details';}; ?>
<section class="card table-card"><h3>Daily balances by SKU</h3><div class="table-responsive"><table class="data-table"><thead><tr><th>SKU</th><th>Beginning On-Hand</th><th>Received</th><th>Transfers In</th><th>Returns In</th><th>Sold / Issued</th><th>Transfers Out</th><th>Returns Out</th><th>Adjustments ±</th><th>Unclassified ±</th><th>Ending On-Hand</th><th>Reserved</th><th>Available</th><th>On-Hand Difference</th><th>Reservation Difference</th></tr></thead><tbody><?php if($rows===[]):?><tr><td colspan="15">No internal stock movement or balance for this filter.</td></tr><?php endif;?><?php foreach($rows as $row):?><tr><td><?=e($row['sku'].' — '.$row['product_name'])?></td><?php foreach(['beginning','received','transfers_in','returns_in','sold_issued','transfers_out','returns_out','adjustments','unclassified'] as $category):?><td><a href="<?=e($movementLink($row,$category))?>"><?=e(number_format((float)$row[$category],3))?></a></td><?php endforeach;?><td><a href="<?=e($movementLink($row,'all'))?>"><?=e(number_format((float)$row['ending'],3))?></a></td><td><?=($h['reservationExact']??false)?e(number_format((float)$row['reserved'],3)):'Unavailable before 088 cutover'?></td><td><?=($h['reservationExact']??false)?e(number_format((float)$row['available'],3)):'Unavailable before 088 cutover'?></td><td><?=isset($row['balance_difference'])?e(number_format((float)$row['balance_difference'],3)):'—'?></td><td><?=isset($row['reservation_difference'])?e(number_format((float)$row['reservation_difference'],3)):'—'?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if(!empty($h['unclassified'])):?><div class="notice error">Unclassified movement legs exist. They are included in Ending On-Hand but not silently assigned to a business category. Review the movement details below.</div><?php endif;?>
<section class="card table-card" id="movement-details"><h3>Authoritative movement legs<?=e($drill!==''?' · '.str_replace('_',' ',$drill):'')?></h3><div class="table-responsive"><table class="data-table"><thead><tr><th>When</th><th>Movement</th><th>SKU</th><th>Location</th><th>Category</th><th>Signed qty</th><th>Source type</th><th>Reference</th></tr></thead><tbody><?php $shown=0;foreach($details as $detail):if($drill!==''&&$drill!=='all'&&$detail['category']!==$drill)continue;$shown++;?><tr><td><?=e($detail['business_at'])?></td><td>#<?=(int)$detail['movement_id']?></td><td><?=e($detail['product_id'])?></td><td><?=e($detail['location_id'])?></td><td><?=e(str_replace('_',' ',$detail['category']))?></td><td><?=e(number_format((float)$detail['quantity_delta'],3))?></td><td><?=e($detail['movement_type'])?></td><td><?=e($detail['reference_type'].' · '.($detail['reference_number']??$detail['reference_id']??'—'))?></td></tr><?php endforeach;if($shown===0):?><tr><td colspan="8">No contributing movement legs.</td></tr><?php endif;?></tbody></table></div></section>
<?php endif;?></div>
