<?php
declare(strict_types=1);
namespace App\Services\Lists;
use PDO;

/** Shared projections; business mutations continue to use AssetRepository. */
final class AssetListSql
{
    public static function register(): string { return "SELECT a.*,c.category_code,c.category_name,d.name department_name,CONCAT(e.first_name,' ',e.last_name) custodian_name,(SELECT COUNT(*) FROM asset_depreciation_schedule s WHERE s.company_id=a.company_id AND s.asset_id=a.asset_id) depreciation_count,(SELECT COUNT(*) FROM asset_depreciation_schedule s WHERE s.company_id=a.company_id AND s.asset_id=a.asset_id AND s.status='posted') posted_depreciation_count,(SELECT COUNT(*) FROM asset_transfers t WHERE t.company_id=a.company_id AND t.asset_id=a.asset_id) transfer_count,(SELECT COUNT(*) FROM asset_maintenance_records m WHERE m.company_id=a.company_id AND m.asset_id=a.asset_id) maintenance_count FROM fixed_assets a INNER JOIN asset_categories c ON c.company_id=a.company_id AND c.asset_category_id=a.asset_category_id LEFT JOIN hr_departments d ON d.company_id=a.company_id AND d.department_id=a.department_id LEFT JOIN hr_employees e ON e.company_id=a.company_id AND e.employee_id=a.custodian_employee_id WHERE a.company_id=:company_id"; }
    public static function header(): string { return "SELECT a.*,c.category_name,c.asset_account_id,c.accumulated_depreciation_account_id,c.depreciation_expense_account_id,c.disposal_gain_account_id,c.disposal_loss_account_id,d.name department_name,CONCAT(e.first_name,' ',e.last_name) custodian_name,p.sku source_product_sku,p.name source_product_name,w.name source_warehouse_name,l.name source_location_name,m.reference_type source_reference_type,m.reference_id source_reference_id,m.reference_number source_reference_number FROM fixed_assets a INNER JOIN asset_categories c ON c.company_id=a.company_id AND c.asset_category_id=a.asset_category_id LEFT JOIN hr_departments d ON d.company_id=a.company_id AND d.department_id=a.department_id LEFT JOIN hr_employees e ON e.company_id=a.company_id AND e.employee_id=a.custodian_employee_id LEFT JOIN sales_products p ON p.company_id=a.company_id AND p.product_id=a.product_id LEFT JOIN inventory_warehouses w ON w.company_id=a.company_id AND w.warehouse_id=a.source_warehouse_id LEFT JOIN inventory_warehouse_locations l ON l.company_id=a.company_id AND l.location_id=a.source_location_id LEFT JOIN inventory_stock_movements m ON m.company_id=a.company_id AND m.movement_id=a.source_inventory_movement_id WHERE a.company_id=:company_id AND a.asset_id=:asset_id"; }
    public static function options(PDO $c,int $companyId,bool $scopeStock=false): array
    {
        $categories=$c->prepare('SELECT * FROM asset_categories WHERE company_id=:company_id ORDER BY category_name');$categories->execute(['company_id'=>$companyId]);
        $accounts=$c->prepare("SELECT account_id,account_code,account_name,account_type,normal_balance FROM finance_accounts WHERE company_id=:company_id AND active=TRUE AND deleted_at IS NULL ORDER BY account_code");$accounts->execute(['company_id'=>$companyId]);
        $departments=$c->prepare('SELECT department_id,name FROM hr_departments WHERE company_id=:company_id AND active=TRUE AND deleted_at IS NULL ORDER BY name');$departments->execute(['company_id'=>$companyId]);
        $employees=$c->prepare("SELECT employee_id,CONCAT(first_name,' ',last_name) name FROM hr_employees WHERE company_id=:company_id AND employment_status='active' AND deleted_at IS NULL ORDER BY first_name,last_name");$employees->execute(['company_id'=>$companyId]);
        $stockScope=$scopeStock?(new \App\Services\InventoryReadScope())->predicate($companyId,(int)($_SESSION['auth']['user_id']??0),'b.warehouse_id'):'1=1';
        $stock=$c->prepare("SELECT b.warehouse_id,b.location_id,b.product_id,b.quantity_on_hand-b.quantity_reserved available,b.average_unit_cost,w.name warehouse_name,l.name location_name,p.sku,p.name product_name,p.serial_tracking FROM inventory_stock_balances b INNER JOIN inventory_warehouses w ON w.company_id=b.company_id AND w.warehouse_id=b.warehouse_id INNER JOIN inventory_warehouse_locations l ON l.company_id=b.company_id AND l.location_id=b.location_id AND l.location_usage='internal' INNER JOIN sales_products p ON p.company_id=b.company_id AND p.product_id=b.product_id WHERE b.company_id=:company_id AND b.quantity_on_hand-b.quantity_reserved>0 AND ($stockScope) ORDER BY p.name,w.name,l.name");$stock->execute(['company_id'=>$companyId]);
        return ['categories'=>$categories->fetchAll(PDO::FETCH_ASSOC),'accounts'=>$accounts->fetchAll(PDO::FETCH_ASSOC),'departments'=>$departments->fetchAll(PDO::FETCH_ASSOC),'employees'=>$employees->fetchAll(PDO::FETCH_ASSOC),'stock'=>$stock->fetchAll(PDO::FETCH_ASSOC)];
    }
}
