<?php
declare(strict_types=1);
$data=is_array($data??null)?$data:[];$permissions=$_SESSION['auth']['permissions']??[];$can=static fn(string $p):bool=>in_array($p,$permissions,true);$base=appBasePath();
?>
<?php if(!empty($data['notice'])):?><div class="alert alert-success"><?=e((string)$data['notice'])?></div><?php endif;?>
<?php if(!empty($data['error'])):?><div class="alert alert-danger"><?=e((string)$data['error'])?></div><?php endif;?>
<?php if($can('finance.period.manage')):?><div class="dashboard-grid">
<section class="card"><h2>Create fiscal year</h2><form method="post" action="<?=e($base)?>/finance/fiscal-years"><?=csrfField()?><label>Name<input name="fiscal_year_name" required maxlength="80"></label><label>From<input type="date" name="date_from" required></label><label>To<input type="date" name="date_to" required></label><button class="btn btn-primary">Create fiscal year</button></form></section>
<section class="card"><h2>Open accounting period</h2><form method="post" action="<?=e($base)?>/finance/accounting-periods"><?=csrfField()?><label>Fiscal year<select name="fiscal_year_id" required><option value="">Select</option><?php foreach($data['years']??[] as $year):?><option value="<?=e($year['fiscal_year_id'])?>"><?=e($year['fiscal_year_name'])?></option><?php endforeach;?></select></label><label>Name<input name="period_name" required maxlength="80"></label><label>From<input type="date" name="date_from" required></label><label>To<input type="date" name="date_to" required></label><button class="btn btn-primary">Open period</button></form></section>
</div><?php endif;?>
<section class="card table-card"><h2>Accounting periods</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>Period</th><th>Fiscal year</th><th>Dates</th><th>Status</th><th>Controlled action</th></tr></thead><tbody><?php foreach($data['periods']??[] as $period):?><tr><td><?=e($period['period_name'])?></td><td><?=e($period['fiscal_year_name']??'Legacy')?></td><td><?=e($period['date_from'].' – '.$period['date_to'])?></td><td><?=e(ucfirst($period['status']))?></td><td><?php if($period['status']==='open'&&$can('finance.period.close')):?><form method="post" action="<?=e($base)?>/finance/accounting-periods/<?=e($period['period_id'])?>/transition"><?=csrfField()?><button class="btn btn-secondary" name="action" value="close">Close</button></form><?php elseif($period['status']==='closed'):?><?php if($can('finance.period.close')):?><form method="post" action="<?=e($base)?>/finance/accounting-periods/<?=e($period['period_id'])?>/transition"><?=csrfField()?><button class="btn btn-secondary" name="action" value="lock">Lock</button></form><?php endif;?><?php if($can('finance.period.reopen')):?><form method="post" action="<?=e($base)?>/finance/accounting-periods/<?=e($period['period_id'])?>/transition"><?=csrfField()?><input name="reason" minlength="3" maxlength="500" placeholder="Required reopening reason" required><button class="btn btn-secondary" name="action" value="reopen">Reopen</button></form><?php endif;?><?php else:?>Locked<?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card table-card"><h2>Lifecycle audit history</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>When</th><th>Period</th><th>Action</th><th>Change</th><th>Reason</th></tr></thead><tbody><?php foreach($data['history']??[] as $row):?><tr><td><?=e($row['acted_at'])?></td><td><?=e($row['period_name'])?></td><td><?=e($row['action'])?></td><td><?=e(($row['status_from']??'—').' → '.$row['status_to'])?></td><td><?=e($row['reason']??'—')?></td></tr><?php endforeach;?></tbody></table></div></section>
