<?php
declare(strict_types=1);
$d=$data['bankData']??[];$user=$data['user']??[];$permissions=$user['permissions']??[];$can=static fn(string $p):bool=>in_array('finance.bank_reconciliation.'.$p,$permissions,true);$token=csrfToken();$base=appBasePath().'/finance/bank-reconciliation';
?>
<section class="card finance-register">
<p>Bank reconciliation covers the whole statement against posted entries in one dedicated GL bank account. Sales Settlement Reconciliation remains separate.</p>
<?php if(!empty($data['notice'])): ?><p class="finance-notice"><?= e(is_array($data['notice'])?($data['notice']['message']??'Saved.'):(string)$data['notice']) ?></p><?php endif; ?>
<?php if(!empty($data['error'])): ?><p class="finance-warning"><?= e((string)$data['error']) ?></p><?php endif; ?>
<p><a class="btn btn-secondary" href="<?= e(appBasePath().'/finance/accounting/cash-bank') ?>">Cash &amp; Bank activity</a> <a class="btn btn-secondary" href="<?= e(appBasePath().'/finance/settlements') ?>">Sales Settlement Reconciliation</a></p>
<h2>Bank accounts / GL mappings</h2>
<div class="table-responsive"><table class="data-table"><thead><tr><th>Bank</th><th>GL account</th><th>Currency</th><th>Effective</th><th>Opening posted GL</th><th>Status</th><th>Approver</th><th>Action</th></tr></thead><tbody>
<?php foreach($d['mappings']??[] as $m): ?><tr><td><?= e($m['bank_name'].' · '.$m['bank_account_name'].' · '.$m['account_number']) ?></td><td><?= e($m['account_code'].' · '.$m['account_name']) ?></td><td><?= e($m['currency']) ?></td><td><?= e($m['effective_from']) ?></td><td><?= e(number_format((float)$m['opening_gl_balance'],2)) ?></td><td><span class="finance-status finance-status-<?= e($m['status']) ?>"><?= e($m['status']) ?></span></td><td><?= e((string)($m['approver_name']??'—')) ?></td><td><?php if($m['status']==='draft'&&$can('mapping')): ?><form method="post" action="<?= e($base.'/mappings/'.(int)$m['mapping_id'].'/approve') ?>"><input type="hidden" name="_token" value="<?= e($token) ?>"><button class="btn btn-primary" type="submit">Approve mapping</button></form><?php endif; ?></td></tr><?php endforeach; ?>
<?php if(empty($d['mappings'])): ?><tr><td colspan="8">No mapping approved. Shared cash accounts are not inferred.</td></tr><?php endif; ?></tbody></table></div>
<?php if($can('mapping')): ?><h3>Propose dedicated bank GL mapping</h3><form class="finance-filter-bar" method="post" action="<?= e($base.'/mappings') ?>"><input type="hidden" name="_token" value="<?= e($token) ?>"><label>Company bank account<select name="bank_account_id" required><option value="">Choose bank</option><?php foreach($d['banks']??[] as $b): if(!(bool)$b['active'])continue; ?><option value="<?= (int)$b['bank_account_id'] ?>"><?= e($b['bank_name'].' · '.$b['account_number'].' · '.$b['currency']) ?></option><?php endforeach; ?></select></label><label>Dedicated asset GL<select name="finance_account_id" required><option value="">Choose GL</option><?php foreach($d['accounts']??[] as $a): ?><option value="<?= (int)$a['account_id'] ?>"><?= e($a['account_code'].' · '.$a['account_name'].' · '.$a['currency']) ?></option><?php endforeach; ?></select></label><label>Effective from<input type="date" name="effective_from" required></label><label>Actual posted GL balance before cutover<input type="number" step="0.01" name="opening_gl_balance" required></label><label>Cutover decision / reason<input name="cutover_reason" maxlength="1000" required></label><button class="btn btn-primary" type="submit">Create mapping draft</button></form><?php endif; ?>
</section>
<section class="card finance-register"><h2>Bank statements &amp; reconciliation register</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>Bank</th><th>Mapped GL</th><th>Reference</th><th>Period</th><th>Opening</th><th>Ending</th><th>Currency</th><th>Preparer / reviewer</th><th>Reconciliation</th></tr></thead><tbody><?php foreach($d['statements']??[] as $s): ?><tr><td><?= e($s['bank_name'].' · '.$s['bank_account_name'].' · '.$s['account_number']) ?></td><td><?= e($s['account_code'].' · '.$s['gl_account_name']) ?></td><td><?= e($s['statement_reference']) ?></td><td><?= e($s['period_start'].' – '.$s['period_end']) ?></td><td><?= e(number_format((float)$s['opening_balance'],2)) ?></td><td><?= e(number_format((float)$s['ending_balance'],2)) ?></td><td><?= e($s['currency']) ?></td><td><?= e(($s['preparer_name']??'—').' / '.($s['reviewer_name']??'—')) ?></td><td><?php if(!empty($s['reconciliation_id'])): ?><a class="btn btn-secondary btn-compact" href="<?= e($base.'/'.(int)$s['reconciliation_id']) ?>"><?= e($s['reconciliation_status']) ?> →</a><?php endif; ?></td></tr><?php endforeach; ?><?php if(empty($d['statements'])): ?><tr><td colspan="9">No statements entered.</td></tr><?php endif; ?></tbody></table></div>
<?php if($can('prepare')): ?><h3>Start manual statement</h3><form class="finance-filter-bar" method="post" action="<?= e($base.'/statements') ?>"><input type="hidden" name="_token" value="<?= e($token) ?>"><label>Approved mapping<select name="mapping_id" required><option value="">Choose mapping</option><?php foreach($d['mappings']??[] as $m): if($m['status']!=='approved'||$m['effective_to']!==null)continue; ?><option value="<?= (int)$m['mapping_id'] ?>"><?= e($m['bank_name'].' · '.$m['account_code'].' · '.$m['currency']) ?></option><?php endforeach; ?></select></label><label>Statement reference<input name="statement_reference" maxlength="190" required></label><label>Period start<input type="date" name="period_start" required></label><label>Period end<input type="date" name="period_end" required></label><label>Statement date<input type="date" name="statement_date" required></label><label>Opening balance<input type="number" step="0.01" name="opening_balance" required></label><label>Ending balance<input type="number" step="0.01" name="ending_balance" required></label><button class="btn btn-primary" type="submit">Create statement</button></form><?php endif; ?>
</section>
