<?php
declare(strict_types=1);
$loanData=$data['loanData']??[];$permissions=$data['user']['permissions']??[];$manage=in_array('finance.records.manage',$permissions,true);$summaries=$loanData['summary']??[];$token=csrfToken();
?>
<?php if(!empty($data['loanError'])): ?><p class="alert alert-danger"><?= e($data['loanError']) ?></p><?php endif; ?>
<?php if(!empty($data['notice'])): ?><p class="alert alert-success"><?= e($data['notice']) ?></p><?php endif; ?>
<section class="card"><h2>Loan summary</h2><?php foreach($summaries as $summary): ?><p><?= e($summary['currency']) ?> · Active loans: <?= (int)$summary['active_loans'] ?> · Outstanding principal: <?= e(number_format((float)$summary['outstanding_principal'],2)) ?> · Due this month: <?= e(number_format((float)$summary['due_this_month'],2)) ?> · Overdue: <?= e(number_format((float)$summary['overdue_amount'],2)) ?></p><?php endforeach; ?><?php if(!$summaries): ?><p>No active loans.</p><?php endif; ?></section>
<?php if($manage): ?><details class="card finance-composer"><summary>New loan or advance</summary><form method="post" action="<?= e(appBasePath().'/finance/staff-loans') ?>" class="form-grid"><input type="hidden" name="_token" value="<?= e($token) ?>">
<label>Employee <select name="employee_id" required><option value="">Select</option><?php foreach(($loanData['employees']??[]) as $employee): ?><option value="<?= (int)$employee['employee_id'] ?>"><?= e($employee['employee_number'].' '.$employee['first_name'].' '.$employee['last_name']) ?></option><?php endforeach; ?></select></label>
<label>Type <select name="loan_type"><option value="loan">Loan</option><option value="advance">Advance</option></select></label>
<label>Purpose <input name="purpose" maxlength="500" required></label><label>Currency <input name="currency" maxlength="3" value="ETB" required></label>
<label>Principal <input type="number" name="principal_amount" step="0.01" min="0.01" required></label><label>Annual simple interest rate % <input type="number" name="interest_rate" step="0.0001" min="0" max="100" value="0"></label>
<label>Request date <input type="date" name="request_date" value="<?= e(date('Y-m-d')) ?>" required></label><label>Frequency <select name="installment_frequency"><option value="monthly">Monthly</option><option value="weekly">Weekly</option></select></label>
<label>Installments <input type="number" name="installment_count" min="1" max="360" required></label><label>First due <input type="date" name="first_due_date" required></label><button type="submit">Save draft</button></form></details><?php endif; ?>
<section class="card"><h2>Loan register</h2><p><?php foreach([''=>'All','active'=>'Active','paid'=>'Paid','overdue'=>'Overdue'] as $value=>$label): ?><a href="<?= e(appBasePath().'/finance/staff-loans'.($value!==''?'?status='.$value:'')) ?>"><?= e($label) ?></a> &nbsp; <?php endforeach; ?></p><div class="table-responsive"><table class="data-table"><thead><tr><th>Number</th><th>Employee</th><th>Type</th><th>Status</th><th>Principal</th><th>Paid</th><th>Outstanding principal</th><th>Interest remaining</th><th>Next due</th><th>Installments left</th><th>Overdue</th></tr></thead><tbody>
<?php foreach(($loanData['loans']??[]) as $loan): ?><tr><td><a href="<?= e(appBasePath().'/finance/staff-loans/'.(int)$loan['loan_id']) ?>"><?= e($loan['loan_number']) ?></a></td><td><?= e($loan['employee_name']) ?></td><td><?= e($loan['loan_type']) ?></td><td><span class="status"><?= e($loan['status']) ?></span></td><td class="erp-money-column"><?= e($loan['currency'].' '.number_format((float)$loan['principal_amount'],2)) ?></td><td class="erp-money-column"><?= e(number_format((float)$loan['amount_paid'],2)) ?></td><td class="erp-money-column"><?= e(number_format((float)$loan['outstanding_principal'],2)) ?></td><td class="erp-money-column"><?= e(number_format((float)$loan['outstanding_interest'],2)) ?></td><td><?= e($loan['next_due_date']??'') ?></td><td><?= (int)$loan['installments_remaining'] ?></td><td class="erp-money-column"><?= e(number_format((float)$loan['overdue_amount'],2)) ?></td></tr><?php endforeach; ?>
<?php if(empty($loanData['loans'])): ?><tr><td colspan="11">No loans in this view.</td></tr><?php endif; ?></tbody></table></div></section>
