<?php
declare(strict_types=1);
$loan=$data['loan'];$permissions=$data['user']['permissions']??[];$manage=in_array('finance.records.manage',$permissions,true);$approve=in_array('finance.requests.approve',$permissions,true);$actor=(int)($data['user']['user_id']??0);$token=csrfToken();$path=appBasePath().'/finance/staff-loans/'.(int)$loan['loan_id'];
?>
<?php if(!empty($data['loanError'])): ?><p class="alert alert-danger"><?= e($data['loanError']) ?></p><?php endif; ?>
<?php if(!empty($data['notice'])): ?><p class="alert alert-success"><?= e($data['notice']) ?></p><?php endif; ?>
<p><a href="<?= e(appBasePath().'/finance/staff-loans') ?>">← Loan register</a></p>
<section class="card"><h2><?= e($loan['loan_number'].' — '.$loan['employee_name']) ?></h2><p><?= e($loan['loan_type'].' · '.$loan['purpose'].' · '.$loan['status']) ?></p><p>Principal: <?= e($loan['currency'].' '.number_format((float)$loan['principal_amount'],2)) ?> · Total paid: <?= e(number_format((float)$loan['amount_paid'],2)) ?> · Outstanding principal: <?= e(number_format((float)$loan['outstanding_principal'],2)) ?> · Outstanding interest: <?= e(number_format((float)$loan['outstanding_interest'],2)) ?></p><p>Installments remaining: <?= (int)$loan['installments_remaining'] ?> · Next due: <?= e($loan['next_due_date']??'None') ?> · Next amount: <?= e(number_format((float)$loan['next_installment_amount'],2)) ?> · Expected finish: <?= e($loan['planned_completion_date']??'Pending approval') ?> · Overdue: <?= e(number_format((float)$loan['overdue_amount'],2)) ?> (<?= (int)$loan['days_overdue'] ?> days)</p></section>
<?php if($manage&&(int)$loan['created_by']===$actor&&$loan['status']==='draft'): foreach(['submit'=>'Submit','cancel'=>'Cancel'] as $action=>$label): ?><form method="post" action="<?= e($path.'/'.$action) ?>"><input type="hidden" name="_token" value="<?= e($token) ?>"><button type="submit"><?= e($label) ?></button></form><?php endforeach; endif; ?>
<?php if($approve&&(int)$loan['created_by']!==$actor&&$loan['status']==='submitted'): ?><form method="post" action="<?= e($path.'/review') ?>"><input type="hidden" name="_token" value="<?= e($token) ?>"><button name="action" value="approve">Approve and generate schedule</button><input name="reason" placeholder="Rejection reason"><button name="action" value="reject">Reject</button></form><?php endif; ?>
<?php if($manage&&$loan['status']==='approved'): ?><section class="card"><h2>Disburse</h2><form method="post" action="<?= e($path.'/disburse') ?>"><input type="hidden" name="_token" value="<?= e($token) ?>"><input type="date" name="disbursement_date" value="<?= e(date('Y-m-d')) ?>" required><select name="journal_id" required><option value="">Cash / bank journal</option><?php foreach($loan['journals'] as $journal): ?><option value="<?= (int)$journal['journal_id'] ?>"><?= e($journal['journal_name']) ?></option><?php endforeach; ?></select><button type="submit">Disburse and post</button></form></section><?php endif; ?>
<?php if($manage&&in_array($loan['status'],['disbursed','active'],true)): ?><section class="card"><h2>Record repayment</h2><form method="post" action="<?= e($path.'/repay') ?>"><input type="hidden" name="_token" value="<?= e($token) ?>"><input type="hidden" name="idempotency_key" value="<?= e(bin2hex(random_bytes(16))) ?>"><input type="date" name="payment_date" value="<?= e(date('Y-m-d')) ?>" required><input type="number" name="amount" min="0.01" step="0.01" required placeholder="Amount"><select name="journal_id" required><option value="">Cash / bank journal</option><?php foreach($loan['journals'] as $journal): ?><option value="<?= (int)$journal['journal_id'] ?>"><?= e($journal['journal_name']) ?></option><?php endforeach; ?></select><input name="reference_number" maxlength="120" placeholder="Reference"><button type="submit">Allocate and post</button></form></section><?php endif; ?>
<section class="card"><h2>Installment schedule</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>No.</th><th>Due</th><th>Opening</th><th>Principal</th><th>Interest</th><th>Total</th><th>Paid</th><th>Remaining</th><th>Status</th></tr></thead><tbody><?php foreach($loan['installments'] as $i): $displayStatus=(float)$i['remaining_due']<=0?'paid':(!in_array($loan['status'],['disbursed','active'],true)?'upcoming':((float)$i['amount_paid']>0?'partially_paid':($i['due_date']<date('Y-m-d')?'overdue':($i['due_date']===date('Y-m-d')?'due':'upcoming')))); ?><tr><td><?= (int)$i['installment_number'] ?></td><td><?= e($i['due_date']) ?></td><td class="erp-money-column"><?= e(number_format((float)$i['opening_balance'],2)) ?></td><td class="erp-money-column"><?= e(number_format((float)$i['principal_due'],2)) ?></td><td class="erp-money-column"><?= e(number_format((float)$i['interest_due'],2)) ?></td><td class="erp-money-column"><?= e(number_format((float)$i['total_due'],2)) ?></td><td class="erp-money-column"><?= e(number_format((float)$i['amount_paid'],2)) ?></td><td class="erp-money-column"><?= e(number_format((float)$i['remaining_due'],2)) ?></td><td><span class="status"><?= e(str_replace('_',' ', $displayStatus)) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="card"><h2>Repayment history</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>Date</th><th>Number</th><th>Reference</th><th>Principal</th><th>Interest</th><th>Total</th><th>Journal</th></tr></thead><tbody><?php foreach($loan['payments'] as $p): ?><tr><td><?= e($p['payment_date']) ?></td><td><?= e($p['payment_number']) ?></td><td><?= e($p['reference_number']??'') ?></td><td><?= e(number_format((float)$p['principal_amount'],2)) ?></td><td><?= e(number_format((float)$p['interest_amount'],2)) ?></td><td><?= e(number_format((float)$p['amount'],2)) ?></td><td><?= e($p['batch_number']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="card"><h2>Audit history</h2><?php foreach($loan['history'] as $event): ?><p><?= e($event['occurred_at'].' · '.$event['action'].' · user #'.$event['actor_id'].($event['reason']?' · '.$event['reason']:'')) ?></p><?php endforeach; ?></section>
