<?php
declare(strict_types=1);
header('Content-Type: application/json');
if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { http_response_code(404); exit; }
const LIVE_ROOT='/home/passiontech/office_app'; const STAGING_ROOT='/home/passiontech/deployment-staging'; const DEPLOY_LOCK='/home/passiontech/.officeapp-deployment.lock';
function fail(int $s,string $e,string $m=''):never{http_response_code($s);echo json_encode(['ok'=>false,'error'=>$e,'message'=>$m]);exit;}
function releaseId(mixed $v):string{$id=is_string($v)?$v:'';if(preg_match('/^[a-f0-9]{7}-[0-9]{14}$/D',$id)!==1)fail(400,'invalid_release_id');return $id;}
function releaseDir(string $id):string{return STAGING_ROOT.'/'.$id;}
function removeTree(string $p):void{if(is_link($p)||is_file($p)){if(!unlink($p))throw new RuntimeException('Unable to remove file.');return;}if(!is_dir($p))return;foreach(new FilesystemIterator($p)as$i)removeTree($i->getPathname());if(!rmdir($p))throw new RuntimeException('Unable to remove directory.');}
function copyTree(string $s,string $d):void{$real=realpath($s);if($real===false||(!str_starts_with($real.'/',LIVE_ROOT.'/')&&$real!==LIVE_ROOT))throw new RuntimeException('Invalid copy source.');if(!is_dir($d)&&!mkdir($d,0700,true))throw new RuntimeException('Unable to create copy destination.');foreach(new FilesystemIterator($real)as$i){if($i->isLink())throw new RuntimeException('Symlink in protected production data.');$t=$d.'/'.$i->getFilename();if($i->isDir())copyTree($i->getPathname(),$t);elseif(!copy($i->getPathname(),$t))throw new RuntimeException('Protected data copy failed.');}}
function metadata(string $id):array{$p=releaseDir($id).'/.deployment.json';$d=is_file($p)?json_decode((string)file_get_contents($p),true):null;if(!is_array($d)||($d['release_id']??null)!==$id)throw new RuntimeException('Release state unavailable.');return$d;}
function saveMetadata(string $id,array $d):void{$p=releaseDir($id).'/.deployment.json';if(file_put_contents($p,json_encode($d,JSON_THROW_ON_ERROR),LOCK_EX)===false)throw new RuntimeException('Unable to save release state.');chmod($p,0600);}
$headerRoot=(string)($_SERVER['HTTP_X_OFFICEAPP_ROOT']??LIVE_ROOT);if(!preg_match('#^/home/passiontech/(office_app|deployment-staging/[a-f0-9]{7}-[0-9]{14}/office_app)$#D',$headerRoot))fail(403,'invalid_release_root');
$authRoot=realpath($headerRoot)?:'';$configRoot=is_file($authRoot.'/config/app.local.php')?$authRoot:LIVE_ROOT;$local=is_file($configRoot.'/config/app.local.php')?require$configRoot.'/config/app.local.php':[];$secret=is_array($local)?(string)($local['deployment_secret']??''):'';$ips=is_array($local)?(array)($local['deployment_allowed_ips']??[]):[];if(strlen($secret)<32){http_response_code(404);exit;}if($ips!==[]&&!in_array((string)($_SERVER['REMOTE_ADDR']??''),$ips,true))fail(403,'source_ip_denied');
$ts=(string)($_SERVER['HTTP_X_OFFICEAPP_TIMESTAMP']??'');$nonce=(string)($_SERVER['HTTP_X_OFFICEAPP_NONCE']??'');$sig=(string)($_SERVER['HTTP_X_OFFICEAPP_SIGNATURE']??'');$body=(string)file_get_contents('php://input');if(!ctype_digit($ts)||abs(time()-(int)$ts)>300||preg_match('/^[a-f0-9]{32,64}$/D',$nonce)!==1)fail(401,'expired_or_invalid_request');$expected=hash_hmac('sha256',$ts."\n".$nonce."\n".$headerRoot."\n".$body,$secret);if(!hash_equals($expected,$sig))fail(401,'authentication_failed');
$request=json_decode($body,true);$action=is_array($request)?(string)($request['action']??''):'';$actions=['migration-status','preflight','begin-release','upload-chunk','finalize-release','database-backup','application-backup','migrate','sync-reference-data','release-health','cutover','rollback-application','cleanup'];if(!in_array($action,$actions,true))fail(400,'unsupported_action');$readOnly=in_array($action,['migration-status','preflight'],true);
if(!$readOnly){$nd=LIVE_ROOT.'/storage/private/deployment-nonces';if(!is_dir($nd)&&!mkdir($nd,0700,true))fail(503,'nonce_storage_unavailable');$nf=$nd.'/'.$nonce;if(is_file($nf)||file_put_contents($nf,(string)time(),LOCK_EX)===false)fail(409,'replay_detected');chmod($nf,0600);}
try{
 require_once LIVE_ROOT.'/app/helpers/bootstrap.php';$pdo=db();$versions=$pdo->query('SELECT version FROM schema_migrations ORDER BY version')->fetchAll(PDO::FETCH_COLUMN);$current=$versions===[]?null:(string)end($versions);$result=['ok'=>true,'action'=>$action,'migration'=>$current];
 if($action==='migration-status'){$result['versions']=$versions;}
 elseif($action==='preflight'){$checks=['php81'=>PHP_VERSION_ID>=80100,'phar'=>class_exists(PharData::class),'staging_parent'=>is_dir(dirname(STAGING_ROOT))&&is_writable(dirname(STAGING_ROOT)),'live_root'=>is_dir(LIVE_ROOT),'database_config'=>is_readable(LIVE_ROOT.'/config/database.php'),'app_config'=>is_readable(LIVE_ROOT.'/config/app.local.php'),'storage'=>is_dir(LIVE_ROOT.'/storage')&&is_readable(LIVE_ROOT.'/storage'),'proc_open'=>function_exists('proc_open'),'mysqldump'=>is_executable('/usr/bin/mysqldump'),'gzip_extension'=>function_exists('gzopen')];if(in_array(false,$checks,true))throw new RuntimeException('Required deployment capability unavailable.');$result['checks']=$checks;}
 elseif($action==='begin-release'){$id=releaseId($request['release_id']??null);$commit=(string)($request['commit']??'');$size=$request['size']??null;$sha=(string)($request['sha256']??'');if(preg_match('/^[a-f0-9]{40}$/D',$commit)!==1||!is_int($size)||$size<1024||$size>1073741824||preg_match('/^[a-f0-9]{64}$/D',$sha)!==1)fail(400,'invalid_release_metadata');if(is_file(DEPLOY_LOCK))throw new RuntimeException('Deployment lock exists.');if(!is_dir(STAGING_ROOT)&&!mkdir(STAGING_ROOT,0700,true))throw new RuntimeException('Cannot create staging root.');$dir=releaseDir($id);if(file_exists($dir)||!mkdir($dir.'/.upload',0700,true))throw new RuntimeException('Cannot create unique release staging directory.');if(file_put_contents(DEPLOY_LOCK,$id,LOCK_EX)===false)throw new RuntimeException('Cannot create deployment lock.');chmod(DEPLOY_LOCK,0600);saveMetadata($id,['release_id'=>$id,'commit'=>$commit,'size'=>$size,'sha256'=>$sha,'next_chunk'=>0,'uploaded'=>0,'state'=>'uploading']);$result['release_id']=$id;}
 elseif($action==='upload-chunk'){$id=releaseId($request['release_id']??null);$state=metadata($id);$index=$request['index']??null;$encoded=$request['data']??null;if($state['state']!=='uploading'||!is_int($index)||$index!==$state['next_chunk']||!is_string($encoded)||strlen($encoded)>400000)fail(400,'invalid_chunk');$bytes=base64_decode($encoded,true);if($bytes===false||strlen($bytes)<1||strlen($bytes)>262144||$state['uploaded']+strlen($bytes)>$state['size'])fail(400,'invalid_chunk_data');$part=releaseDir($id).'/.upload/package.tar.gz.part';if(file_put_contents($part,$bytes,FILE_APPEND|LOCK_EX)===false)throw new RuntimeException('Chunk write failed.');chmod($part,0600);$state['uploaded']+=strlen($bytes);$state['next_chunk']++;saveMetadata($id,$state);$result+=['next_chunk'=>$state['next_chunk'],'uploaded'=>$state['uploaded']];}
 elseif($action==='finalize-release'){$id=releaseId($request['release_id']??null);$state=metadata($id);$dir=releaseDir($id);$part=$dir.'/.upload/package.tar.gz.part';if($state['state']!=='uploading'||!is_file($part)||filesize($part)!==$state['size']||!hash_equals($state['sha256'],hash_file('sha256',$part)))throw new RuntimeException('Uploaded package verification failed.');$archive=$dir.'/officeapp-cpanel.tar.gz';if(!rename($part,$archive))throw new RuntimeException('Cannot finalize package.');$phar=new PharData($archive);$prefix='phar://'.str_replace('\\','/',$archive).'/';$seen=false;foreach(new RecursiveIteratorIterator($phar)as$key=>$entry){$key=(string)$key;$name=str_replace('\\','/',str_starts_with($key,$prefix)?substr($key,strlen($prefix)):$key);if($name==='office_app'||str_starts_with($name,'office_app/'))$seen=true;else throw new RuntimeException('Archive root invalid.');if(str_contains('/'.$name.'/','/../')||str_starts_with($name,'/')||preg_match('/^[A-Za-z]:/',$name)||$entry->isLink())throw new RuntimeException('Unsafe archive entry.');}if(!$seen||isset($phar['office_app/config/database.php'])||isset($phar['office_app/config/app.local.php']))throw new RuntimeException('Archive structure or exclusions invalid.');$phar->extractTo($dir,null,false);$app=$dir.'/office_app';if(!is_file($app.'/vendor/autoload.php'))throw new RuntimeException('Composer autoload absent.');if(!copy(LIVE_ROOT.'/config/database.php',$app.'/config/database.php')||!copy(LIVE_ROOT.'/config/app.local.php',$app.'/config/app.local.php'))throw new RuntimeException('Protected configuration copy failed.');chmod($app.'/config/database.php',0600);chmod($app.'/config/app.local.php',0600);removeTree($app.'/storage');copyTree(LIVE_ROOT.'/storage',$app.'/storage');$state['state']='staged';saveMetadata($id,$state);$result+=['release_id'=>$id,'staged_root'=>$app,'size'=>filesize($archive),'sha256'=>hash_file('sha256',$archive)];}
 elseif($action==='database-backup'){$id=releaseId($request['release_id']??null);$state=metadata($id);if($state['state']!=='staged')throw new RuntimeException('Release not staged.');$cfg=require LIVE_ROOT.'/config/database.php';$name='production-db-before_'.gmdate('YmdHis').'_'.substr($state['commit'],0,7).'.sql.gz';$path=LIVE_ROOT.'/storage/backups/'.$name;if(!is_dir(dirname($path))&&!mkdir(dirname($path),0700,true))throw new RuntimeException('Backup directory unavailable.');$defaults=tempnam(LIVE_ROOT.'/storage/private','deploy-db-');if($defaults===false)throw new RuntimeException('Cannot create protected database client configuration.');file_put_contents($defaults,"[client]\nhost=".$cfg['host']."\nport=".$cfg['port']."\nuser=".$cfg['username']."\npassword=".$cfg['password']."\n",LOCK_EX);chmod($defaults,0600);$args=['/usr/bin/mysqldump','--defaults-extra-file='.$defaults,'--single-transaction','--routines','--triggers','--events',(string)$cfg['database']];$proc=proc_open($args,[1=>['pipe','w'],2=>['pipe','w']],$pipes,null,null,['bypass_shell'=>true]);if(!is_resource($proc)){unlink($defaults);throw new RuntimeException('Cannot start database backup.');}$gz=gzopen($path,'wb9');if($gz===false){unlink($defaults);throw new RuntimeException('Cannot open backup.');}while(!feof($pipes[1])){$c=fread($pipes[1],262144);if($c!==false&&$c!=='')gzwrite($gz,$c);}gzclose($gz);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($proc);unlink($defaults);clearstatcache(true,$path);if($code!==0||!is_file($path)||filesize($path)<1024)throw new RuntimeException('Database backup failed: '.substr(trim($err),0,300));chmod($path,0600);$state['database_backup']=$name;$state['state']='database-backed-up';saveMetadata($id,$state);$result['backup']=['name'=>$name,'size'=>filesize($path),'sha256'=>hash_file('sha256',$path)];}
 elseif($action==='application-backup'){$id=releaseId($request['release_id']??null);$state=metadata($id);if($state['state']!=='database-backed-up')throw new RuntimeException('Verified database backup required.');$name='office_app_before_'.gmdate('YmdHis').'_'.substr($state['commit'],0,7);$path='/home/passiontech/'.$name;if(file_exists($path))throw new RuntimeException('Application backup exists.');copyTree(LIVE_ROOT,$path);if(!is_file($path.'/vendor/autoload.php')||!is_file($path.'/config/database.php'))throw new RuntimeException('Application backup verification failed.');$state['application_backup']=$name;$state['state']='backed-up';saveMetadata($id,$state);$result['backup']=['name'=>$name,'verified'=>true];}
 elseif($action==='migrate'){$id=releaseId($request['release_id']??null);$state=metadata($id);if($state['state']!=='backed-up')throw new RuntimeException('Verified backups required.');$root=releaseDir($id).'/office_app';require$root.'/vendor/autoload.php';$runner=new App\Database\MigrationRunner($pdo,databaseDriver()->name());$result['result']=$runner->run($root.'/database/migrations/'.databaseDriver()->name());$after=$pdo->query('SELECT version FROM schema_migrations ORDER BY version')->fetchAll(PDO::FETCH_COLUMN);$result['migration']=$after===[]?null:(string)end($after);$state['state']='migrated';saveMetadata($id,$state);}
 elseif($action==='sync-reference-data'){$id=releaseId($request['release_id']??null);$state=metadata($id);if(!in_array($state['state'],['backed-up','migrated'],true))throw new RuntimeException('Backups required.');$root=releaseDir($id).'/office_app';require$root.'/vendor/autoload.php';$sync=new App\Database\ReferenceDataSynchronizer($pdo,databaseDriver()->name());$result['result']=$sync->run($root.'/database/seeds');$state['state']='ready';saveMetadata($id,$state);}
 elseif($action==='release-health'){$root=$headerRoot;$checks=['autoload'=>is_file($root.'/vendor/autoload.php'),'database'=>true,'protected_config'=>is_file($root.'/config/database.php')&&is_file($root.'/config/app.local.php'),'storage'=>is_dir($root.'/storage')&&is_writable($root.'/storage')];if(in_array(false,$checks,true))throw new RuntimeException('Release health failed.');$result['checks']=$checks;}
 elseif($action==='cutover'){$id=releaseId($request['release_id']??null);$state=metadata($id);if($state['state']!=='ready')throw new RuntimeException('Release not ready.');$failed='/home/passiontech/office_app_failed_'.gmdate('YmdHis').'_'.$id;if(!rename(LIVE_ROOT,$failed))throw new RuntimeException('Cannot move live application.');if(!rename(releaseDir($id).'/office_app',LIVE_ROOT)){rename($failed,LIVE_ROOT);throw new RuntimeException('Cannot activate staged application.');}$state['cutover_previous']=$failed;$state['state']='cutover';saveMetadata($id,$state);$result['previous']=$failed;}
 elseif($action==='rollback-application'){$id=releaseId($request['release_id']??null);$state=metadata($id);$previous=(string)($state['cutover_previous']??'');if($state['state']!=='cutover'||preg_match('#^/home/passiontech/office_app_failed_[0-9]{14}_[a-f0-9]{7}-[0-9]{14}$#D',$previous)!==1||!is_dir($previous))throw new RuntimeException('No validated rollback source.');$bad='/home/passiontech/office_app_failed_health_'.gmdate('YmdHis').'_'.$id;if(!rename(LIVE_ROOT,$bad)||!rename($previous,LIVE_ROOT))throw new RuntimeException('Application rollback failed.');$state['state']='rolled-back';saveMetadata($id,$state);$result['restored']=true;}
 elseif($action==='cleanup'){$id=releaseId($request['release_id']??null);if(is_file(DEPLOY_LOCK)&&trim((string)file_get_contents(DEPLOY_LOCK))===$id){if(!unlink(DEPLOY_LOCK))throw new RuntimeException('Cannot remove deployment lock.');}$result['lock_removed']=!is_file(DEPLOY_LOCK);}
 if(!$readOnly){@file_put_contents(LIVE_ROOT.'/storage/logs/deployment-actions.log',json_encode(['time'=>gmdate(DATE_ATOM),'action'=>$action,'remote'=>$_SERVER['REMOTE_ADDR']??null,'ok'=>true],JSON_UNESCAPED_SLASHES).PHP_EOL,FILE_APPEND|LOCK_EX);}echo json_encode($result,JSON_UNESCAPED_SLASHES);
}catch(Throwable$e){http_response_code(500);error_log('Deployment runner '.$action.' failed: '.$e->getMessage());echo json_encode(['ok'=>false,'action'=>$action,'error'=>'deployment_action_failed','message'=>$e->getMessage()]);}
