<?php
declare(strict_types=1);

/* Temporary deployment-only gateway. Install at an unguessable public-bridge
 * filename for a deployment window, then remove it. It is inert without the
 * production-only deployment_secret in config/app.local.php. */
header('Content-Type: application/json');
if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { http_response_code(404); exit; }
$root=(string)($_SERVER['HTTP_X_OFFICEAPP_ROOT']??'/home/passiontech/office_app');
if(!preg_match('#^/home/passiontech/(office_app|deployment-staging/[a-f0-9]{7,40}-[0-9]{14}/office_app)$#',$root)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'invalid_release_root']);exit;}
$root=realpath($root)?:'';$local=$root!==''&&is_file($root.'/config/app.local.php')?require $root.'/config/app.local.php':[];$secret=is_array($local)?(string)($local['deployment_secret']??''):'';$allowed=is_array($local)?(array)($local['deployment_allowed_ips']??[]):[];
if(strlen($secret)<32){http_response_code(404);exit;}if($allowed!==[]&&!in_array((string)($_SERVER['REMOTE_ADDR']??''),$allowed,true)){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'source_ip_denied']);exit;}
$timestamp=(string)($_SERVER['HTTP_X_OFFICEAPP_TIMESTAMP']??'');$nonce=(string)($_SERVER['HTTP_X_OFFICEAPP_NONCE']??'');$signature=(string)($_SERVER['HTTP_X_OFFICEAPP_SIGNATURE']??'');$body=(string)file_get_contents('php://input');
if(!ctype_digit($timestamp)||abs(time()-(int)$timestamp)>300||!preg_match('/^[a-f0-9]{32,64}$/',$nonce)){http_response_code(401);echo json_encode(['ok'=>false,'error'=>'expired_or_invalid_request']);exit;}
$expected=hash_hmac('sha256',$timestamp."\n".$nonce."\n".$root."\n".$body,$secret);if(!hash_equals($expected,$signature)){http_response_code(401);echo json_encode(['ok'=>false,'error'=>'authentication_failed']);exit;}
$request=json_decode($body,true);$action=is_array($request)?(string)($request['action']??''):'';$allowedActions=['health','migration-status','database-backup','migrate','sync-reference-data','release-health'];if(!in_array($action,$allowedActions,true)){http_response_code(400);echo json_encode(['ok'=>false,'error'=>'unsupported_action']);exit;}
$readOnlyDiscovery=$action==='migration-status';if(!$readOnlyDiscovery){$nonceDir=$root.'/storage/private/deployment-nonces';if(!is_dir($nonceDir)&&!mkdir($nonceDir,0700,true)){http_response_code(503);echo json_encode(['ok'=>false,'error'=>'nonce_storage_unavailable']);exit;}$nonceFile=$nonceDir.'/'.$nonce;if(file_exists($nonceFile)||file_put_contents($nonceFile,(string)time(),LOCK_EX)===false){http_response_code(409);echo json_encode(['ok'=>false,'error'=>'replay_detected']);exit;}chmod($nonceFile,0600);foreach(glob($nonceDir.'/*')?:[] as $old)if(filemtime($old)<time()-86400)@unlink($old);}
try{
 require_once $root.'/app/helpers/bootstrap.php';$pdo=db();$versions=$pdo->query('SELECT version FROM schema_migrations ORDER BY version')->fetchAll(PDO::FETCH_COLUMN);$current=$versions===[]?null:(string)end($versions);
 $result=['ok'=>true,'action'=>$action,'migration'=>$current];
 if($action==='migration-status'){$result['versions']=$versions;}
 elseif($action==='migrate'){if(!empty($request['expected_before'])&&(string)$request['expected_before']!==$current)throw new RuntimeException('Production migration changed since preflight.');$runner=new App\Database\MigrationRunner($pdo,databaseDriver()->name());$result['result']=$runner->run($root.'/database/migrations/'.databaseDriver()->name());$after=$pdo->query('SELECT version FROM schema_migrations ORDER BY version')->fetchAll(PDO::FETCH_COLUMN);$result['versions']=$after;$result['migration']=$after===[]?null:(string)end($after);}
 elseif($action==='sync-reference-data'){$sync=new App\Database\ReferenceDataSynchronizer($pdo,databaseDriver()->name());$result['result']=$sync->run($root.'/database/seeds');}
 elseif($action==='database-backup'){$cfg=require $root.'/config/database.php';$name='production-db-before_'.gmdate('YmdHis').'_' . preg_replace('/[^a-f0-9]/','',(string)($request['commit']??'unknown')).'.sql.gz';$path=$root.'/storage/backups/'.$name;if(!is_dir(dirname($path))&&!mkdir(dirname($path),0700,true))throw new RuntimeException('Backup directory unavailable.');$dump='/usr/bin/mysqldump';$gzip='/usr/bin/gzip';if(!is_executable($dump)||!is_executable($gzip)||!function_exists('proc_open'))throw new RuntimeException('Reliable database backup capability is unavailable.');$defaults=tempnam($nonceDir,'db-');file_put_contents($defaults,"[client]\nhost=".$cfg['host']."\nport=".$cfg['port']."\nuser=".$cfg['username']."\npassword=".$cfg['password']."\n",LOCK_EX);chmod($defaults,0600);$command=escapeshellarg($dump).' --defaults-extra-file='.escapeshellarg($defaults).' --single-transaction --routines --triggers --events '.escapeshellarg($cfg['database']).' | '.escapeshellarg($gzip).' -9 > '.escapeshellarg($path);$process=proc_open($command,[1=>['pipe','w'],2=>['pipe','w']],$pipes);$error=stream_get_contents($pipes[2]);$code=proc_close($process);@unlink($defaults);clearstatcache(true,$path);if($code!==0||!is_file($path)||filesize($path)<1024)throw new RuntimeException('Database backup failed: '.substr(trim($error),0,300));chmod($path,0600);$result['backup']=['name'=>$name,'size'=>filesize($path),'sha256'=>hash_file('sha256',$path)];}
 elseif($action==='release-health'){$result['checks']=['autoload'=>is_file($root.'/vendor/autoload.php'),'database'=>true,'protected_config'=>is_file($root.'/config/database.php')&&is_file($root.'/config/app.local.php'),'storage'=>is_dir($root.'/storage')&&is_writable($root.'/storage'),'manifest'=>is_file($root.'/deployment-manifest.txt')];if(in_array(false,$result['checks'],true))throw new RuntimeException('Release health failed.');}
 if(!$readOnlyDiscovery){$log=$root.'/storage/logs/deployment-actions.log';file_put_contents($log,json_encode(['time'=>gmdate(DATE_ATOM),'action'=>$action,'remote'=>$_SERVER['REMOTE_ADDR']??null,'ok'=>true],JSON_UNESCAPED_SLASHES).PHP_EOL,FILE_APPEND|LOCK_EX);}echo json_encode($result,JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){http_response_code(500);error_log('Deployment runner '.$action.' failed: '.$e->getMessage());echo json_encode(['ok'=>false,'action'=>$action,'error'=>'deployment_action_failed','message'=>$e->getMessage()]);}
