<?php $incentiveDetail=$data['incentiveDetail']??[];$claim=$incentiveDetail['claim'];$settlements=$incentiveDetail['settlements'];$events=$incentiveDetail['events'];$notice=$data['notice']??null;$error=$data['error']??null;$canApproveIncentive=$data['canApproveIncentive']??false;$canSettleIncentive=$data['canSettleIncentive']??false; ?>
<div class="module-stack">
<div class="page-actions"><a class="btn btn-secondary" href="<?=e(appBasePath())?>/sales/incentives">Back to Incentives</a></div>
<?php if(!empty($notice)):?><div class="notice success"><?=e($notice)?></div><?php endif;?>
<?php if(!empty($error)):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<section class="card"><div class="page-heading-row"><h2>Safaricom incentive #<?=(int)$claim['incentive_claim_id']?></h2><span class="status-badge"><?=e(str_replace('_',' ',$claim['status']))?></span></div><div class="detail-grid"><div><strong>DSA/DSP</strong><br><?=e($claim['dsa_name'])?></div><div><strong>Responsible manager</strong><br><?=e($claim['manager_name'])?></div><div><strong>Originating report</strong><br><a href="<?=e(appBasePath())?>/sales/quick-sale/<?=(int)$claim['quick_sale_id']?>"><?=e('Report #'.$claim['originating_report_id'])?></a></div><div><strong>Float issuance</strong><br><?=e($claim['float_reference'].' · '.$claim['issued_date'])?></div><div><strong>Float</strong><br><?=e($claim['float_amount'].' '.$claim['currency'])?></div><div><strong>Normal sold settlement</strong><br><?=e($claim['sold_amount'].' '.$claim['currency'])?></div><div><strong>Proposed incentive</strong><br><?=e($claim['proposed_amount'].' '.$claim['currency'])?></div><div><strong>Approved incentive</strong><br><?=e(($claim['approved_amount']??'0.00').' '.$claim['currency'])?></div><div><strong>Safaricom settled</strong><br><?=e($claim['settled_amount'].' '.$claim['currency'])?></div><div><strong>Safaricom outstanding</strong><br><?=e($claim['outstanding'].' '.$claim['currency'])?></div><div><strong>Unexplained DSA/DSP variance</strong><br><?=e($claim['unexplained_variance'].' '.$claim['currency'])?></div></div><p><strong>Safaricom reference:</strong> <?=e($claim['external_reference']??'—')?></p><?php if(!empty($claim['rejection_reason'])):?><p><strong>Rejection reason:</strong> <?=e($claim['rejection_reason'])?></p><?php endif;?></section>
<?php if($claim['status']==='submitted'&&!empty($canApproveIncentive)&&(int)$claim['responsible_manager_id']===(int)($_SESSION['auth']['user_id']??0)):?><section class="card"><h3>Manager decision</h3><form method="post" action="<?=e(appBasePath())?>/sales/incentives/<?=(int)$claim['incentive_claim_id']?>/decision"><?=csrfField()?><div class="finance-filter-form"><label>Approved amount<input name="approved_amount" type="number" min="0.01" max="<?=e($claim['proposed_amount'])?>" step="0.01" value="<?=e($claim['proposed_amount'])?>"></label><label>Decision reason<input name="reason" maxlength="1000"></label></div><button class="btn btn-primary" name="decision" value="approve">Approve incentive</button> <button class="btn btn-secondary" name="decision" value="reject">Reject claim</button></form></section><?php endif;?>
<?php if(in_array($claim['status'],['approved','partially_settled'],true)&&!empty($canSettleIncentive)):?><section class="card"><h3>Record Safaricom settlement</h3><form method="post" action="<?=e(appBasePath())?>/sales/incentives/<?=(int)$claim['incentive_claim_id']?>/settlements"><?=csrfField()?><div class="finance-filter-form"><label>Date<input type="date" name="settlement_date" value="<?=e(date('Y-m-d'))?>" required></label><label>Amount<input type="number" name="amount" min="0.01" max="<?=e($claim['outstanding'])?>" step="0.01" required></label><label>Currency<input name="currency" value="<?=e($claim['currency'])?>" readonly></label><label>Safaricom payment reference<input name="external_payment_reference" maxlength="190" required></label><label>Evidence/reference<input name="evidence_reference" maxlength="500"></label></div><button class="btn btn-primary">Record settlement</button></form></section><?php endif;?>
<section class="card table-card"><h3>Safaricom settlement history</h3><div class="table-responsive"><table class="data-table"><thead><tr><th>Date</th><th>Amount</th><th>Currency</th><th>Payment reference</th><th>Evidence/reference</th><th>Entered by</th></tr></thead><tbody><?php if($settlements===[]):?><tr><td colspan="6">No settlement recorded.</td></tr><?php endif;?><?php foreach($settlements as $settlement):?><tr><td><?=e($settlement['settlement_date'])?></td><td><?=e($settlement['amount'])?></td><td><?=e($settlement['currency'])?></td><td><?=e($settlement['external_payment_reference'])?></td><td><?=e($settlement['evidence_reference']??'—')?></td><td><?=e($settlement['entered_by'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card table-card"><h3>Immutable event history</h3><div class="table-responsive"><table class="data-table"><thead><tr><th>When</th><th>Event</th><th>From</th><th>To</th><th>Actor</th><th>Reason/reference</th></tr></thead><tbody><?php foreach($events as $event):?><tr><td><?=e($event['occurred_at'])?></td><td><?=e(str_replace('_',' ',$event['event_type']))?></td><td><?=e($event['from_status']??'—')?></td><td><?=e($event['to_status'])?></td><td><?=e($event['actor_id'])?></td><td><?=e($event['reason_reference']??'—')?></td></tr><?php endforeach;?></tbody></table></div></section>
</div>
