<?php $brands=$variants['brands']??[];$models=$variants['models']??[];$products=$variants['products']??[]; ?>
<div class="module-stack">
<?php if(!empty($notice)):?><div class="notice success"><?=e($notice)?></div><?php endif;?>
<?php if(!empty($error)):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<section class="card"><h2>Mobile and MiFi SKU classification</h2><p>Each sellable or stock-distinct variant remains a real SKU. Legacy products remain unclassified until explicitly assigned; names are never guessed.</p></section>
<?php if(!empty($canManageVariants)):?>
<section class="card"><h3>Add brand</h3><form method="post" action="<?=e(appBasePath())?>/sales/product-variants/brands"><?=csrfField()?><div class="finance-filter-form"><label>Brand<input name="name" maxlength="120" required></label></div><button class="btn btn-primary">Add brand</button></form></section>
<section class="card"><h3>Add model</h3><form method="post" action="<?=e(appBasePath())?>/sales/product-variants/models"><?=csrfField()?><div class="finance-filter-form"><label>Type<select name="product_family" required><option value="mobile">Mobile</option><option value="mifi">MiFi</option></select></label><label>MiFi subtype<select name="mifi_subtype"><option value="">None for Mobile</option><option value="portable">Portable</option><option value="non_portable">Non-Portable</option></select></label><label>Brand<select name="brand_id" required><option value="">Select active brand</option><?php foreach($brands as $brand):if(empty($brand['active']))continue;?><option value="<?=(int)$brand['brand_id']?>"><?=e($brand['name'])?></option><?php endforeach;?></select></label><label>Model<input name="model_name" maxlength="160" required></label></div><button class="btn btn-primary">Add model</button></form></section>
<section class="card"><h3>Assign SKU to model</h3><form method="post" action="<?=e(appBasePath())?>/sales/product-variants/assign"><?=csrfField()?><div class="finance-filter-form"><label>SKU<select name="product_id" required><option value="">Select SKU</option><?php foreach($products as $product):?><option value="<?=(int)$product['product_id']?>"><?=e($product['sku'].' — '.$product['name'])?></option><?php endforeach;?></select></label><label>Model<select name="model_id"><option value="">Unclassified</option><?php foreach($models as $model):if(empty($model['active'])||empty($model['brand_active']))continue;?><option value="<?=(int)$model['model_id']?>"><?=e($model['product_family'].' / '.($model['mifi_subtype']??'').' / '.$model['brand_name'].' / '.$model['model_name'])?></option><?php endforeach;?></select></label></div><button class="btn btn-primary">Save SKU classification</button></form></section>
<?php endif;?>
<section class="card table-card"><h3>Classified SKUs</h3><div class="table-responsive"><table class="data-table"><thead><tr><th>SKU</th><th>Product</th><th>Type</th><th>MiFi subtype</th><th>Brand</th><th>Model</th><th>Active</th></tr></thead><tbody><?php foreach($products as $product):?><tr><td><?=e($product['sku'])?></td><td><?=e($product['name'])?></td><td><?=e($product['product_family']??'Legacy / unclassified')?></td><td><?=e($product['mifi_subtype']??'—')?></td><td><?=e($product['brand_name']??'—')?></td><td><?=e($product['model_name']??'—')?></td><td><?=!empty($product['active'])?'Active':'Inactive'?></td></tr><?php endforeach;?></tbody></table></div></section>
</div>
