<?php
declare(strict_types=1);
$data=is_array($data??null)?$data:[];$mode=(string)($data['quotationMode']??'show');$q=is_array($data['quotation']??null)?$data['quotation']:[];$old=is_array($data['old']??null)?$data['old']:[];$errors=is_array($data['errors']??null)?$data['errors']:[];$notice=is_array($data['notice']??null)?$data['notice']:null;$editing=in_array($mode,['create','edit'],true);$value=static fn(string $key,mixed $default=''):mixed=>$old[$key]??$q[$key]??$default;$lines=is_array($old['lines']??null)?$old['lines']:(is_array($q['lines']??null)?$q['lines']:[]);while(count($lines)<5)$lines[]=[];$currency=(string)($data['user']['company']['default_currency']??'ETB');
?>
<div class="sales-workspace">
<nav class="card"><a class="btn btn-secondary btn-compact" href="/office_app/public/sales/quotations">Back to quotations</a><?php if(!$editing&&!empty($data['canEdit'])&&($q['status']??'')==='draft'):?> <a class="btn btn-primary btn-compact" href="/office_app/public/sales/quotations/<?=e($q['quotation_id'])?>/edit">Edit</a><?php endif;?></nav>
<?php if($notice!==null):?><div class="alert alert-success"><?=e($notice['message']??'')?></div><?php endif;?>
<?php if($errors!==[]):?><div class="alert alert-danger"><strong>The quotation was not saved.</strong><?php foreach($errors as $error):?><div><?=e($error)?></div><?php endforeach;?></div><?php endif;?>
<header class="page-header"><div><p class="eyebrow">Sales quotation</p><h1><?=e($mode==='create'?'New quotation':($q['quotation_number']??'Quotation'))?></h1><?php if(!$editing):?><p class="page-description">Status: <strong><?=e(strtoupper((string)($q['effective_status']??$q['status']??'')))?></strong></p><?php endif;?></div></header>
<?php if($editing):?>
<form method="post" action="/office_app/public/sales/quotations<?= $mode==='edit'?'/'.e($q['quotation_id']):'' ?>" class="card finance-filter-panel"><?=csrfField()?>
<div class="finance-filter-form">
<div class="form-field"><label>Customer</label><select name="customer_id" required><option value="">Select customer</option><?php foreach($data['customers'] as $customer):?><option value="<?=e($customer['customer_id'])?>" <?= (int)$value('customer_id')===(int)$customer['customer_id']?'selected':'' ?>><?=e($customer['customer_number'].' - '.$customer['name'])?></option><?php endforeach;?></select></div>
<div class="form-field"><label>Quotation date</label><input type="date" name="quotation_date" value="<?=e($value('quotation_date',date('Y-m-d')))?>" required></div>
<div class="form-field"><label>Expiration date</label><input type="date" name="expiration_date" value="<?=e($value('expiration_date'))?>"></div>
<div class="form-field"><label>Salesperson</label><select name="agent_id"><option value="">Unassigned</option><?php foreach($data['agents'] as $agent):?><option value="<?=e($agent['agent_id'])?>" <?= (int)$value('agent_id')===(int)$agent['agent_id']?'selected':'' ?>><?=e($agent['name'])?></option><?php endforeach;?></select></div>
<div class="form-field"><label>Sales team</label><select name="team_id"><option value="">Unassigned</option><?php foreach($data['salesTeams'] as $team):?><option value="<?=e($team['team_id'])?>" <?= (int)$value('team_id')===(int)$team['team_id']?'selected':'' ?>><?=e($team['name'])?></option><?php endforeach;?></select></div>
<div class="form-field"><label>Pricelist</label><select name="pricelist_id"><option value="">Standard price</option><?php foreach($data['pricelists'] as $price):?><?php if(!empty($price['active'])||(int)$value('pricelist_id')===(int)$price['pricelist_id']):?><option value="<?=e($price['pricelist_id'])?>" <?= (int)$value('pricelist_id')===(int)$price['pricelist_id']?'selected':'' ?>><?=e($price['name'])?></option><?php endif;?><?php endforeach;?></select></div>
<div class="form-field"><label>Payment terms (days)</label><input type="number" min="0" name="payment_terms_days" value="<?=e($value('payment_terms_days',0))?>"></div><div class="form-field"><label>Currency</label><input name="currency" maxlength="3" value="<?=e($value('currency',$currency))?>" required></div>
</div>
<div class="finance-summary-grid"><div class="form-field"><label>Billing address/contact</label><textarea name="billing_address" rows="3"><?=e($value('billing_address'))?></textarea></div><div class="form-field"><label>Delivery address/contact</label><textarea name="delivery_address" rows="3"><?=e($value('delivery_address'))?></textarea></div></div>
<div class="table-responsive"><table class="data-table"><thead><tr><th>Product</th><th>Quantity</th><th>Discount</th><th>Tax %</th></tr></thead><tbody><?php foreach($lines as $line):?><tr><td><select name="product_id[]"><option value="">Select product</option><?php foreach($data['products'] as $product):?><option value="<?=e($product['product_id'])?>" <?= (int)($line['product_id']??0)===(int)$product['product_id']?'selected':'' ?>><?=e($product['sku'].' - '.$product['name'])?></option><?php endforeach;?></select></td><td><input type="number" min="0" step="0.001" name="quantity[]" value="<?=e($line['quantity']??'')?>"></td><td><input type="number" min="0" step="0.01" name="discount_amount[]" value="<?=e($line['discount_amount']??0)?>"></td><td><input type="number" min="0" max="100" step="0.01" name="tax_rate[]" value="<?=e($line['tax_rate']??0)?>"></td></tr><?php endforeach;?></tbody></table></div>
<div class="form-field"><label>Notes / terms</label><textarea name="notes" rows="4"><?=e($value('notes'))?></textarea></div><button class="btn btn-primary" type="submit"><?= $mode==='create'?'Create quotation':'Save quotation' ?></button>
</form>
<?php else:?>
<section class="card"><div class="finance-summary-grid"><div><strong>Customer</strong><p><?=e($q['customer_name'])?></p></div><div><strong>Dates</strong><p><?=e($q['quotation_date'])?> · expires <?=e($q['expiration_date']??'never')?></p></div><div><strong>Sales owner</strong><p><?=e($q['agent_name']??'Unassigned')?> · <?=e($q['team_name']??'No team')?></p></div><div><strong>Commercial terms</strong><p><?=e($q['pricelist_name']??'Standard price')?> · <?=e($q['payment_terms_days'])?> days</p></div></div><p><strong>Billing:</strong> <?=nl2br(e($q['billing_address']??'Not specified'))?></p><p><strong>Delivery:</strong> <?=nl2br(e($q['delivery_address']??'Not specified'))?></p></section>
<section class="card table-card"><div class="table-responsive"><table class="data-table"><thead><tr><th>Product</th><th>Quantity</th><th>UoM</th><th>Unit price</th><th>Discount</th><th>Tax</th><th>Total</th></tr></thead><tbody><?php foreach($q['lines'] as $line):?><tr><td><?=e($line['sku'].' - '.$line['description'])?></td><td><?=e($line['quantity'])?></td><td><?=e($line['unit_of_measure'])?></td><td><?=e($q['currency'].' '.number_format((float)$line['unit_price'],2))?></td><td><?=e(number_format((float)$line['discount_amount'],2))?></td><td><?=e(number_format((float)$line['tax_amount'],2))?></td><td><?=e(number_format((float)$line['line_total'],2))?></td></tr><?php endforeach;?></tbody></table></div><div class="table-summary"><span>Untaxed <?=e(number_format((float)$q['untaxed_amount'],2))?> · Tax <?=e(number_format((float)$q['tax_amount'],2))?></span><strong>Total <?=e($q['currency'].' '.number_format((float)$q['total_amount'],2))?></strong></div></section>
<?php if(!empty($data['canTransition'])&&in_array($q['status'],['draft','sent'],true)):?><section class="card"><div class="filter-actions"><?php if($q['status']==='draft'):?><form method="post" action="/office_app/public/sales/quotations/<?=e($q['quotation_id'])?>/send"><?=csrfField()?><button class="btn btn-secondary">Mark sent</button></form><?php endif;?><?php if(($q['effective_status']??$q['status'])!=='expired'):?><form method="post" action="/office_app/public/sales/quotations/<?=e($q['quotation_id'])?>/confirm"><?=csrfField()?><button class="btn btn-primary">Confirm quotation</button></form><?php endif;?><form method="post" action="/office_app/public/sales/quotations/<?=e($q['quotation_id'])?>/cancel"><?=csrfField()?><button class="btn btn-secondary">Cancel quotation</button></form></div></section><?php endif;?>
<?php if(!empty($data['canTransition'])&&($q['status']??'')==='confirmed'&&($q['order_status']??'')==='submitted'):?><section class="card"><p>The linked order was created before automatic delivery preparation completed.</p><form method="post" action="/office_app/public/sales/quotations/<?=e($q['quotation_id'])?>/confirm"><?=csrfField()?><button class="btn btn-primary">Complete automatic preparation</button></form></section><?php endif;?>
<?php if(!empty($q['sales_order_id'])):?><p><a class="btn btn-primary" href="/office_app/public/sales/orders/<?=e($q['sales_order_id'])?>">Open Sales Order <?=e($q['order_number'])?></a></p><?php endif;?>
<?php endif;?></div>
