<?php

declare(strict_types=1);

$permissions = $data['user']['permissions'] ?? [];
$can = static fn (string $permission): bool => in_array($permission, $permissions, true);
$financeMode = !empty($data['financeMode']);
$humanize = static fn (mixed $value): string => ucwords(str_replace('_', ' ', (string) $value));
$tone = static fn (string $status): string => match ($status) {
    'matched', 'closed', 'approved' => 'success',
    'partial', 'awaiting_confirmation', 'submitted' => 'warning',
    'mismatch', 'review_required', 'returned', 'cancelled' => 'danger',
    default => 'neutral',
};
$maskAccount = static fn (string $account): string => strlen($account) <= 4 ? $account : '••••' . substr($account, -4);
?>
<div class="module-stack settlement-workspace">
    <?php if (is_array($data['notice'] ?? null)): ?><div class="alert alert-success"><?= e($data['notice']['message'] ?? '') ?></div><?php endif; ?>
    <?php foreach ((array) ($data['errors'] ?? []) as $error): ?><div class="alert alert-danger"><?= e($error) ?></div><?php endforeach; ?>

    <section class="card erp-record-header"><div><p class="erp-eyebrow"><?= $financeMode ? 'Finance control' : 'Sales accountability' ?></p><h2><?= $financeMode ? 'Settlement Reconciliation' : 'Settlement Overview' ?></h2><p>Reconcile posted customer payments to verified company-bank deposits without creating duplicate accounting entries.</p></div><?php if (!$financeMode && $can('sales.settlements.create')): ?><a class="btn btn-primary btn-compact" href="#create-settlement">Create Settlement</a><?php endif; ?></section>

    <section class="card table-card erp-section-card"><header class="erp-section-header"><div><p class="erp-eyebrow">History</p><h2>Settlement Register</h2></div><span><?= e(count($data['settlements'])) ?> record(s)</span></header><div class="table-responsive"><table class="data-table erp-data-table"><thead><tr><th>Settlement</th><th>Bank</th><th class="erp-money-column">Expected</th><th class="erp-money-column">Confirmed</th><th class="erp-money-column">Variance</th><th>Reconciliation</th><th>Workflow</th><th class="table-actions-column"><span class="sr-only">Actions</span></th></tr></thead><tbody>
    <?php if ($data['settlements'] === []): ?><tr><td colspan="8" class="empty-state"><strong>No settlements yet.</strong><br>Eligible posted customer payments will appear in the creation section.</td></tr><?php endif; ?>
    <?php foreach ($data['settlements'] as $settlement): ?><tr><td><strong><?= e($settlement['settlement_number']) ?></strong></td><td><?= e($settlement['bank_name']) ?><small><?= e($maskAccount((string) $settlement['account_number'])) ?></small></td><td class="erp-money erp-money-column"><?= e($settlement['currency'] . ' ' . number_format((float) $settlement['expected_amount'], 2)) ?></td><td class="erp-money erp-money-column"><?= e($settlement['currency'] . ' ' . number_format((float) $settlement['confirmed_amount'], 2)) ?></td><td class="erp-money erp-money-column"><?= e($settlement['currency'] . ' ' . number_format((float) $settlement['variance_amount'], 2)) ?></td><td><span class="erp-status-badge erp-status-<?= e($tone((string) $settlement['reconciliation_status'])) ?>"><?= e($humanize($settlement['reconciliation_status'])) ?></span></td><td><span class="erp-status-badge erp-status-<?= e($tone((string) $settlement['workflow_status'])) ?>"><?= e($humanize($settlement['workflow_status'])) ?></span></td><td><a class="btn btn-secondary btn-compact" href="<?= e(appBasePath() . '/sales/settlements/' . $settlement['settlement_id']) ?>">View</a></td></tr><?php endforeach; ?>
    </tbody></table></div></section>

    <?php if (!$financeMode && $can('sales.settlements.create')): ?><section class="card erp-section-card" id="create-settlement"><header class="erp-section-header"><div><p class="erp-eyebrow">New record</p><h2>Create New Settlement</h2><p>Select a deposit account and the authoritative posted payments included in this bank deposit.</p></div></header>
        <?php if ($data['bankAccounts'] === []): ?><div class="empty-state">Add a company bank account before creating a settlement.</div><?php else: ?><form method="post" action="<?= e(appBasePath() . '/sales/settlements') ?>"><?= csrfField() ?><div class="erp-form-grid"><label class="form-field erp-field-wide">Deposit Bank Account<select name="bank_account_id" required><?php foreach ($data['bankAccounts'] as $bank): ?><option value="<?= e($bank['bank_account_id']) ?>"><?= e($bank['bank_name'] . ' · ' . $maskAccount((string) $bank['account_number']) . ' · ' . $bank['currency'] . ($bank['is_default'] ? ' · Default' : '')) ?></option><?php endforeach; ?></select></label></div><fieldset class="erp-payment-selector"><legend>Eligible Posted Customer Payments</legend><?php if ($data['eligiblePayments'] === []): ?><p class="empty-state">No eligible posted payments are currently awaiting settlement.</p><?php endif; ?><?php foreach ($data['eligiblePayments'] as $payment): ?><label class="erp-check-row"><input type="checkbox" name="payment_ids[]" value="<?= e($payment['payment_id']) ?>"><span><strong><?= e($payment['payment_number'] . ' · ' . $payment['order_number']) ?></strong><small><?= e($payment['customer_name'] . ' · ' . ($payment['reference_number'] ?? 'No reference')) ?></small></span><b class="erp-money"><?= e($payment['currency'] . ' ' . number_format((float) $payment['amount'], 2)) ?></b></label><?php endforeach; ?></fieldset><label class="form-field">Notes <span class="erp-optional">Optional</span><textarea name="notes" maxlength="1000" rows="3"></textarea></label><div class="erp-form-actions"><button class="btn btn-primary">Create Settlement</button></div></form><?php endif; ?>
    </section><?php endif; ?>

    <?php if ($can('finance.bank_accounts.manage')): ?><section class="card erp-section-card"><header class="erp-section-header"><div><p class="erp-eyebrow">Treasury setup</p><h2>Company Bank Accounts</h2><p>Accounts are company-scoped. Provider code is reserved for future integrations.</p></div></header><form method="post" action="<?= e(appBasePath() . '/finance/company-bank-accounts') ?>"><?= csrfField() ?><div class="erp-form-grid erp-form-grid-three"><label class="form-field">Bank Name<input name="bank_name" required></label><label class="form-field">Account Name<input name="account_name" required></label><label class="form-field">Account Number<input name="account_number" autocomplete="off" required></label><label class="form-field">Branch <span class="erp-optional">Optional</span><input name="branch"></label><label class="form-field">Currency<input name="currency" value="ETB" maxlength="3" required></label><label class="form-field">SWIFT / BIC <span class="erp-optional">Optional</span><input name="swift_bic" maxlength="11"></label><label class="form-field">Provider Code <span class="erp-optional">Future</span><input name="provider_code"></label><label class="erp-checkbox-field"><input type="checkbox" name="is_default" value="1"><span><strong>Default Account</strong><small>Preselect this account for new settlements.</small></span></label></div><div class="erp-form-actions"><button class="btn btn-primary">Add Bank Account</button></div></form></section><?php endif; ?>
</div>
