<?php

declare(strict_types=1);

namespace App\Repositories\MySql;

use App\Repositories\AssetRepository as AssetRepositoryContract;
use PDO;
use RuntimeException;

final class AssetRepository extends MySqlRepository implements AssetRepositoryContract
{
    public function workspace(int $companyId): array
    {
        $c=$this->connection();$assets=$c->prepare("SELECT a.*,c.category_code,c.category_name,d.name department_name,CONCAT(e.first_name,' ',e.last_name) custodian_name,(SELECT COUNT(*) FROM asset_depreciation_schedule s WHERE s.company_id=a.company_id AND s.asset_id=a.asset_id) depreciation_count,(SELECT COUNT(*) FROM asset_depreciation_schedule s WHERE s.company_id=a.company_id AND s.asset_id=a.asset_id AND s.status='posted') posted_depreciation_count,(SELECT COUNT(*) FROM asset_transfers t WHERE t.company_id=a.company_id AND t.asset_id=a.asset_id) transfer_count,(SELECT COUNT(*) FROM asset_maintenance_records m WHERE m.company_id=a.company_id AND m.asset_id=a.asset_id) maintenance_count FROM fixed_assets a INNER JOIN asset_categories c ON c.company_id=a.company_id AND c.asset_category_id=a.asset_category_id LEFT JOIN hr_departments d ON d.company_id=a.company_id AND d.department_id=a.department_id LEFT JOIN hr_employees e ON e.company_id=a.company_id AND e.employee_id=a.custodian_employee_id WHERE a.company_id=:company_id ORDER BY a.asset_id DESC");$assets->execute(['company_id'=>$companyId]);
        $categories=$c->prepare('SELECT * FROM asset_categories WHERE company_id=:company_id ORDER BY category_name');$categories->execute(['company_id'=>$companyId]);
        $accounts=$c->prepare("SELECT account_id,account_code,account_name,account_type,normal_balance FROM finance_accounts WHERE company_id=:company_id AND active=TRUE AND deleted_at IS NULL ORDER BY account_code");$accounts->execute(['company_id'=>$companyId]);
        $departments=$c->prepare('SELECT department_id,name FROM hr_departments WHERE company_id=:company_id AND active=TRUE AND deleted_at IS NULL ORDER BY name');$departments->execute(['company_id'=>$companyId]);
        $employees=$c->prepare("SELECT employee_id,CONCAT(first_name,' ',last_name) name FROM hr_employees WHERE company_id=:company_id AND employment_status='active' AND deleted_at IS NULL ORDER BY first_name,last_name");$employees->execute(['company_id'=>$companyId]);
        $stock=$c->prepare("SELECT b.warehouse_id,b.location_id,b.product_id,b.quantity_on_hand-b.quantity_reserved available,b.average_unit_cost,w.name warehouse_name,l.name location_name,p.sku,p.name product_name,p.serial_tracking FROM inventory_stock_balances b INNER JOIN inventory_warehouses w ON w.company_id=b.company_id AND w.warehouse_id=b.warehouse_id INNER JOIN inventory_warehouse_locations l ON l.company_id=b.company_id AND l.location_id=b.location_id AND l.location_usage='internal' INNER JOIN sales_products p ON p.company_id=b.company_id AND p.product_id=b.product_id WHERE b.company_id=:company_id AND b.quantity_on_hand-b.quantity_reserved>0 ORDER BY p.name,w.name,l.name");$stock->execute(['company_id'=>$companyId]);
        return['assets'=>$assets->fetchAll(PDO::FETCH_ASSOC),'categories'=>$categories->fetchAll(PDO::FETCH_ASSOC),'accounts'=>$accounts->fetchAll(PDO::FETCH_ASSOC),'departments'=>$departments->fetchAll(PDO::FETCH_ASSOC),'employees'=>$employees->fetchAll(PDO::FETCH_ASSOC),'stock'=>$stock->fetchAll(PDO::FETCH_ASSOC)];
    }
    public function asset(int $companyId,int $assetId,bool $forUpdate=false): ?array
    {$s=$this->connection()->prepare("SELECT a.*,c.category_name,c.asset_account_id,c.accumulated_depreciation_account_id,c.depreciation_expense_account_id,c.disposal_gain_account_id,c.disposal_loss_account_id,d.name department_name,CONCAT(e.first_name,' ',e.last_name) custodian_name,p.sku source_product_sku,p.name source_product_name,w.name source_warehouse_name,l.name source_location_name,m.reference_type source_reference_type,m.reference_id source_reference_id,m.reference_number source_reference_number FROM fixed_assets a INNER JOIN asset_categories c ON c.company_id=a.company_id AND c.asset_category_id=a.asset_category_id LEFT JOIN hr_departments d ON d.company_id=a.company_id AND d.department_id=a.department_id LEFT JOIN hr_employees e ON e.company_id=a.company_id AND e.employee_id=a.custodian_employee_id LEFT JOIN sales_products p ON p.company_id=a.company_id AND p.product_id=a.product_id LEFT JOIN inventory_warehouses w ON w.company_id=a.company_id AND w.warehouse_id=a.source_warehouse_id LEFT JOIN inventory_warehouse_locations l ON l.company_id=a.company_id AND l.location_id=a.source_location_id LEFT JOIN inventory_stock_movements m ON m.company_id=a.company_id AND m.movement_id=a.source_inventory_movement_id WHERE a.company_id=:company_id AND a.asset_id=:asset_id".($forUpdate?' FOR UPDATE':''));$s->execute(['company_id'=>$companyId,'asset_id'=>$assetId]);$a=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($a))return null;foreach(['schedule'=>"SELECT * FROM asset_depreciation_schedule WHERE company_id=:company_id AND asset_id=:asset_id ORDER BY period_number",'transfers'=>"SELECT * FROM asset_transfers WHERE company_id=:company_id AND asset_id=:asset_id ORDER BY transferred_at DESC",'maintenance'=>"SELECT * FROM asset_maintenance_records WHERE company_id=:company_id AND asset_id=:asset_id ORDER BY maintenance_date DESC",'history'=>"SELECT * FROM asset_history WHERE company_id=:company_id AND asset_id=:asset_id ORDER BY occurred_at DESC,asset_history_id DESC"] as $key=>$sql){$q=$this->connection()->prepare($sql);$q->execute(['company_id'=>$companyId,'asset_id'=>$assetId]);$a[$key]=$q->fetchAll(PDO::FETCH_ASSOC);}return$a;}
    public function category(int $companyId,int $categoryId): ?array{$s=$this->connection()->prepare('SELECT * FROM asset_categories WHERE company_id=:company_id AND asset_category_id=:id AND active=TRUE');$s->execute(['company_id'=>$companyId,'id'=>$categoryId]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null;}
    public function createCategory(int $companyId,array $v,int $actorId): int{$s=$this->connection()->prepare('INSERT INTO asset_categories(company_id,category_code,category_name,asset_account_id,accumulated_depreciation_account_id,depreciation_expense_account_id,disposal_gain_account_id,disposal_loss_account_id,useful_life_months,salvage_behavior,created_by,updated_by) VALUES(:company_id,:category_code,:category_name,:asset_account_id,:accumulated_depreciation_account_id,:depreciation_expense_account_id,:disposal_gain_account_id,:disposal_loss_account_id,:useful_life_months,:salvage_behavior,:actor,:actor2)');$s->execute($v+['company_id'=>$companyId,'actor'=>$actorId,'actor2'=>$actorId]);return(int)$this->connection()->lastInsertId();}
    public function createAsset(int $companyId,array $v,int $actorId): int{$s=$this->connection()->prepare("INSERT INTO fixed_assets(company_id,asset_category_id,asset_number,asset_name,department_id,custodian_employee_id,location_name,vendor_name,acquisition_date,acquisition_cost,salvage_value,book_value,currency,depreciation_method,useful_life_months,depreciation_frequency,serial_number,status,created_by,updated_by) VALUES(:company_id,:asset_category_id,:asset_number,:asset_name,:department_id,:custodian_employee_id,:location_name,:vendor_name,:acquisition_date,:acquisition_cost,:salvage_value,:book_value,:currency,'straight_line',:useful_life_months,'monthly',:serial_number,'draft',:actor,:actor2)");$s->execute($v+['company_id'=>$companyId,'actor'=>$actorId,'actor2'=>$actorId]);return(int)$this->connection()->lastInsertId();}
    public function activate(int $companyId,int $assetId,string $inServiceDate,array $schedule,int $actorId): void{$u=$this->connection()->prepare("UPDATE fixed_assets SET status='active',in_service_date=:date,activated_by=:actor,activated_at=NOW(),updated_by=:actor2 WHERE company_id=:company_id AND asset_id=:asset_id AND status='draft'");$u->execute(['date'=>$inServiceDate,'actor'=>$actorId,'actor2'=>$actorId,'company_id'=>$companyId,'asset_id'=>$assetId]);if($u->rowCount()!==1)throw new RuntimeException('Only a draft asset can be activated.');$i=$this->connection()->prepare('INSERT INTO asset_depreciation_schedule(company_id,asset_id,period_number,depreciation_date,depreciation_amount,accumulated_amount,book_value_after) VALUES(:company_id,:asset_id,:period_number,:depreciation_date,:depreciation_amount,:accumulated_amount,:book_value_after)');foreach($schedule as $row)$i->execute($row+['company_id'=>$companyId,'asset_id'=>$assetId]);}
    public function depreciationLine(int $companyId,int $lineId,bool $forUpdate=false): ?array{$s=$this->connection()->prepare("SELECT s.*,a.asset_number,a.asset_name,a.status asset_status,a.currency,a.salvage_value,a.asset_account_id,a.accumulated_depreciation_account_id,a.depreciation_expense_account_id FROM asset_depreciation_schedule s INNER JOIN (SELECT f.*,c.asset_account_id,c.accumulated_depreciation_account_id,c.depreciation_expense_account_id FROM fixed_assets f INNER JOIN asset_categories c ON c.company_id=f.company_id AND c.asset_category_id=f.asset_category_id) a ON a.company_id=s.company_id AND a.asset_id=s.asset_id WHERE s.company_id=:company_id AND s.depreciation_line_id=:line_id".($forUpdate?' FOR UPDATE':''));$s->execute(['company_id'=>$companyId,'line_id'=>$lineId]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null;}
    public function markDepreciationPosted(int $companyId,int $lineId,int $journalBatchId,float $accumulated,float $bookValue,string $assetStatus,int $actorId): void{$s=$this->connection()->prepare("UPDATE asset_depreciation_schedule SET status='posted',journal_batch_id=:batch,posted_by=:actor,posted_at=NOW() WHERE company_id=:company_id AND depreciation_line_id=:line_id AND status='scheduled'");$s->execute(['batch'=>$journalBatchId,'actor'=>$actorId,'company_id'=>$companyId,'line_id'=>$lineId]);if($s->rowCount()!==1)throw new RuntimeException('Depreciation period is not available for posting.');$u=$this->connection()->prepare('UPDATE fixed_assets f INNER JOIN asset_depreciation_schedule s ON s.company_id=f.company_id AND s.asset_id=f.asset_id SET f.accumulated_depreciation=:accumulated,f.book_value=:book_value,f.status=:status,f.updated_by=:actor WHERE s.company_id=:company_id AND s.depreciation_line_id=:line_id');$u->execute(['accumulated'=>$accumulated,'book_value'=>$bookValue,'status'=>$assetStatus,'actor'=>$actorId,'company_id'=>$companyId,'line_id'=>$lineId]);}
    public function transfer(int $companyId,int $assetId,array $v,int $actorId): int{$a=$this->asset($companyId,$assetId,true);if(!$a||!in_array($a['status'],['active','fully_depreciated','under_maintenance'],true))throw new RuntimeException('Only an active asset can be transferred.');$s=$this->connection()->prepare('INSERT INTO asset_transfers(company_id,asset_id,from_department_id,to_department_id,from_custodian_employee_id,to_custodian_employee_id,from_location_name,to_location_name,transferred_at,reason,transferred_by) VALUES(:company_id,:asset_id,:from_department_id,:to_department_id,:from_custodian_employee_id,:to_custodian_employee_id,:from_location_name,:to_location_name,NOW(),:reason,:actor)');$s->execute(['company_id'=>$companyId,'asset_id'=>$assetId,'from_department_id'=>$a['department_id'],'to_department_id'=>$v['department_id'],'from_custodian_employee_id'=>$a['custodian_employee_id'],'to_custodian_employee_id'=>$v['custodian_employee_id'],'from_location_name'=>$a['location_name'],'to_location_name'=>$v['location_name'],'reason'=>$v['reason'],'actor'=>$actorId]);$id=(int)$this->connection()->lastInsertId();$u=$this->connection()->prepare('UPDATE fixed_assets SET department_id=:department_id,custodian_employee_id=:custodian,location_name=:location,updated_by=:actor WHERE company_id=:company_id AND asset_id=:asset_id');$u->execute(['department_id'=>$v['department_id'],'custodian'=>$v['custodian_employee_id'],'location'=>$v['location_name'],'actor'=>$actorId,'company_id'=>$companyId,'asset_id'=>$assetId]);return$id;}
    public function addMaintenance(int $companyId,int $assetId,array $v,int $actorId): int{$a=$this->asset($companyId,$assetId,true);if(!$a||in_array($a['status'],['disposed','sold','scrapped','cancelled'],true))throw new RuntimeException('Maintenance cannot be recorded for this asset state.');$s=$this->connection()->prepare("INSERT INTO asset_maintenance_records(company_id,asset_id,maintenance_type,description,vendor_name,cost,maintenance_date,status,capitalized,created_by) VALUES(:company_id,:asset_id,:maintenance_type,:description,:vendor_name,:cost,:maintenance_date,'completed',FALSE,:actor)");$s->execute($v+['company_id'=>$companyId,'asset_id'=>$assetId,'actor'=>$actorId]);return(int)$this->connection()->lastInsertId();}
    public function updateTracking(int $companyId,int $assetId,array $v,int $actorId): void{$s=$this->connection()->prepare("UPDATE fixed_assets SET presence_status=:presence_status,health_status=:health_status,last_verified_at=NOW(),last_verified_by=:actor,updated_by=:actor2 WHERE company_id=:company_id AND asset_id=:asset_id AND status NOT IN('disposed','sold','scrapped','cancelled')");$s->execute(['presence_status'=>$v['presence_status'],'health_status'=>$v['health_status'],'actor'=>$actorId,'actor2'=>$actorId,'company_id'=>$companyId,'asset_id'=>$assetId]);}
    public function dispose(int $companyId,int $assetId,array $v,int $actorId): int{$s=$this->connection()->prepare('INSERT INTO asset_disposals(company_id,asset_id,disposal_type,disposal_date,proceeds_amount,book_value_at_disposal,gain_amount,loss_amount,journal_batch_id,reason,disposed_by,disposed_at) VALUES(:company_id,:asset_id,:disposal_type,:disposal_date,:proceeds_amount,:book_value_at_disposal,:gain_amount,:loss_amount,:journal_batch_id,:reason,:actor,NOW())');$s->execute($v+['company_id'=>$companyId,'asset_id'=>$assetId,'actor'=>$actorId]);$id=(int)$this->connection()->lastInsertId();$status=$v['disposal_type']==='sale'?'sold':($v['disposal_type']==='scrap'?'scrapped':'disposed');$u=$this->connection()->prepare('UPDATE fixed_assets SET status=:status,updated_by=:actor WHERE company_id=:company_id AND asset_id=:asset_id');$u->execute(['status'=>$status,'actor'=>$actorId,'company_id'=>$companyId,'asset_id'=>$assetId]);$x=$this->connection()->prepare("UPDATE asset_depreciation_schedule SET status='cancelled' WHERE company_id=:company_id AND asset_id=:asset_id AND status='scheduled'");$x->execute(['company_id'=>$companyId,'asset_id'=>$assetId]);return$id;}
    public function linkInventorySource(int $companyId,int $assetId,int $movementId,int $warehouseId,int $locationId,int $productId,float $quantity,float $cost): void{$s=$this->connection()->prepare('UPDATE fixed_assets SET product_id=:product,source_inventory_movement_id=:movement,source_warehouse_id=:warehouse,source_location_id=:location,source_quantity=:quantity,acquisition_cost=:cost,book_value=:cost2 WHERE company_id=:company_id AND asset_id=:asset_id');$s->execute(['product'=>$productId,'movement'=>$movementId,'warehouse'=>$warehouseId,'location'=>$locationId,'quantity'=>$quantity,'cost'=>$cost,'cost2'=>$cost,'company_id'=>$companyId,'asset_id'=>$assetId]);}
    public function history(int $companyId,int $assetId,string $action,?string $from,?string $to,array $details,int $actorId): void{$s=$this->connection()->prepare('INSERT INTO asset_history(company_id,asset_id,action,from_status,to_status,details_json,actor_id,occurred_at) VALUES(:company_id,:asset_id,:action,:from_status,:to_status,:details,:actor,NOW())');$s->execute(['company_id'=>$companyId,'asset_id'=>$assetId,'action'=>$action,'from_status'=>$from,'to_status'=>$to,'details'=>json_encode($details,JSON_THROW_ON_ERROR),'actor'=>$actorId]);}
}
