[CmdletBinding(DefaultParameterSetName='Deploy')]
param([switch]$Execute,[switch]$VerifyOnly,[int]$ProductionMigration=-1,[string]$Rollback,[switch]$AllowDirty)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;$root=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path;$dist=Join-Path $root 'dist';$script:cfg=$null;$script:runnerUrl=$null;$script:trackedDirty=$false;$reportPath=$null;$reportData=[ordered]@{Result='IN_PROGRESS';Rollback='not requested';Health=@();MigrationsApplied=@();ReferenceSync='not run'}
function Read-Env([string]$Path){$values=@{};if(Test-Path $Path){foreach($line in Get-Content $Path){if($line.Trim()-eq''-or$line.TrimStart().StartsWith('#')){continue};$pair=$line.Split('=',2);if($pair.Count-eq 2){$values[$pair[0].Trim()]=$pair[1].Trim()}}};return $values}
function Require-CleanRelease{$branch=(git -C $root branch --show-current).Trim();if($branch-ne'main'){throw 'HEAD must be on main.'};$head=(git -C $root rev-parse HEAD).Trim();git -C $root fetch origin main --quiet;if($LASTEXITCODE-ne 0){throw 'Unable to verify origin/main.'};$origin=(git -C $root rev-parse origin/main).Trim();if($head-ne$origin){throw 'HEAD is not pushed to origin/main.'};$tracked=@(git -C $root status --porcelain --untracked-files=no);$script:trackedDirty=$tracked.Count-gt 0;if($script:trackedDirty-and$Execute-and-not$AllowDirty){throw 'Tracked working-tree changes exist.'};return $head}
function Invoke-Uapi([string]$Module,[string]$Function,[hashtable]$Query=@{},[hashtable]$Form=$null){$base='https://'+$script:cfg.CPANEL_HOST.TrimEnd('/');$uri="$base/execute/$Module/$Function";if($Query.Count){$uri+='?'+(($Query.GetEnumerator()|ForEach-Object{[uri]::EscapeDataString($_.Key)+'='+[uri]::EscapeDataString([string]$_.Value)})-join'&')};$auth='cpanel '+$script:cfg.CPANEL_USERNAME+':'+$script:cfg.CPANEL_API_TOKEN;if($null-ne$Form){Add-Type -AssemblyName System.Net.Http;$client=[Net.Http.HttpClient]::new();$content=[Net.Http.MultipartFormDataContent]::new();try{$client.DefaultRequestHeaders.Add('Authorization',$auth);foreach($key in $Form.Keys){if($Form[$key]-is[IO.FileInfo]){$stream=[IO.File]::OpenRead($Form[$key].FullName);$part=[Net.Http.StreamContent]::new($stream);$content.Add($part,$key,$Form[$key].Name)}else{$content.Add([Net.Http.StringContent]::new([string]$Form[$key]),$key)}};$raw=$client.PostAsync($uri,$content).GetAwaiter().GetResult();$json=$raw.Content.ReadAsStringAsync().GetAwaiter().GetResult();if(-not$raw.IsSuccessStatusCode){throw "cPanel upload HTTP $([int]$raw.StatusCode): $json"};$response=$json|ConvertFrom-Json}finally{$content.Dispose();$client.Dispose()}}else{$response=Invoke-RestMethod -Method Get -Uri $uri -Headers @{Authorization=$auth}};if($response.result.status-ne 1){throw "cPanel UAPI $Module/$Function failed: $($response.result.errors -join '; ')"};return $response.result.data}
function Invoke-Api2([string]$Function,[hashtable]$Parameters){$query=@{cpanel_jsonapi_user=$script:cfg.CPANEL_USERNAME;cpanel_jsonapi_apiversion='2';cpanel_jsonapi_module='Fileman';cpanel_jsonapi_func=$Function}+$Parameters;$base='https://'+$script:cfg.CPANEL_HOST.TrimEnd('/');$uri=$base+'/json-api/cpanel?'+(($query.GetEnumerator()|ForEach-Object{[uri]::EscapeDataString($_.Key)+'='+[uri]::EscapeDataString([string]$_.Value)})-join'&');$headers=@{Authorization='cpanel '+$script:cfg.CPANEL_USERNAME+':'+$script:cfg.CPANEL_API_TOKEN};$r=Invoke-RestMethod -Method Get -Uri $uri -Headers $headers;if($r.cpanelresult.event.result-ne 1){throw "cPanel API2 Fileman/$Function failed: $($r.cpanelresult.error)"};return $r.cpanelresult.data}
function Runner([string]$Action,[string]$ReleaseRoot,[hashtable]$Extra=@{}){$payload=(@{action=$Action}+$Extra)|ConvertTo-Json -Compress;$ts=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds().ToString();$nonce=([guid]::NewGuid().ToString('N'));$canonical=$ts+"`n"+$nonce+"`n"+$ReleaseRoot+"`n"+$payload;$h=[Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($script:cfg.DEPLOYMENT_SECRET));try{$sig=([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($canonical)))).Replace('-','').ToLowerInvariant()}finally{$h.Dispose()};$headers=@{'X-OfficeApp-Timestamp'=$ts;'X-OfficeApp-Nonce'=$nonce;'X-OfficeApp-Root'=$ReleaseRoot;'X-OfficeApp-Signature'=$sig};return Invoke-RestMethod -Method Post -Uri $script:runnerUrl -Headers $headers -ContentType 'application/json' -Body $payload}
function FileOp([string]$Op,[string]$Source,[string]$Destination='',[string]$Metadata=''){$p=@{op=$Op;sourcefiles=$Source;doubledecode='1'};if($Destination){$p.destfiles=$Destination};if($Metadata){$p.metadata=$Metadata};Invoke-Api2 'fileop' $p|Out-Null}
function Entry-Name($Entry){foreach($property in @('file','name')){if($Entry.PSObject.Properties[$property]){return [string]$Entry.$property}};return ''}
function Write-Report([string]$Path){$lines=@('# OfficeApp production deployment report','',"- Git SHA: $($reportData.Commit)","- Package SHA256: $($reportData.PackageSHA)","- Package size: $($reportData.PackageSize)","- Production migration before: $($reportData.MigrationBefore)","- Production migration after: $($reportData.MigrationAfter)","- Migrations applied: $($reportData.MigrationsApplied -join ', ')","- Reference sync: $($reportData.ReferenceSync)","- Application backup: $($reportData.AppBackup)","- Database backup: $($reportData.DatabaseBackup)","- Staging path: $($reportData.StagingPath)","- Cutover UTC: $($reportData.Cutover)","- Health checks: $($reportData.Health -join '; ')","- Rollback status: $($reportData.Rollback)","- Final result: $($reportData.Result)");Set-Content $Path $lines -Encoding utf8}
$lock=Join-Path $root '.deploy/deploy-production.lock';New-Item -ItemType Directory (Split-Path $lock) -Force|Out-Null;if(Test-Path $lock){throw 'A local deployment lock exists. Remove it only after verifying no deployment is running.'};Set-Content $lock ([DateTime]::UtcNow.ToString('o')) -NoNewline
try{
 $head=Require-CleanRelease;$baseline=$ProductionMigration
 $existing=Join-Path $dist 'deployment-manifest.txt';$diagnosticDirty=$AllowDirty-or($script:trackedDirty-and-not$Execute);$skipBuild=$diagnosticDirty-and(Test-Path $existing);$release=& (Join-Path $PSScriptRoot 'prepare-cpanel-release.ps1') -ProductionMigration $baseline -SkipBuild:$skipBuild -AllowDirty:$diagnosticDirty;$releasePath=$release.ReleasePath;$reportPath=Join-Path $releasePath 'DEPLOYMENT_REPORT.md';$reportData.Commit=$head;$reportData.PackageSHA=$release.PackageSHA256;$reportData.PackageSize=$release.PackageSize;$reportData.MigrationBefore=if($baseline-ge 0){$baseline}else{'remote discovery required'};$reportData.MigrationAfter='not run';$reportData.AppBackup='not created';$reportData.DatabaseBackup='not created';$reportData.StagingPath='not created';$reportData.Cutover='not run'
 if($VerifyOnly){$reportData.Result='VERIFY PASS';Write-Report $reportPath;return}
 if(-not$Execute){$before=if($baseline-ge 0){$baseline.ToString('000')}else{'not queried (offline dry run)'};$target=([int]$release.LatestMigration).ToString('000');$missingText=if($baseline-ge 0){$release.MissingMigrations}else{'secure discovery occurs with -Execute'};Write-Host "Production before: $before";Write-Host "Release target: $target";Write-Host "Missing migrations: $missingText";$reportData.Result='DRY RUN PASS';$reportData.Health+=@('branch main','HEAD equals origin/main','package manifest equals HEAD','archive validation pass',"release target $target","missing migrations $missingText",'protected configs excluded','no remote mutation');Write-Report $reportPath;[pscustomobject]@{Mode='DRY RUN';Release=$releasePath;Commit=$head;SHA256=$release.PackageSHA256;Size=$release.PackageSize;ProductionBefore=$before;ReleaseTarget=$target;MissingMigrations=$missingText;Report=$reportPath};return}
 if($ProductionMigration-ge 0){throw '-ProductionMigration is an offline dry-run diagnostic override and cannot be used with -Execute.'}
 try{
 $script:cfg=Read-Env(Join-Path $root '.deploy/production.env');foreach($key in @('CPANEL_HOST','CPANEL_USERNAME','CPANEL_API_TOKEN','DEPLOYMENT_SECRET','PRODUCTION_URL','DEPLOYMENT_RUNNER_URL')){if(-not$cfg[$key]){throw "Missing deployment configuration: $key"}};if($cfg.DEPLOYMENT_SECRET.Length-lt 32){throw 'DEPLOYMENT_SECRET must contain at least 32 characters.'};$script:runnerUrl=$cfg.DEPLOYMENT_RUNNER_URL
 # This authenticated read is deliberately the first production operation.
 $status=Runner 'migration-status' '/home/passiontech/office_app';$repoVersions=@(Get-ChildItem (Join-Path $root 'database/migrations/mysql') -File -Filter '*.php'|Where-Object{$_.BaseName-match'^\d{3}_'}|Sort-Object BaseName|ForEach-Object{$_.BaseName.Substring(0,3)});$applied=@($status.versions|ForEach-Object{[string]$_});if($repoVersions.Count-eq 0){throw 'Release migration catalog is empty.'};if(($applied|Sort-Object -Unique).Count-ne$applied.Count){throw 'Production migration ledger contains duplicate versions.'};foreach($version in $applied){if($version-notmatch'^\d{3,20}$'){throw "Production migration ledger contains an invalid version: $version"}}
 if($applied.Count-gt$repoVersions.Count){throw 'Production is ahead of this release.'};for($i=0;$i-lt$applied.Count;$i++){if($applied[$i]-ne$repoVersions[$i]){if(-not($repoVersions-contains$applied[$i])){throw "Production is ahead of or divergent from this release at $($applied[$i])."};throw "Production migration ledger has a gap or inconsistent ordering at $($applied[$i])."}}
 $productionBefore=if($applied.Count){$applied[-1]}else{'none'};$releaseTarget=$repoVersions[-1];$missing=@($repoVersions|Select-Object -Skip $applied.Count);Write-Host "Production before: $productionBefore";Write-Host "Release target: $releaseTarget";Write-Host ('Missing migrations: '+$(if($missing.Count){$missing-join', '}else{'none'}));$reportData.MigrationBefore=$productionBefore;if($applied.Count-and[int]$productionBefore-gt[int]$releaseTarget){throw 'Production is ahead of this release.'}
 $homeEntries=@(Invoke-Uapi 'Fileman' 'list_files' @{dir='/home/passiontech'});Invoke-Api2 'getdir' @{}|Out-Null # read-only capability probes after secure discovery
 if($Rollback){if($Rollback-notmatch'^office_app_before_[0-9]{14}_[a-f0-9]{7}$'){throw 'Rollback must name an exact office_app_before_YYYYMMDDhhmmss_SHA backup.'};if(-not$Execute){throw 'Rollback execution requires -Execute.'};Invoke-Uapi 'Fileman' 'get_file_information' @{path="/home/passiontech/$Rollback"}|Out-Null;$rollbackStamp=[DateTime]::UtcNow.ToString('yyyyMMddHHmmss');FileOp 'rename' '/home/passiontech/office_app' "/home/passiontech/office_app_failed_rollback_$rollbackStamp";try{FileOp 'rename' "/home/passiontech/$Rollback" '/home/passiontech/office_app';$reportData.Rollback="restored $Rollback; database was not changed";$reportData.Result='ROLLBACK COMPLETE';return}catch{FileOp 'rename' "/home/passiontech/office_app_failed_rollback_$rollbackStamp" '/home/passiontech/office_app';throw}}
 $stamp=[DateTime]::UtcNow.ToString('yyyyMMddHHmmss');$short=$head.Substring(0,7);$stage="/home/passiontech/deployment-staging/$short-$stamp";$stageApp="$stage/office_app";$appBackup="office_app_before_${stamp}_$short";$remoteArchive="/home/passiontech/officeapp-cpanel-$short.tar.gz";$remoteLock='/home/passiontech/.officeapp-deployment.lock';$reportData.StagingPath=$stage;$reportData.AppBackup=$appBackup
 if($homeEntries|Where-Object{(Entry-Name $_)-eq'.officeapp-deployment.lock'}){throw 'A production deployment lock already exists. Inspect its timestamp and active processes before manual recovery.'}
 Invoke-Api2 'mkfile' @{path='/home/passiontech';name='.officeapp-deployment.lock';permissions='0600'}|Out-Null;if(-not($homeEntries|Where-Object{(Entry-Name $_)-eq'deployment-staging'})){Invoke-Api2 'mkdir' @{path='/home/passiontech';name='deployment-staging';permissions='0700'}|Out-Null};Invoke-Api2 'mkdir' @{path='/home/passiontech/deployment-staging';name="$short-$stamp";permissions='0700'}|Out-Null
 $package=Join-Path $releasePath 'officeapp-cpanel.tar.gz';Invoke-Uapi 'Fileman' 'upload_files' @{} @{dir='/home/passiontech';file=Get-Item $package}|Out-Null;FileOp 'rename' '/home/passiontech/officeapp-cpanel.tar.gz' "$stage/officeapp-cpanel.tar.gz";FileOp 'extract' "$stage/officeapp-cpanel.tar.gz";Invoke-Uapi 'Fileman' 'upload_files' @{} @{dir=$stage;file=Get-Item(Join-Path $releasePath 'deployment-manifest.txt')}|Out-Null
 Invoke-Uapi 'Fileman' 'get_file_information' @{path="$stageApp/vendor/autoload.php"}|Out-Null;foreach($protected in @('database.php','app.local.php')){try{Invoke-Uapi 'Fileman' 'get_file_information' @{path="$stageApp/config/$protected"}|Out-Null;throw 'Protected configuration entered the staged package.'}catch{if($_.Exception.Message-notmatch'failed'){throw}}}
 FileOp 'copy' '/home/passiontech/office_app/config/database.php' "$stageApp/config/database.php";FileOp 'copy' '/home/passiontech/office_app/config/app.local.php' "$stageApp/config/app.local.php";FileOp 'chmod' "$stageApp/config/database.php,$stageApp/config/app.local.php" '' '0600';FileOp 'trash' "$stageApp/storage";FileOp 'copy' '/home/passiontech/office_app/storage' $stageApp
 $db=Runner 'database-backup' '/home/passiontech/office_app' @{commit=$short};$reportData.DatabaseBackup=$db.backup.name;FileOp 'copy' '/home/passiontech/office_app' "/home/passiontech/$appBackup"
 if($missing.Count){$migrate=Runner 'migrate' $stageApp @{expected_before=$status.migration};$reportData.MigrationsApplied=@($migrate.result.applied);$reportData.MigrationAfter=$migrate.migration;if([int]$migrate.migration-ne[int]$releaseTarget){throw 'Migration ledger did not reach the release level.'}}else{$reportData.MigrationsApplied=@();$reportData.MigrationAfter=$releaseTarget};$sync=Runner 'sync-reference-data' $stageApp;$reportData.ReferenceSync='PASS'
 Runner 'release-health' $stageApp|Out-Null;FileOp 'rename' '/home/passiontech/office_app' "/home/passiontech/office_app_failed_$stamp";FileOp 'move' $stageApp '/home/passiontech/office_app';$reportData.Cutover=[DateTime]::UtcNow.ToString('o')
 try{$health=Runner 'release-health' '/home/passiontech/office_app';$web=Invoke-WebRequest -Uri $cfg.PRODUCTION_URL -MaximumRedirection 0 -UseBasicParsing;if($web.StatusCode-notin 200,302){throw "Homepage returned $($web.StatusCode)"};$login=Invoke-WebRequest -Uri ($cfg.PRODUCTION_URL.TrimEnd('/')+'/login') -MaximumRedirection 0 -UseBasicParsing;if($login.StatusCode-notin 200,302){throw "Login returned $($login.StatusCode)"};$policy=[string]$web.Headers['Permissions-Policy'];if($policy-notmatch'geolocation=\(self\)'){throw 'Permissions-Policy geolocation contract changed.'};$reportData.Health+=@('release-health PASS',"homepage $($web.StatusCode)","login $($login.StatusCode)",'Permissions-Policy PASS');$reportData.Result='DEPLOYED'}catch{$reportData.Rollback='application rollback attempted';FileOp 'rename' '/home/passiontech/office_app' "/home/passiontech/office_app_failed_health_$stamp";FileOp 'rename' "/home/passiontech/office_app_failed_$stamp" '/home/passiontech/office_app';$reportData.Rollback='application restored; database restore decision required because forward migrations ran';throw}
 } finally {if($Execute-and$script:cfg){try{FileOp 'trash' '/home/passiontech/.officeapp-deployment.lock'}catch{}};if($reportPath){Write-Report $reportPath}}
} finally {Remove-Item -LiteralPath $lock -Force -ErrorAction SilentlyContinue}
