[CmdletBinding()]
param([switch]$Execute,[switch]$VerifyOnly,[int]$ProductionMigration=-1,[switch]$AllowDirty)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path;$dist=Join-Path $root 'dist';$script:cfg=$null;$script:runnerUrl=$null;$script:trackedDirty=$false;$releaseId=$null;$reportPath=$null
$report=[ordered]@{Commit='not prepared';PackageSHA='not prepared';PackageSize='not prepared';Result='IN_PROGRESS';Rollback='not requested';Health=@();MigrationsApplied=@();ReferenceSync='not run';MigrationBefore='not queried';MigrationAfter='not run';AppBackup='not created';DatabaseBackup='not created';StagingPath='not created';Cutover='not run'}
function Read-Env([string]$Path){$v=@{};if(Test-Path $Path){foreach($line in Get-Content $Path){if($line.Trim()-eq''-or$line.TrimStart().StartsWith('#')){continue};$p=$line.Split('=',2);if($p.Count-eq2){$v[$p[0].Trim()]=$p[1].Trim()}}};return$v}
function Require-Release{$branch=(git -C $root branch --show-current).Trim();if($branch-ne'main'){throw 'HEAD must be on main.'};$head=(git -C $root rev-parse HEAD).Trim();git -C $root fetch origin main --quiet;if($LASTEXITCODE-ne0){throw 'Unable to verify origin/main.'};$origin=(git -C $root rev-parse origin/main).Trim();if($head-ne$origin){throw 'HEAD is not pushed to origin/main.'};$tracked=@(git -C $root status --porcelain --untracked-files=no);$script:trackedDirty=$tracked.Count-gt0;if($script:trackedDirty-and$Execute-and-not$AllowDirty){throw 'Tracked working-tree changes exist.'};return $head}
function Runner([string]$Action,[string]$ReleaseRoot='/home/passiontech/office_app',[hashtable]$Extra=@{}){$payload=(@{action=$Action}+$Extra)|ConvertTo-Json -Compress;$ts=[DateTimeOffset]::UtcNow.ToUnixTimeSeconds().ToString();$nonce=[guid]::NewGuid().ToString('N');$canonical=$ts+"`n"+$nonce+"`n"+$ReleaseRoot+"`n"+$payload;$h=New-Object Security.Cryptography.HMACSHA256(,[Text.Encoding]::UTF8.GetBytes($script:cfg.DEPLOYMENT_SECRET));try{$sig=([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($canonical)))).Replace('-','').ToLowerInvariant()}finally{$h.Dispose()};$headers=@{'X-OfficeApp-Timestamp'=$ts;'X-OfficeApp-Nonce'=$nonce;'X-OfficeApp-Root'=$ReleaseRoot;'X-OfficeApp-Signature'=$sig};$answer=Invoke-RestMethod -Method Post -Uri $script:runnerUrl -Headers $headers -ContentType 'application/json' -Body $payload;if(-not$answer.ok){throw "Runner action failed: $Action"};return $answer}
function Write-Report{$lines=@('# OfficeApp production deployment report','',"- Commit: $($report.Commit)","- Package SHA256: $($report.PackageSHA)","- Package size: $($report.PackageSize)","- Production migration before: $($report.MigrationBefore)","- Production migration after: $($report.MigrationAfter)","- Migrations applied: $($report.MigrationsApplied -join ', ')","- Reference sync: $($report.ReferenceSync)","- Database backup: $($report.DatabaseBackup)","- Application backup: $($report.AppBackup)","- Staging identifier: $($report.StagingPath)","- Cutover UTC: $($report.Cutover)","- Health checks: $($report.Health -join '; ')","- Rollback status: $($report.Rollback)","- Final result: $($report.Result)");if($reportPath){Set-Content $reportPath $lines -Encoding utf8}}
$localLock=Join-Path $root '.deploy/deploy-production.lock';New-Item -ItemType Directory (Split-Path $localLock) -Force|Out-Null;if(Test-Path $localLock){throw 'Local deployment lock exists.'};Set-Content $localLock ([DateTime]::UtcNow.ToString('o')) -NoNewline
try{
 $head=Require-Release;$diagnosticDirty=$AllowDirty-or($script:trackedDirty-and-not$Execute);$release=& (Join-Path $PSScriptRoot 'prepare-cpanel-release.ps1') -ProductionMigration $ProductionMigration -AllowDirty:$diagnosticDirty;$reportPath=Join-Path $release.ReleasePath 'DEPLOYMENT_REPORT.md';$report.Commit=$head;$report.PackageSHA=$release.PackageSHA256;$report.PackageSize=$release.PackageSize;$target=([int]$release.LatestMigration).ToString('000')
 if($VerifyOnly){$report.Result='VERIFY PASS';Write-Report;return}
 if(-not$Execute){$before=if($ProductionMigration-ge0){$ProductionMigration.ToString('000')}else{'not queried (offline dry run)'};$missing=if($ProductionMigration-ge0){if($release.MissingMigrations){$release.MissingMigrations}else{'none'}}else{'not calculated offline'};Write-Host "Production before: $before";Write-Host "Release target: $target";Write-Host "Missing migrations: $missing";$report.MigrationBefore=$before;$report.Result='DRY RUN PASS';$report.Health=@('manifest matches HEAD','archive validation PASS','no production request or write');Write-Report;[pscustomobject]@{Mode='DRY RUN';Commit=$head;SHA256=$release.PackageSHA256;Size=$release.PackageSize;ProductionBefore=$before;ReleaseTarget=$target;MissingMigrations=$missing;Report=$reportPath};return}
 if($ProductionMigration-ge0){throw '-ProductionMigration is an offline diagnostic only and cannot be used with -Execute.'}
 $script:cfg=Read-Env(Join-Path $root '.deploy/production.env');foreach($key in @('DEPLOYMENT_SECRET','DEPLOYMENT_RUNNER_URL','PRODUCTION_URL')){if(-not$cfg[$key]){throw "Missing deployment configuration: $key"}};if($cfg.DEPLOYMENT_SECRET.Length-lt32){throw 'DEPLOYMENT_SECRET must be at least 32 characters.'};$script:runnerUrl=$cfg.DEPLOYMENT_RUNNER_URL
 # First production operation: authenticated and read-only.
 $status=Runner 'migration-status';$repoVersions=@(Get-ChildItem (Join-Path $root 'database/migrations/mysql') -File -Filter '*.php'|Where-Object{$_.BaseName-match'^\d{3}_'}|Sort-Object BaseName|ForEach-Object{$_.BaseName.Substring(0,3)});$applied=@($status.versions|ForEach-Object{[string]$_});if(-not$repoVersions.Count){throw 'Release migration catalog is empty.'};if(($applied|Sort-Object -Unique).Count-ne$applied.Count){throw 'Production ledger has duplicate versions.'};foreach($v in $applied){if($v-notmatch'^\d{3,20}$'){throw "Invalid production migration: $v"}};if($applied.Count-gt$repoVersions.Count){throw 'Production is ahead of release.'};for($i=0;$i-lt$applied.Count;$i++){if($applied[$i]-ne$repoVersions[$i]){if(-not($repoVersions-contains$applied[$i])){throw "Production is ahead/divergent at $($applied[$i])."};throw "Production ledger gap/inconsistency at $($applied[$i])."}}
 $before=if($applied.Count){$applied[-1]}else{'none'};$missingVersions=@($repoVersions|Select-Object -Skip $applied.Count);Write-Host "Production before: $before";Write-Host "Release target: $target";Write-Host ('Missing migrations: '+$(if($missingVersions.Count){$missingVersions-join', '}else{'none'}));$report.MigrationBefore=$before
 # Second production operation: authenticated and read-only capability proof.
 $preflight=Runner 'preflight';$report.Health+='runner preflight PASS'
 $stamp=[DateTime]::UtcNow.ToString('yyyyMMddHHmmss');$releaseId=$head.Substring(0,7)+'-'+$stamp;$report.StagingPath=$releaseId;$package=Join-Path $release.ReleasePath 'officeapp-cpanel.tar.gz'
 Runner 'begin-release' '/home/passiontech/office_app' @{release_id=$releaseId;commit=$head;size=[int64]$release.PackageSize;sha256=$release.PackageSHA256}|Out-Null
 $stream=[IO.File]::OpenRead($package);try{$buffer=New-Object byte[] 262144;$index=0;while(($count=$stream.Read($buffer,0,$buffer.Length))-gt0){if($count-eq$buffer.Length){$chunk=$buffer}else{$chunk=New-Object byte[] $count;[Array]::Copy($buffer,$chunk,$count)};Runner 'upload-chunk' '/home/passiontech/office_app' @{release_id=$releaseId;index=$index;data=[Convert]::ToBase64String($chunk)}|Out-Null;$index++}}finally{$stream.Dispose()}
 $final=Runner 'finalize-release' '/home/passiontech/office_app' @{release_id=$releaseId};if([int64]$final.size-ne[int64]$release.PackageSize-or$final.sha256-ne$release.PackageSHA256){throw 'Remote staged package verification mismatch.'}
 $db=Runner 'database-backup' '/home/passiontech/office_app' @{release_id=$releaseId};$report.DatabaseBackup=$db.backup.name;$app=Runner 'application-backup' '/home/passiontech/office_app' @{release_id=$releaseId};$report.AppBackup=$app.backup.name
 $stageRoot="/home/passiontech/deployment-staging/$releaseId/office_app";if($missingVersions.Count){$m=Runner 'migrate' $stageRoot @{release_id=$releaseId};$report.MigrationsApplied=@($m.result.applied|ForEach-Object{[string]$_});$report.MigrationAfter=$m.migration;if(($report.MigrationsApplied-join',')-ne($missingVersions-join',')){throw 'Migration runner did not apply the exact calculated sequence.'};if($m.migration-ne$target){throw 'Migration target verification failed.'}}else{$report.MigrationAfter=$target;$report.MigrationsApplied=@()}
 $sync=Runner 'sync-reference-data' $stageRoot @{release_id=$releaseId};$report.ReferenceSync='PASS';Runner 'release-health' $stageRoot @{release_id=$releaseId}|Out-Null
 $cut=Runner 'cutover' '/home/passiontech/office_app' @{release_id=$releaseId};$report.Cutover=[DateTime]::UtcNow.ToString('o')
 try{Runner 'release-health' '/home/passiontech/office_app' @{release_id=$releaseId}|Out-Null;$home=Invoke-WebRequest -Uri $cfg.PRODUCTION_URL -UseBasicParsing;$login=Invoke-WebRequest -Uri ($cfg.PRODUCTION_URL.TrimEnd('/')+'/login') -UseBasicParsing;if($home.StatusCode-ne200-or$login.StatusCode-ne200){throw 'Production HTTP health failed.'};if(([string]$home.Headers['Permissions-Policy'])-notmatch'geolocation=\(self\)'){throw 'Permissions-Policy contract failed.'};$report.Health+=@('post-cutover release-health PASS','homepage 200','login 200','Permissions-Policy PASS');$report.Result='DEPLOYED'}catch{$primary=$_;$report.Rollback='application rollback attempted; database DDL not reversed';try{Runner 'rollback-application' '/home/passiontech/office_app' @{release_id=$releaseId}|Out-Null;$report.Rollback='application restored; explicit database restore decision required'}catch{$report.Rollback+='; rollback FAILED: '+$_.Exception.Message};throw $primary}
}catch{$report.Result='FAILED: '+$_.Exception.Message;throw}finally{if($Execute-and$releaseId-and$script:cfg){try{Runner 'cleanup' '/home/passiontech/office_app' @{release_id=$releaseId}|Out-Null}catch{Write-Warning('Deployment lock cleanup failed: '+$_.Exception.Message)}};Write-Report;Remove-Item -LiteralPath $localLock -Force -ErrorAction SilentlyContinue}
