[CmdletBinding()]
param([int]$ProductionMigration=-1,[switch]$SkipBuild,[switch]$AllowDirty)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;$root=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path
$head=(git -C $root rev-parse HEAD).Trim();$branch=(git -C $root branch --show-current).Trim();$status=@(git -C $root status --porcelain --untracked-files=no);if($status.Count-and-not$AllowDirty){throw 'Tracked working-tree changes exist. Commit the intended release before packaging.'}
if(-not$SkipBuild){& (Join-Path $PSScriptRoot 'build-cpanel-package.ps1') | Out-Null}
$sourcePackage=Join-Path $root 'dist/officeapp-cpanel.tar.gz';$sourceManifest=Join-Path $root 'dist/deployment-manifest.txt';if(-not(Test-Path $sourcePackage)-or-not(Test-Path $sourceManifest)){throw 'Canonical cPanel package artifacts are absent.'}
$builtManifest=Get-Content -Raw $sourceManifest;if($builtManifest-notmatch"Git commit SHA:\s*$head"){throw 'Package manifest commit does not equal HEAD.'}
$short=$head.Substring(0,7);$release=Join-Path $root "dist/releases/$short";New-Item -ItemType Directory -Path $release -Force|Out-Null;Copy-Item $sourcePackage (Join-Path $release 'officeapp-cpanel.tar.gz') -Force
$hash=(Get-FileHash $sourcePackage -Algorithm SHA256).Hash.ToLowerInvariant();$size=(Get-Item $sourcePackage).Length;$migrationFiles=@(Get-ChildItem (Join-Path $root 'database/migrations/mysql') -File -Filter '*.php'|Where-Object{$_.BaseName-match'^\d{3}_'}|Sort-Object BaseName);$versions=@($migrationFiles|ForEach-Object{[int]$_.BaseName.Substring(0,3)});if($versions.Count-eq 0-or($versions|Sort-Object -Unique).Count-ne$versions.Count){throw 'Migration catalog is empty or has duplicate versions.'};$latest=($versions|Measure-Object -Maximum).Maximum
$missing=@();if($ProductionMigration-ge 0){$missing=@($versions|Where-Object{$_-gt$ProductionMigration})};$seedFiles=@(Get-ChildItem (Join-Path $root 'database/seeds') -File -Filter '*.sql'|Sort-Object Name);$changedSeeds=@()
if($ProductionMigration-ge 0){$baselineFile=$migrationFiles|Where-Object{[int]$_.BaseName.Substring(0,3)-eq$ProductionMigration}|Select-Object -First 1;if($baselineFile){$relative=$baselineFile.FullName.Substring($root.Length+1).Replace('\','/');$baselineCommit=(git -C $root log --diff-filter=A -n 1 --format=%H -- $relative).Trim();if($baselineCommit){$changed=@(git -C $root diff --name-only "$baselineCommit..HEAD" -- database/seeds);$changedSeeds=@($seedFiles|Where-Object{$changed-contains('database/seeds/'+$_.Name)})}}}
$timestamp=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')
$manifest=@('OfficeApp ERP Automated Deployment Manifest',"Git commit SHA: $head","Branch: $branch","Build UTC: $timestamp","Package SHA256: $hash","Package size bytes: $size",'PHP requirement: 8.1 / ea-php81',"Latest MySQL migration: $latest",("Production migration baseline: "+$(if($ProductionMigration-ge 0){$ProductionMigration}else{'discover remotely'})),('Missing migrations: '+$(if($missing.Count){($missing|ForEach-Object{$_.ToString('000')})-join', '}else{'none/discover remotely'})),'Reference data present: true',('Reference files: '+(($seedFiles|ForEach-Object{$_.Name})-join', ')),('Reference files changed since baseline migration commit: '+$(if($changedSeeds.Count){($changedSeeds|ForEach-Object{$_.Name})-join', '}else{'none/discover remotely'})),'Protected exclusions: config/database.php, config/app.local.php','Expected archive root: office_app/','Production app path: /home/passiontech/office_app','Production public bridge: /home/passiontech/public_html/erp.passiontechnologiesplc.com','Database: passiontech_officeapp','Rollback: retain matching application and verified database backups; never reverse DDL ad hoc.')
Set-Content (Join-Path $release 'deployment-manifest.txt') $manifest -Encoding utf8;Set-Content (Join-Path $release 'SHA256SUMS.txt') "$hash  officeapp-cpanel.tar.gz" -Encoding ascii
$missingText=$(if($missing.Count){($missing|ForEach-Object{$_.ToString('000')})-join', '}else{'discover remotely'});$checklist=@("# Release checklist - $short",'',"- [ ] HEAD `$head` is reviewed and pushed to `origin/main`.",'- [ ] Local focused and integration checks pass.','- [ ] cPanel API capability preflight passes.','- [ ] Database and application backups are verified.','- [ ] Package upload, staging root, protected config 0600 and preserved storage are verified.',"- [ ] Only missing migrations run: $missingText",'- [ ] Reference synchronization and migration ledger verification pass.','- [ ] Atomic cutover leaves the public bridge unchanged.','- [ ] Login/sign-out, release, DB, storage and read-only module health checks pass.','- [ ] `Permissions-Policy` remains `geolocation=(self)`.','- [ ] Rollback status and backup identifiers are recorded.');Set-Content (Join-Path $release 'RELEASE_CHECKLIST.md') $checklist -Encoding utf8
$dbNote=@('# Database upgrade','','No static `database-upgrade.sql` is generated. Migrations are PHP definitions with callable database preflights, checksum compatibility rules and resumable step-ledger behavior. Flattening them into SQL would bypass those safety contracts. The authenticated deployment runner invokes the same MigrationRunner and ReferenceDataSynchronizer classes and verifies the ledger. This artifact fails closed rather than inventing SQL.','',"Release latest migration: $latest","Caller baseline: $ProductionMigration","Expected missing range: $missingText");Set-Content (Join-Path $release 'DATABASE_UPGRADE.md') $dbNote -Encoding utf8
& (Join-Path $PSScriptRoot 'verify-cpanel-release.ps1') -ReleasePath $release|Out-Null
[pscustomobject]@{ReleasePath=$release;Commit=$head;PackageSHA256=$hash;PackageSize=$size;LatestMigration=$latest;MissingMigrations=($missing-join',');ChangedReferenceFiles=(($changedSeeds|ForEach-Object{$_.Name})-join',');DatabaseArtifact='DATABASE_UPGRADE.md (runner required)'}
