<?php

declare(strict_types=1);

return [
    'version' => '010',
    'description' =>
        'Create identity, access and company tenancy tables',
    'statements' => [
        <<<'SQL'
CREATE TABLE roles (
    role_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(80 CHAR) NOT NULL,
    code VARCHAR2(80 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),
    is_system NUMBER(1) DEFAULT 0 NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uq_roles_name UNIQUE (name),
    CONSTRAINT uq_roles_code UNIQUE (code),
    CONSTRAINT ck_roles_system
        CHECK (is_system IN (0, 1)),
    CONSTRAINT ck_roles_active
        CHECK (active IN (0, 1))
)
SQL,
        <<<'SQL'
CREATE TABLE permissions (
    permission_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(120 CHAR) NOT NULL,
    code VARCHAR2(120 CHAR) NOT NULL,
    module VARCHAR2(80 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_permissions
        PRIMARY KEY (permission_id),
    CONSTRAINT uq_permissions_code UNIQUE (code),
    CONSTRAINT ck_permissions_active
        CHECK (active IN (0, 1))
)
SQL,
        'CREATE INDEX ix_permissions_module'
            . ' ON permissions (module)',
        <<<'SQL'
CREATE TABLE users (
    user_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username VARCHAR2(80 CHAR) NOT NULL,
    email VARCHAR2(190 CHAR) NOT NULL,
    password_hash VARCHAR2(255 CHAR) NOT NULL,
    display_name VARCHAR2(150 CHAR) NOT NULL,
    is_platform_admin NUMBER(1) DEFAULT 0 NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    must_change_password NUMBER(1) DEFAULT 1 NOT NULL,
    failed_login_count NUMBER(5) DEFAULT 0 NOT NULL,
    locked_until TIMESTAMP(6),
    last_login_at TIMESTAMP(6),
    password_changed_at TIMESTAMP(6),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_platform
        CHECK (is_platform_admin IN (0, 1)),
    CONSTRAINT ck_users_active
        CHECK (active IN (0, 1)),
    CONSTRAINT ck_users_change_password
        CHECK (must_change_password IN (0, 1)),
    CONSTRAINT ck_users_failed_login
        CHECK (failed_login_count >= 0)
)
SQL,
        'CREATE INDEX ix_users_active'
            . ' ON users (active)',
        'CREATE INDEX ix_users_deleted'
            . ' ON users (deleted_at)',
        'CREATE INDEX ix_users_platform'
            . ' ON users ('
            . 'is_platform_admin, active, deleted_at'
            . ')',
        <<<'SQL'
CREATE TABLE companies (
    company_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code VARCHAR2(50 CHAR) NOT NULL,
    name VARCHAR2(150 CHAR) NOT NULL,
    legal_name VARCHAR2(190 CHAR),
    contact_email VARCHAR2(190 CHAR),
    contact_phone VARCHAR2(40 CHAR),
    country_code CHAR(2 CHAR) DEFAULT 'KE' NOT NULL,
    default_currency CHAR(3 CHAR)
        DEFAULT 'KES' NOT NULL,
    timezone VARCHAR2(80 CHAR)
        DEFAULT 'Africa/Nairobi' NOT NULL,
    subscription_status VARCHAR2(30 CHAR)
        DEFAULT 'active' NOT NULL,
    subscription_expires_at TIMESTAMP(6),
    brand_primary_color CHAR(7 CHAR)
        DEFAULT '#2563EB' NOT NULL,
    approval_status VARCHAR2(30 CHAR)
        DEFAULT 'pending' NOT NULL,
    approved_at TIMESTAMP(6),
    approved_by NUMBER(19),
    owner_user_id NUMBER(19),
    active NUMBER(1) DEFAULT 1 NOT NULL,
    provisioned_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_companies PRIMARY KEY (company_id),
    CONSTRAINT uq_companies_code UNIQUE (code),
    CONSTRAINT ck_companies_active
        CHECK (active IN (0, 1)),
    CONSTRAINT fk_companies_approved
        FOREIGN KEY (approved_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_companies_owner
        FOREIGN KEY (owner_user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_companies_provisioned
        FOREIGN KEY (provisioned_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_companies_active'
            . ' ON companies (active, deleted_at)',
        'CREATE INDEX ix_companies_subscription'
            . ' ON companies ('
            . 'subscription_status, '
            . 'subscription_expires_at, '
            . 'active, deleted_at'
            . ')',
        'CREATE INDEX ix_companies_approval'
            . ' ON companies ('
            . 'approval_status, active, deleted_at'
            . ')',
        'CREATE INDEX ix_companies_owner'
            . ' ON companies (owner_user_id)',
        <<<'SQL'
CREATE TABLE user_roles (
    user_id NUMBER(19) NOT NULL,
    role_id NUMBER(10) NOT NULL,
    assigned_by NUMBER(19),
    assigned_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_assigner
        FOREIGN KEY (assigned_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_user_roles_role'
            . ' ON user_roles (role_id)',
        'CREATE INDEX ix_user_roles_assigner'
            . ' ON user_roles (assigned_by)',
        <<<'SQL'
CREATE TABLE role_permissions (
    role_id NUMBER(10) NOT NULL,
    permission_id NUMBER(10) NOT NULL,
    granted_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_role_permissions
        PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_perm
        FOREIGN KEY (permission_id)
        REFERENCES permissions (permission_id)
        ON DELETE CASCADE
)
SQL,
        'CREATE INDEX ix_role_permissions_perm'
            . ' ON role_permissions (permission_id)',
        <<<'SQL'
CREATE TABLE company_users (
    company_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    is_default NUMBER(1) DEFAULT 0 NOT NULL,
    assigned_by NUMBER(19),
    joined_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_company_users
        PRIMARY KEY (company_id, user_id),
    CONSTRAINT ck_company_users_active
        CHECK (active IN (0, 1)),
    CONSTRAINT ck_company_users_default
        CHECK (is_default IN (0, 1)),
    CONSTRAINT fk_company_users_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_users_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_users_assigner
        FOREIGN KEY (assigned_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_company_users_user'
            . ' ON company_users ('
            . 'user_id, active, is_default'
            . ')',
        'CREATE INDEX ix_company_users_company'
            . ' ON company_users (company_id, active)',
        'CREATE INDEX ix_company_users_assigner'
            . ' ON company_users (assigned_by)',
        <<<'SQL'
CREATE TABLE company_user_roles (
    company_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    role_id NUMBER(10) NOT NULL,
    assigned_by NUMBER(19),
    assigned_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_company_user_roles
        PRIMARY KEY (company_id, user_id, role_id),
    CONSTRAINT fk_company_user_roles_member
        FOREIGN KEY (company_id, user_id)
        REFERENCES company_users (company_id, user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_user_roles_by
        FOREIGN KEY (assigned_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_company_user_roles_role'
            . ' ON company_user_roles ('
            . 'company_id, role_id, user_id'
            . ')',
        'CREATE INDEX ix_company_user_roles_by'
            . ' ON company_user_roles (assigned_by)',
        <<<'SQL'
CREATE TABLE company_role_permissions (
    company_id NUMBER(19) NOT NULL,
    role_id NUMBER(10) NOT NULL,
    permission_id NUMBER(10) NOT NULL,
    granted_by NUMBER(19),
    granted_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_company_role_perms
        PRIMARY KEY (
            company_id,
            role_id,
            permission_id
        ),
    CONSTRAINT fk_company_role_perm_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_role_perm_role
        FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_role_perm_perm
        FOREIGN KEY (permission_id)
        REFERENCES permissions (permission_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_role_perm_by
        FOREIGN KEY (granted_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_company_role_perm_find'
            . ' ON company_role_permissions ('
            . 'company_id, permission_id, role_id'
            . ')',
        'CREATE INDEX ix_company_role_perm_by'
            . ' ON company_role_permissions (granted_by)',
    ],
];
