<?php

declare(strict_types=1);

return [
    'version' => '020',
    'description' =>
        'Create modular product catalog and company entitlements',
    'statements' => [
        <<<'SQL'
CREATE TABLE erp_modules (
    module_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code VARCHAR2(50 CHAR) NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    navigation_label VARCHAR2(100 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR) NOT NULL,
    route_path VARCHAR2(120 CHAR) NOT NULL,
    permission_namespace VARCHAR2(80 CHAR) NOT NULL,
    icon_text VARCHAR2(10 CHAR) NOT NULL,
    sort_order NUMBER(5) DEFAULT 100 NOT NULL,
    available NUMBER(1) DEFAULT 0 NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_erp_modules PRIMARY KEY (module_id),
    CONSTRAINT uq_erp_modules_code UNIQUE (code),
    CONSTRAINT uq_erp_modules_route UNIQUE (route_path),
    CONSTRAINT ck_erp_modules_available
        CHECK (available IN (0, 1)),
    CONSTRAINT ck_erp_modules_active
        CHECK (active IN (0, 1)),
    CONSTRAINT ck_erp_modules_sort
        CHECK (sort_order >= 0)
)
SQL,
        'CREATE INDEX ix_erp_modules_catalog'
            . ' ON erp_modules ('
            . 'active, available, sort_order'
            . ')',
        <<<'SQL'
CREATE TABLE company_modules (
    company_id NUMBER(19) NOT NULL,
    module_id NUMBER(10) NOT NULL,
    enabled NUMBER(1) DEFAULT 0 NOT NULL,
    license_status VARCHAR2(30 CHAR)
        DEFAULT 'not_licensed' NOT NULL,
    licensed_at TIMESTAMP(6),
    expires_at TIMESTAMP(6),
    settings_json CLOB,
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_company_modules
        PRIMARY KEY (company_id, module_id),
    CONSTRAINT ck_company_modules_enabled
        CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_company_modules_json
        CHECK (
            settings_json IS JSON
            OR settings_json IS NULL
        ),
    CONSTRAINT fk_company_modules_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_modules_module
        FOREIGN KEY (module_id)
        REFERENCES erp_modules (module_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_company_modules_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_company_modules_ent'
            . ' ON company_modules ('
            . 'company_id, enabled, '
            . 'license_status, expires_at'
            . ')',
        'CREATE INDEX ix_company_modules_user'
            . ' ON company_modules (updated_by)',
    ],
];
