<?php

declare(strict_types=1);

return [
    'version' => '030',
    'description' =>
        'Create tenant-scoped human resources tables',
    'statements' => [
        <<<'SQL'
CREATE TABLE hr_departments (
    department_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    code VARCHAR2(30 CHAR) NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_hr_departments
        PRIMARY KEY (department_id),
    CONSTRAINT uq_hr_dept_company_code
        UNIQUE (company_id, code),
    CONSTRAINT uq_hr_dept_company_name
        UNIQUE (company_id, name),
    CONSTRAINT ck_hr_departments_active
        CHECK (active IN (0, 1)),
    CONSTRAINT fk_hr_dept_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_hr_dept_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_hr_dept_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_hr_dept_active'
            . ' ON hr_departments (active, deleted_at)',
        'CREATE INDEX ix_hr_dept_company'
            . ' ON hr_departments ('
            . 'company_id, active, deleted_at'
            . ')',
        'CREATE INDEX ix_hr_dept_creator'
            . ' ON hr_departments (created_by)',
        'CREATE INDEX ix_hr_dept_updater'
            . ' ON hr_departments (updated_by)',
        <<<'SQL'
CREATE TABLE hr_employees (
    employee_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    employee_number VARCHAR2(50 CHAR) NOT NULL,
    user_id NUMBER(19),
    first_name VARCHAR2(80 CHAR) NOT NULL,
    middle_name VARCHAR2(80 CHAR),
    last_name VARCHAR2(80 CHAR) NOT NULL,
    preferred_name VARCHAR2(80 CHAR),
    work_email VARCHAR2(190 CHAR) NOT NULL,
    work_phone VARCHAR2(40 CHAR),
    department_id NUMBER(10),
    job_title VARCHAR2(120 CHAR) NOT NULL,
    employment_type VARCHAR2(30 CHAR) NOT NULL,
    employment_status VARCHAR2(30 CHAR)
        DEFAULT 'active' NOT NULL,
    hire_date DATE NOT NULL,
    termination_date DATE,
    manager_employee_id NUMBER(19),
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_hr_employees
        PRIMARY KEY (employee_id),
    CONSTRAINT uq_hr_emp_company_number
        UNIQUE (company_id, employee_number),
    CONSTRAINT uq_hr_emp_company_user
        UNIQUE (company_id, user_id),
    CONSTRAINT uq_hr_emp_company_email
        UNIQUE (company_id, work_email),
    CONSTRAINT fk_hr_emp_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_hr_emp_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_hr_emp_department
        FOREIGN KEY (department_id)
        REFERENCES hr_departments (department_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_hr_emp_manager
        FOREIGN KEY (manager_employee_id)
        REFERENCES hr_employees (employee_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_hr_emp_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_hr_emp_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_hr_emp_status'
            . ' ON hr_employees ('
            . 'employment_status, deleted_at'
            . ')',
        'CREATE INDEX ix_hr_emp_department'
            . ' ON hr_employees ('
            . 'department_id, employment_status'
            . ')',
        'CREATE INDEX ix_hr_emp_name'
            . ' ON hr_employees (last_name, first_name)',
        'CREATE INDEX ix_hr_emp_manager'
            . ' ON hr_employees (manager_employee_id)',
        'CREATE INDEX ix_hr_emp_company_status'
            . ' ON hr_employees ('
            . 'company_id, employment_status, deleted_at'
            . ')',
        'CREATE INDEX ix_hr_emp_company_dept'
            . ' ON hr_employees ('
            . 'company_id, department_id, employment_status'
            . ')',
        'CREATE INDEX ix_hr_emp_creator'
            . ' ON hr_employees (created_by)',
        'CREATE INDEX ix_hr_emp_updater'
            . ' ON hr_employees (updated_by)',
    ],
];
