<?php

declare(strict_types=1);

return [
    'version' => '040',
    'description' =>
        'Create tenant-scoped finance tables',
    'statements' => [
        <<<'SQL'
CREATE TABLE finance_expense_categories (
    category_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    code VARCHAR2(50 CHAR) NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_fin_exp_categories
        PRIMARY KEY (category_id),
    CONSTRAINT uq_fin_cat_company_code
        UNIQUE (company_id, code),
    CONSTRAINT uq_fin_cat_company_name
        UNIQUE (company_id, name),
    CONSTRAINT ck_fin_categories_active
        CHECK (active IN (0, 1)),
    CONSTRAINT fk_fin_cat_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_fin_cat_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_fin_cat_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_fin_cat_active'
            . ' ON finance_expense_categories ('
            . 'active, deleted_at'
            . ')',
        'CREATE INDEX ix_fin_cat_company'
            . ' ON finance_expense_categories ('
            . 'company_id, active, deleted_at'
            . ')',
        'CREATE INDEX ix_fin_cat_creator'
            . ' ON finance_expense_categories (created_by)',
        'CREATE INDEX ix_fin_cat_updater'
            . ' ON finance_expense_categories (updated_by)',
        <<<'SQL'
CREATE TABLE finance_expense_requests (
    expense_request_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    request_number VARCHAR2(50 CHAR) NOT NULL,
    requested_by_employee_id NUMBER(19) NOT NULL,
    category_id NUMBER(10),
    title VARCHAR2(150 CHAR) NOT NULL,
    description CLOB,
    amount NUMBER(15, 2) NOT NULL,
    currency CHAR(3 CHAR) DEFAULT 'KES' NOT NULL,
    expense_date DATE NOT NULL,
    status VARCHAR2(30 CHAR) DEFAULT 'draft' NOT NULL,
    submitted_at TIMESTAMP(6),
    reviewed_by NUMBER(19),
    reviewed_at TIMESTAMP(6),
    review_notes VARCHAR2(500 CHAR),
    paid_at TIMESTAMP(6),
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_fin_exp_requests
        PRIMARY KEY (expense_request_id),
    CONSTRAINT uq_fin_req_company_number
        UNIQUE (company_id, request_number),
    CONSTRAINT ck_fin_request_amount
        CHECK (amount >= 0),
    CONSTRAINT fk_fin_req_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_fin_req_employee
        FOREIGN KEY (requested_by_employee_id)
        REFERENCES hr_employees (employee_id),
    CONSTRAINT fk_fin_req_category
        FOREIGN KEY (category_id)
        REFERENCES finance_expense_categories (category_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_fin_req_reviewer
        FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_fin_req_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_fin_req_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_fin_req_status'
            . ' ON finance_expense_requests ('
            . 'status, deleted_at'
            . ')',
        'CREATE INDEX ix_fin_req_date'
            . ' ON finance_expense_requests ('
            . 'expense_date, status'
            . ')',
        'CREATE INDEX ix_fin_req_employee'
            . ' ON finance_expense_requests ('
            . 'requested_by_employee_id, status'
            . ')',
        'CREATE INDEX ix_fin_req_category'
            . ' ON finance_expense_requests ('
            . 'category_id, status'
            . ')',
        'CREATE INDEX ix_fin_req_company_status'
            . ' ON finance_expense_requests ('
            . 'company_id, status, deleted_at'
            . ')',
        'CREATE INDEX ix_fin_req_company_date'
            . ' ON finance_expense_requests ('
            . 'company_id, expense_date, status'
            . ')',
        'CREATE INDEX ix_fin_req_creator'
            . ' ON finance_expense_requests (created_by)',
        'CREATE INDEX ix_fin_req_reviewer'
            . ' ON finance_expense_requests (reviewed_by)',
        'CREATE INDEX ix_fin_req_updater'
            . ' ON finance_expense_requests (updated_by)',
    ],
];
