<?php

declare(strict_types=1);

return [
    'version' => '050',
    'description' =>
        'Create tenant-aware login and audit history tables',
    'statements' => [
        <<<'SQL'
CREATE TABLE login_attempts (
    login_attempt_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19),
    username_entered VARCHAR2(190 CHAR),
    user_id NUMBER(19),
    ip_address VARCHAR2(45 CHAR) NOT NULL,
    user_agent VARCHAR2(500 CHAR),
    successful NUMBER(1) DEFAULT 0 NOT NULL,
    failure_reason VARCHAR2(100 CHAR),
    attempted_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_login_attempts
        PRIMARY KEY (login_attempt_id),
    CONSTRAINT ck_login_attempt_success
        CHECK (successful IN (0, 1)),
    CONSTRAINT fk_login_attempt_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_login_attempt_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_login_ip_time'
            . ' ON login_attempts ('
            . 'ip_address, attempted_at'
            . ')',
        'CREATE INDEX ix_login_user_time'
            . ' ON login_attempts ('
            . 'user_id, attempted_at'
            . ')',
        'CREATE INDEX ix_login_company_time'
            . ' ON login_attempts ('
            . 'company_id, attempted_at'
            . ')',
        'CREATE INDEX ix_login_company_user'
            . ' ON login_attempts ('
            . 'company_id, user_id, attempted_at'
            . ')',
        <<<'SQL'
CREATE TABLE audit_logs (
    audit_log_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19),
    user_id NUMBER(19),
    action VARCHAR2(50 CHAR) NOT NULL,
    module VARCHAR2(80 CHAR) NOT NULL,
    table_name VARCHAR2(100 CHAR),
    record_id VARCHAR2(100 CHAR),
    old_values CLOB,
    new_values CLOB,
    ip_address VARCHAR2(45 CHAR),
    user_agent VARCHAR2(500 CHAR),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_log_id),
    CONSTRAINT ck_audit_old_json
        CHECK (
            old_values IS JSON
            OR old_values IS NULL
        ),
    CONSTRAINT ck_audit_new_json
        CHECK (
            new_values IS JSON
            OR new_values IS NULL
        ),
    CONSTRAINT fk_audit_logs_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_audit_user_time'
            . ' ON audit_logs (user_id, created_at)',
        'CREATE INDEX ix_audit_module_time'
            . ' ON audit_logs (module, created_at)',
        'CREATE INDEX ix_audit_record'
            . ' ON audit_logs (table_name, record_id)',
        'CREATE INDEX ix_audit_company_time'
            . ' ON audit_logs (company_id, created_at)',
        'CREATE INDEX ix_audit_company_record'
            . ' ON audit_logs ('
            . 'company_id, table_name, record_id'
            . ')',
    ],
];
