<?php

declare(strict_types=1);

return [
    'version' => '080',
    'description' =>
        'Create tenant-scoped organization job titles',
    'statements' => [
        <<<'SQL'
CREATE TABLE organization_job_titles (
    job_title_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    code VARCHAR2(30 CHAR) NOT NULL,
    name VARCHAR2(120 CHAR) NOT NULL,
    job_family VARCHAR2(100 CHAR),
    grade_level VARCHAR2(40 CHAR),
    description VARCHAR2(500 CHAR),
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_org_job_titles
        PRIMARY KEY (job_title_id),
    CONSTRAINT uq_org_job_titles_company_code
        UNIQUE (company_id, code),
    CONSTRAINT uq_org_job_titles_company_name
        UNIQUE (company_id, name),
    CONSTRAINT ck_org_job_titles_active
        CHECK (active IN (0, 1)),
    CONSTRAINT fk_org_job_titles_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_org_job_titles_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_org_job_titles_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_org_job_titles_comp_active'
            . ' ON organization_job_titles ('
            . 'company_id, active, deleted_at'
            . ')',
        'CREATE INDEX ix_org_job_titles_comp_family'
            . ' ON organization_job_titles ('
            . 'company_id, job_family, active, deleted_at'
            . ')',
        <<<'SQL'
MERGE INTO permissions target
USING (
    SELECT
        'View Company Job Titles' AS name,
        'organization.job_titles.view' AS code,
        'organization' AS module,
        'View company job-title master data'
            AS description
    FROM dual
    UNION ALL
    SELECT
        'Manage Company Job Titles',
        'organization.job_titles.manage',
        'organization',
        'Create and update company job-title master data'
    FROM dual
) source
ON (target.code = source.code)
WHEN MATCHED THEN UPDATE SET
    target.name = source.name,
    target.module = source.module,
    target.description = source.description,
    target.active = 1
WHEN NOT MATCHED THEN INSERT (
    name,
    code,
    module,
    description,
    active
) VALUES (
    source.name,
    source.code,
    source.module,
    source.description,
    1
)
SQL,
        <<<'SQL'
MERGE INTO role_permissions target
USING (
    SELECT
        roles.role_id,
        permissions.permission_id
    FROM roles
    CROSS JOIN permissions
    WHERE (
        roles.code IN (
            'system_administrator',
            'company_owner'
        )
        AND permissions.code IN (
            'organization.job_titles.view',
            'organization.job_titles.manage'
        )
    ) OR (
        roles.code = 'executive_viewer'
        AND permissions.code =
            'organization.job_titles.view'
    )
) source
ON (
    target.role_id = source.role_id
    AND target.permission_id =
        source.permission_id
)
WHEN NOT MATCHED THEN INSERT (
    role_id,
    permission_id
) VALUES (
    source.role_id,
    source.permission_id
)
SQL,
        <<<'SQL'
MERGE INTO company_role_permissions target
USING (
    SELECT
        companies.company_id,
        grants.role_id,
        grants.permission_id,
        companies.provisioned_by AS granted_by
    FROM companies
    CROSS JOIN role_permissions grants
    INNER JOIN roles
        ON roles.role_id = grants.role_id
    INNER JOIN permissions
        ON permissions.permission_id =
            grants.permission_id
    WHERE companies.deleted_at IS NULL
      AND roles.code IN (
            'system_administrator',
            'company_owner',
            'executive_viewer'
      )
      AND permissions.code IN (
            'organization.job_titles.view',
            'organization.job_titles.manage'
      )
) source
ON (
    target.company_id = source.company_id
    AND target.role_id = source.role_id
    AND target.permission_id =
        source.permission_id
)
WHEN NOT MATCHED THEN INSERT (
    company_id,
    role_id,
    permission_id,
    granted_by
) VALUES (
    source.company_id,
    source.role_id,
    source.permission_id,
    source.granted_by
)
SQL,
    ],
];
