<?php

declare(strict_types=1);

return [
    'version' => '100',
    'description' =>
        'Create tenant-scoped organization positions',
    'statements' => [
        'ALTER TABLE organization_branches'
            . ' ADD CONSTRAINT uq_org_branches_company_id'
            . ' UNIQUE (company_id, branch_id)',
        'ALTER TABLE organization_job_titles'
            . ' ADD CONSTRAINT uq_org_job_titles_company_id'
            . ' UNIQUE (company_id, job_title_id)',
        <<<'SQL'
CREATE TABLE organization_positions (
    position_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    code VARCHAR2(40 CHAR) NOT NULL,
    name VARCHAR2(140 CHAR) NOT NULL,
    branch_id NUMBER(19),
    department_id NUMBER(10) NOT NULL,
    job_title_id NUMBER(19) NOT NULL,
    approved_headcount NUMBER(10) DEFAULT 1 NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'planned' NOT NULL,
    description VARCHAR2(500 CHAR),
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_org_positions
        PRIMARY KEY (position_id),
    CONSTRAINT uq_org_positions_company_code
        UNIQUE (company_id, code),
    CONSTRAINT ck_org_positions_headcount
        CHECK (approved_headcount BETWEEN 1 AND 10000),
    CONSTRAINT ck_org_positions_status
        CHECK (
            status IN (
                'planned',
                'open',
                'frozen',
                'closed'
            )
        ),
    CONSTRAINT fk_org_positions_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_org_positions_branch
        FOREIGN KEY (company_id, branch_id)
        REFERENCES organization_branches (
            company_id,
            branch_id
        ),
    CONSTRAINT fk_org_positions_department
        FOREIGN KEY (company_id, department_id)
        REFERENCES hr_departments (
            company_id,
            department_id
        ),
    CONSTRAINT fk_org_positions_job_title
        FOREIGN KEY (company_id, job_title_id)
        REFERENCES organization_job_titles (
            company_id,
            job_title_id
        ),
    CONSTRAINT fk_org_positions_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_org_positions_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_org_positions_comp_status'
            . ' ON organization_positions ('
            . 'company_id, status, deleted_at'
            . ')',
        'CREATE INDEX ix_org_positions_comp_dept'
            . ' ON organization_positions ('
            . 'company_id, department_id, status, deleted_at'
            . ')',
        'CREATE INDEX ix_org_positions_comp_branch'
            . ' ON organization_positions ('
            . 'company_id, branch_id, status, deleted_at'
            . ')',
        'CREATE INDEX ix_org_positions_comp_title'
            . ' ON organization_positions ('
            . 'company_id, job_title_id, status, deleted_at'
            . ')',
        <<<'SQL'
MERGE INTO permissions target
USING (
    SELECT
        'View Company Positions' AS name,
        'organization.positions.view' AS code,
        'organization' AS module,
        'View company positions and approved headcount'
            AS description
    FROM dual
    UNION ALL
    SELECT
        'Manage Company Positions',
        'organization.positions.manage',
        'organization',
        'Create and update company positions and approved headcount'
    FROM dual
) source
ON (target.code = source.code)
WHEN MATCHED THEN UPDATE SET
    target.name = source.name,
    target.module = source.module,
    target.description = source.description,
    target.active = 1
WHEN NOT MATCHED THEN INSERT (
    name,
    code,
    module,
    description,
    active
) VALUES (
    source.name,
    source.code,
    source.module,
    source.description,
    1
)
SQL,
        <<<'SQL'
MERGE INTO role_permissions target
USING (
    SELECT
        roles.role_id,
        permissions.permission_id
    FROM roles
    CROSS JOIN permissions
    WHERE (
        roles.code IN (
            'system_administrator',
            'company_owner',
            'hr_administrator'
        )
        AND permissions.code IN (
            'organization.positions.view',
            'organization.positions.manage'
        )
    ) OR (
        roles.code = 'executive_viewer'
        AND permissions.code =
            'organization.positions.view'
    )
) source
ON (
    target.role_id = source.role_id
    AND target.permission_id =
        source.permission_id
)
WHEN NOT MATCHED THEN INSERT (
    role_id,
    permission_id
) VALUES (
    source.role_id,
    source.permission_id
)
SQL,
        <<<'SQL'
MERGE INTO company_role_permissions target
USING (
    SELECT
        companies.company_id,
        grants.role_id,
        grants.permission_id,
        companies.provisioned_by AS granted_by
    FROM companies
    CROSS JOIN role_permissions grants
    INNER JOIN roles
        ON roles.role_id = grants.role_id
    INNER JOIN permissions
        ON permissions.permission_id =
            grants.permission_id
    WHERE companies.deleted_at IS NULL
      AND roles.code IN (
            'system_administrator',
            'company_owner',
            'hr_administrator',
            'executive_viewer'
      )
      AND permissions.code IN (
            'organization.positions.view',
            'organization.positions.manage'
      )
) source
ON (
    target.company_id = source.company_id
    AND target.role_id = source.role_id
    AND target.permission_id =
        source.permission_id
)
WHEN NOT MATCHED THEN INSERT (
    company_id,
    role_id,
    permission_id,
    granted_by
) VALUES (
    source.company_id,
    source.role_id,
    source.permission_id,
    source.granted_by
)
SQL,
    ],
];
