<?php

declare(strict_types=1);

return [
    'version' => '110',
    'description' =>
        'Create effective-dated employee position assignments',
    'statements' => [
        'ALTER TABLE hr_employees'
            . ' ADD CONSTRAINT uq_hr_employees_company_id'
            . ' UNIQUE (company_id, employee_id)',
        'ALTER TABLE organization_positions'
            . ' ADD CONSTRAINT uq_org_positions_company_id'
            . ' UNIQUE (company_id, position_id)',
        <<<'SQL'
CREATE TABLE hr_employee_position_assignments (
    assignment_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    employee_id NUMBER(19) NOT NULL,
    position_id NUMBER(19) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    assignment_status VARCHAR2(20 CHAR)
        DEFAULT 'current' NOT NULL,
    current_marker NUMBER(1) DEFAULT 1,
    position_code_snapshot VARCHAR2(40 CHAR) NOT NULL,
    position_name_snapshot VARCHAR2(140 CHAR) NOT NULL,
    department_name_snapshot VARCHAR2(100 CHAR) NOT NULL,
    job_title_name_snapshot VARCHAR2(120 CHAR) NOT NULL,
    branch_name_snapshot VARCHAR2(120 CHAR),
    notes VARCHAR2(500 CHAR),
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_hr_position_assignments
        PRIMARY KEY (assignment_id),
    CONSTRAINT uq_hr_assignment_current
        UNIQUE (
            company_id,
            employee_id,
            current_marker
        ),
    CONSTRAINT ck_hr_assignment_status
        CHECK (
            assignment_status IN (
                'current',
                'ended'
            )
        ),
    CONSTRAINT ck_hr_assignment_current_marker
        CHECK (
            (
                assignment_status = 'current'
                AND current_marker = 1
                AND effective_to IS NULL
            )
            OR (
                assignment_status = 'ended'
                AND current_marker IS NULL
                AND effective_to IS NOT NULL
            )
        ),
    CONSTRAINT ck_hr_assignment_dates
        CHECK (
            effective_to IS NULL
            OR effective_to > effective_from
        ),
    CONSTRAINT fk_hr_assignment_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_hr_assignment_employee
        FOREIGN KEY (company_id, employee_id)
        REFERENCES hr_employees (
            company_id,
            employee_id
        ),
    CONSTRAINT fk_hr_assignment_position
        FOREIGN KEY (company_id, position_id)
        REFERENCES organization_positions (
            company_id,
            position_id
        ),
    CONSTRAINT fk_hr_assignment_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_hr_assignment_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_hr_assignment_pos_current'
            . ' ON hr_employee_position_assignments ('
            . 'company_id, position_id, current_marker'
            . ')',
        'CREATE INDEX ix_hr_assignment_emp_history'
            . ' ON hr_employee_position_assignments ('
            . 'company_id, employee_id, effective_from'
            . ')',
    ],
];
