<?php

declare(strict_types=1);

return [
    'version' => '120',
    'description' =>
        'Create attendance and leave operations core',
    'statements' => [
        <<<'SQL'
CREATE TABLE attendance_records (
    attendance_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    employee_id NUMBER(19) NOT NULL,
    attendance_date DATE NOT NULL,
    check_in_at TIMESTAMP(6),
    check_out_at TIMESTAMP(6),
    attendance_status VARCHAR2(20 CHAR)
        DEFAULT 'present' NOT NULL,
    work_minutes NUMBER(10) DEFAULT 0 NOT NULL,
    source VARCHAR2(20 CHAR)
        DEFAULT 'manual' NOT NULL,
    notes VARCHAR2(500 CHAR),
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_attendance_records
        PRIMARY KEY (attendance_id),
    CONSTRAINT uq_attendance_employee_date
        UNIQUE (
            company_id,
            employee_id,
            attendance_date
        ),
    CONSTRAINT ck_attendance_status
        CHECK (
            attendance_status IN (
                'present',
                'late',
                'absent',
                'remote',
                'on_leave',
                'holiday'
            )
        ),
    CONSTRAINT ck_attendance_source
        CHECK (
            source IN (
                'manual',
                'import',
                'device',
                'system'
            )
        ),
    CONSTRAINT ck_attendance_work_minutes
        CHECK (work_minutes >= 0),
    CONSTRAINT ck_attendance_time_order
        CHECK (
            check_out_at IS NULL
            OR (
                check_in_at IS NOT NULL
                AND check_out_at >= check_in_at
            )
        ),
    CONSTRAINT fk_attendance_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_attendance_employee
        FOREIGN KEY (company_id, employee_id)
        REFERENCES hr_employees (
            company_id,
            employee_id
        ),
    CONSTRAINT fk_attendance_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_attendance_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_attendance_company_date'
            . ' ON attendance_records ('
            . 'company_id, attendance_date,'
            . ' attendance_status)',
        'CREATE INDEX ix_attendance_emp_history'
            . ' ON attendance_records ('
            . 'company_id, employee_id,'
            . ' attendance_date)',
        <<<'SQL'
CREATE TABLE hr_leave_types (
    leave_type_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    code VARCHAR2(30 CHAR) NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    annual_entitlement NUMBER(6,2)
        DEFAULT 0 NOT NULL,
    requires_approval NUMBER(1)
        DEFAULT 1 NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT pk_hr_leave_types
        PRIMARY KEY (leave_type_id),
    CONSTRAINT uq_leave_types_company_code
        UNIQUE (company_id, code),
    CONSTRAINT uq_leave_types_company_name
        UNIQUE (company_id, name),
    CONSTRAINT uq_leave_types_company_identity
        UNIQUE (company_id, leave_type_id),
    CONSTRAINT ck_leave_type_entitlement
        CHECK (
            annual_entitlement
                BETWEEN 0 AND 366
        ),
    CONSTRAINT ck_leave_type_approval
        CHECK (requires_approval IN (0, 1)),
    CONSTRAINT ck_leave_type_active
        CHECK (active IN (0, 1)),
    CONSTRAINT fk_leave_type_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_leave_type_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_leave_type_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_leave_types_company_active'
            . ' ON hr_leave_types ('
            . 'company_id, active, deleted_at)',
        <<<'SQL'
CREATE TABLE hr_leave_requests (
    leave_request_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    employee_id NUMBER(19) NOT NULL,
    leave_type_id NUMBER(19) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    requested_days NUMBER(6,2) NOT NULL,
    reason VARCHAR2(500 CHAR),
    request_status VARCHAR2(20 CHAR)
        DEFAULT 'pending' NOT NULL,
    decision_note VARCHAR2(500 CHAR),
    decided_by NUMBER(19),
    decided_at TIMESTAMP(6),
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_hr_leave_requests
        PRIMARY KEY (leave_request_id),
    CONSTRAINT ck_leave_request_status
        CHECK (
            request_status IN (
                'pending',
                'approved',
                'rejected',
                'cancelled'
            )
        ),
    CONSTRAINT ck_leave_request_dates
        CHECK (end_date >= start_date),
    CONSTRAINT ck_leave_requested_days
        CHECK (
            requested_days > 0
            AND requested_days <= 366
        ),
    CONSTRAINT ck_leave_decision
        CHECK (
            (
                request_status = 'pending'
                AND decided_at IS NULL
            )
            OR request_status = 'cancelled'
            OR (
                request_status IN (
                    'approved',
                    'rejected'
                )
                AND decided_at IS NOT NULL
            )
        ),
    CONSTRAINT fk_leave_request_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_leave_request_employee
        FOREIGN KEY (company_id, employee_id)
        REFERENCES hr_employees (
            company_id,
            employee_id
        ),
    CONSTRAINT fk_leave_request_type
        FOREIGN KEY (company_id, leave_type_id)
        REFERENCES hr_leave_types (
            company_id,
            leave_type_id
        ),
    CONSTRAINT fk_leave_request_decider
        FOREIGN KEY (decided_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_leave_request_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_leave_request_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_leave_requests_status'
            . ' ON hr_leave_requests ('
            . 'company_id, request_status,'
            . ' start_date, end_date)',
        'CREATE INDEX ix_leave_requests_employee'
            . ' ON hr_leave_requests ('
            . 'company_id, employee_id, start_date)',
        <<<'SQL'
UPDATE erp_modules
SET available = 1,
    description =
        'Daily attendance, time status and workforce presence control.'
WHERE code = 'attendance'
SQL,
        <<<'SQL'
MERGE INTO permissions target
USING (
    SELECT
        'View Attendance Records' AS name,
        'attendance.records.view' AS code,
        'attendance' AS module,
        'View company attendance records and daily workforce status'
            AS description
    FROM dual
    UNION ALL
    SELECT
        'Manage Attendance Records',
        'attendance.records.manage',
        'attendance',
        'Create and update company attendance records'
    FROM dual
    UNION ALL
    SELECT
        'View Leave Requests',
        'hr.leave.view',
        'hr',
        'View company leave requests and leave policy information'
    FROM dual
    UNION ALL
    SELECT
        'Manage Leave Requests',
        'hr.leave.manage',
        'hr',
        'Create company leave requests for authorized employees'
    FROM dual
    UNION ALL
    SELECT
        'Approve Leave Requests',
        'hr.leave.approve',
        'hr',
        'Approve or reject company leave requests'
    FROM dual
) source
ON (target.code = source.code)
WHEN MATCHED THEN UPDATE SET
    target.name = source.name,
    target.module = source.module,
    target.description = source.description,
    target.active = 1
WHEN NOT MATCHED THEN INSERT (
    name,
    code,
    module,
    description,
    active
) VALUES (
    source.name,
    source.code,
    source.module,
    source.description,
    1
)
SQL,
        <<<'SQL'
MERGE INTO role_permissions target
USING (
    SELECT
        roles.role_id,
        permissions.permission_id
    FROM roles
    CROSS JOIN permissions
    WHERE (
            roles.code IN (
                'system_administrator',
                'company_owner',
                'hr_administrator'
            )
            AND permissions.code IN (
                'attendance.records.view',
                'attendance.records.manage',
                'hr.leave.view',
                'hr.leave.manage',
                'hr.leave.approve'
            )
        )
       OR (
            roles.code IN (
                'executive_viewer',
                'auditor'
            )
            AND permissions.code IN (
                'attendance.records.view',
                'hr.leave.view'
            )
        )
) source
ON (
    target.role_id = source.role_id
    AND target.permission_id =
        source.permission_id
)
WHEN NOT MATCHED THEN INSERT (
    role_id,
    permission_id
) VALUES (
    source.role_id,
    source.permission_id
)
SQL,
        <<<'SQL'
MERGE INTO company_role_permissions target
USING (
    SELECT
        companies.company_id,
        grants.role_id,
        grants.permission_id,
        companies.provisioned_by AS granted_by
    FROM companies
    CROSS JOIN role_permissions grants
    INNER JOIN permissions
        ON permissions.permission_id =
            grants.permission_id
    WHERE companies.deleted_at IS NULL
      AND permissions.code IN (
            'attendance.records.view',
            'attendance.records.manage',
            'hr.leave.view',
            'hr.leave.manage',
            'hr.leave.approve'
        )
) source
ON (
    target.company_id = source.company_id
    AND target.role_id = source.role_id
    AND target.permission_id =
        source.permission_id
)
WHEN NOT MATCHED THEN INSERT (
    company_id,
    role_id,
    permission_id,
    granted_by
) VALUES (
    source.company_id,
    source.role_id,
    source.permission_id,
    source.granted_by
)
SQL,
        <<<'SQL'
MERGE INTO hr_leave_types target
USING (
    SELECT
        companies.company_id,
        defaults.code,
        defaults.name,
        defaults.annual_entitlement,
        companies.provisioned_by AS actor_id
    FROM companies
    CROSS JOIN (
        SELECT
            'ANNUAL' AS code,
            'Annual Leave' AS name,
            21 AS annual_entitlement
        FROM dual
        UNION ALL
        SELECT
            'SICK',
            'Sick Leave',
            14
        FROM dual
        UNION ALL
        SELECT
            'COMPASSIONATE',
            'Compassionate Leave',
            5
        FROM dual
        UNION ALL
        SELECT
            'UNPAID',
            'Unpaid Leave',
            0
        FROM dual
    ) defaults
    WHERE companies.deleted_at IS NULL
) source
ON (
    target.company_id = source.company_id
    AND target.code = source.code
)
WHEN MATCHED THEN UPDATE SET
    target.name = source.name,
    target.annual_entitlement =
        source.annual_entitlement,
    target.requires_approval = 1,
    target.active = 1,
    target.deleted_at = NULL
WHEN NOT MATCHED THEN INSERT (
    company_id,
    code,
    name,
    annual_entitlement,
    requires_approval,
    active,
    created_by,
    updated_by
) VALUES (
    source.company_id,
    source.code,
    source.name,
    source.annual_entitlement,
    1,
    1,
    source.actor_id,
    source.actor_id
)
SQL,
    ],
];
