<?php

declare(strict_types=1);

return [
    'version' => '160',
    'description' =>
        'Create tenant leave allocations and adjustment ledger',
    'statements' => [
        <<<'SQL'
CREATE TABLE hr_leave_allocations (
    allocation_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    employee_id NUMBER(19) NOT NULL,
    leave_type_id NUMBER(19) NOT NULL,
    allocation_year NUMBER(4) NOT NULL,
    entitlement_days NUMBER(6,2) NOT NULL,
    carry_over_days NUMBER(6,2)
        DEFAULT 0 NOT NULL,
    notes VARCHAR2(500 CHAR),
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_hr_leave_alloc
        PRIMARY KEY (allocation_id),
    CONSTRAINT uq_leave_alloc_scope
        UNIQUE (
            company_id,
            employee_id,
            leave_type_id,
            allocation_year
        ),
    CONSTRAINT uq_leave_alloc_identity
        UNIQUE (company_id, allocation_id),
    CONSTRAINT ck_leave_alloc_year
        CHECK (
            allocation_year BETWEEN 2000 AND 2100
        ),
    CONSTRAINT ck_leave_alloc_entitle
        CHECK (
            entitlement_days BETWEEN 0 AND 366
        ),
    CONSTRAINT ck_leave_alloc_carry
        CHECK (
            carry_over_days BETWEEN 0 AND 366
        ),
    CONSTRAINT fk_leave_alloc_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_leave_alloc_employee
        FOREIGN KEY (company_id, employee_id)
        REFERENCES hr_employees (
            company_id,
            employee_id
        ),
    CONSTRAINT fk_leave_alloc_type
        FOREIGN KEY (company_id, leave_type_id)
        REFERENCES hr_leave_types (
            company_id,
            leave_type_id
        ),
    CONSTRAINT fk_leave_alloc_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_leave_alloc_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_leave_alloc_emp_year'
            . ' ON hr_leave_allocations ('
            . 'company_id, employee_id, allocation_year)',
        <<<'SQL'
CREATE TABLE hr_leave_balance_adjustments (
    adjustment_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    allocation_id NUMBER(19) NOT NULL,
    adjustment_type VARCHAR2(20 CHAR) NOT NULL,
    adjustment_days NUMBER(7,2) NOT NULL,
    effective_date DATE NOT NULL,
    reason VARCHAR2(500 CHAR) NOT NULL,
    created_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_hr_leave_adjustment
        PRIMARY KEY (adjustment_id),
    CONSTRAINT ck_leave_adjust_type
        CHECK (
            adjustment_type IN (
                'credit',
                'debit'
            )
        ),
    CONSTRAINT ck_leave_adjust_days
        CHECK (
            adjustment_days <> 0
            AND adjustment_days
                BETWEEN -366 AND 366
            AND (
                (
                    adjustment_type = 'credit'
                    AND adjustment_days > 0
                )
                OR (
                    adjustment_type = 'debit'
                    AND adjustment_days < 0
                )
            )
        ),
    CONSTRAINT fk_leave_adjust_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_leave_adjust_alloc
        FOREIGN KEY (company_id, allocation_id)
        REFERENCES hr_leave_allocations (
            company_id,
            allocation_id
        ),
    CONSTRAINT fk_leave_adjust_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        'CREATE INDEX ix_leave_adjust_ledger'
            . ' ON hr_leave_balance_adjustments ('
            . 'company_id, allocation_id,'
            . ' effective_date, adjustment_id)',
        <<<'SQL'
MERGE INTO permissions target
USING (
    SELECT
        'Manage Leave Balances' AS name,
        'hr.leave.balance.manage' AS code,
        'hr' AS module,
        'Manage employee annual allocations, carry-over and balance adjustments'
            AS description
    FROM dual
) source
ON (target.code = source.code)
WHEN MATCHED THEN UPDATE SET
    target.name = source.name,
    target.module = source.module,
    target.description = source.description,
    target.active = 1
WHEN NOT MATCHED THEN INSERT (
    name,
    code,
    module,
    description,
    active
) VALUES (
    source.name,
    source.code,
    source.module,
    source.description,
    1
)
SQL,
        <<<'SQL'
MERGE INTO role_permissions target
USING (
    SELECT
        roles.role_id,
        permissions.permission_id
    FROM roles
    CROSS JOIN permissions
    WHERE roles.code IN (
            'system_administrator',
            'company_owner',
            'hr_administrator'
        )
      AND permissions.code =
            'hr.leave.balance.manage'
) source
ON (
    target.role_id = source.role_id
    AND target.permission_id =
        source.permission_id
)
WHEN NOT MATCHED THEN INSERT (
    role_id,
    permission_id
) VALUES (
    source.role_id,
    source.permission_id
)
SQL,
        <<<'SQL'
MERGE INTO company_role_permissions target
USING (
    SELECT
        companies.company_id,
        grants.role_id,
        grants.permission_id,
        companies.provisioned_by AS granted_by
    FROM companies
    CROSS JOIN role_permissions grants
    INNER JOIN roles
        ON roles.role_id = grants.role_id
    INNER JOIN permissions
        ON permissions.permission_id =
            grants.permission_id
    WHERE companies.deleted_at IS NULL
      AND permissions.code =
            'hr.leave.balance.manage'
      AND roles.code IN (
            'system_administrator',
            'company_owner',
            'hr_administrator'
        )
) source
ON (
    target.company_id = source.company_id
    AND target.role_id = source.role_id
    AND target.permission_id =
        source.permission_id
)
WHEN NOT MATCHED THEN INSERT (
    company_id,
    role_id,
    permission_id,
    granted_by
) VALUES (
    source.company_id,
    source.role_id,
    source.permission_id,
    source.granted_by
)
SQL,
    ],
];
