<?php

declare(strict_types=1);

return [
    'version' => '170',
    'description' =>
        'Create configurable staged leave approval workflows',
    'statements' => [
        <<<'SQL'
ALTER TABLE hr_leave_types ADD (
    approval_workflow VARCHAR2(30 CHAR)
        DEFAULT 'manager' NOT NULL,
    hr_approver_user_id NUMBER(19)
)
SQL,
        <<<'SQL'
ALTER TABLE hr_leave_types
    ADD CONSTRAINT ck_leave_type_workflow
    CHECK (
        approval_workflow IN (
            'none',
            'manager',
            'hr',
            'manager_then_hr'
        )
    )
SQL,
        <<<'SQL'
ALTER TABLE hr_leave_types
    ADD CONSTRAINT fk_leave_type_hr_approver
    FOREIGN KEY (
        company_id,
        hr_approver_user_id
    )
    REFERENCES company_users (
        company_id,
        user_id
    )
SQL,
        'CREATE INDEX ix_leave_type_hr_approver'
            . ' ON hr_leave_types ('
            . 'company_id, hr_approver_user_id, active)',
        <<<'SQL'
UPDATE hr_leave_types
SET approval_workflow =
    CASE
        WHEN requires_approval = 1
            THEN 'manager'
        ELSE 'none'
    END
SQL,
        <<<'SQL'
ALTER TABLE hr_leave_requests ADD (
    approval_workflow VARCHAR2(30 CHAR)
        DEFAULT 'manager' NOT NULL
)
SQL,
        <<<'SQL'
ALTER TABLE hr_leave_requests
    ADD CONSTRAINT uq_leave_request_identity
    UNIQUE (company_id, leave_request_id)
SQL,
        <<<'SQL'
ALTER TABLE hr_leave_requests
    ADD CONSTRAINT ck_leave_request_workflow
    CHECK (
        approval_workflow IN (
            'none',
            'manager',
            'hr',
            'manager_then_hr'
        )
    )
SQL,
        <<<'SQL'
MERGE INTO hr_leave_requests requests
USING (
    SELECT
        company_id,
        leave_type_id,
        approval_workflow
    FROM hr_leave_types
) types
ON (
    types.company_id = requests.company_id
    AND types.leave_type_id =
        requests.leave_type_id
)
WHEN MATCHED THEN UPDATE SET
    requests.approval_workflow =
        types.approval_workflow
SQL,
        <<<'SQL'
CREATE TABLE hr_leave_request_approvals (
    approval_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    leave_request_id NUMBER(19) NOT NULL,
    approval_stage VARCHAR2(20 CHAR) NOT NULL,
    approval_sequence NUMBER(2) NOT NULL,
    approver_user_id NUMBER(19) NOT NULL,
    approval_status VARCHAR2(20 CHAR)
        DEFAULT 'waiting' NOT NULL,
    decision_note VARCHAR2(500 CHAR),
    decided_at TIMESTAMP(6),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_leave_req_approvals
        PRIMARY KEY (approval_id),
    CONSTRAINT uq_leave_approval_stage
        UNIQUE (
            company_id,
            leave_request_id,
            approval_stage
        ),
    CONSTRAINT uq_leave_approval_identity
        UNIQUE (company_id, approval_id),
    CONSTRAINT ck_leave_approval_stage
        CHECK (
            approval_stage IN ('manager', 'hr')
        ),
    CONSTRAINT ck_leave_approval_sequence
        CHECK (
            approval_sequence BETWEEN 1 AND 2
        ),
    CONSTRAINT ck_leave_approval_status
        CHECK (
            approval_status IN (
                'waiting',
                'pending',
                'approved',
                'rejected'
            )
        ),
    CONSTRAINT ck_leave_approval_decision
        CHECK (
            (
                approval_status IN ('waiting', 'pending')
                AND decided_at IS NULL
            )
            OR (
                approval_status IN ('approved', 'rejected')
                AND decided_at IS NOT NULL
            )
        ),
    CONSTRAINT fk_leave_approval_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id),
    CONSTRAINT fk_leave_approval_request
        FOREIGN KEY (company_id, leave_request_id)
        REFERENCES hr_leave_requests (
            company_id,
            leave_request_id
        ),
    CONSTRAINT fk_leave_approval_approver
        FOREIGN KEY (company_id, approver_user_id)
        REFERENCES company_users (
            company_id,
            user_id
        )
)
SQL,
        'CREATE INDEX ix_leave_approval_inbox'
            . ' ON hr_leave_request_approvals ('
            . 'company_id, approver_user_id,'
            . ' approval_status, approval_sequence)',
        'CREATE INDEX ix_leave_approval_request'
            . ' ON hr_leave_request_approvals ('
            . 'company_id, leave_request_id,'
            . ' approval_sequence)',
        <<<'SQL'
INSERT INTO hr_leave_request_approvals (
    company_id,
    leave_request_id,
    approval_stage,
    approval_sequence,
    approver_user_id,
    approval_status
)
SELECT
    requests.company_id,
    requests.leave_request_id,
    'manager',
    1,
    manager_membership.user_id,
    'pending'
FROM hr_leave_requests requests
INNER JOIN hr_employees employees
    ON employees.company_id = requests.company_id
   AND employees.employee_id = requests.employee_id
INNER JOIN company_users employee_membership
    ON employee_membership.company_id =
        employees.company_id
   AND employee_membership.user_id =
        employees.user_id
   AND employee_membership.active = 1
INNER JOIN company_users manager_membership
    ON manager_membership.company_id =
        employee_membership.company_id
   AND manager_membership.user_id =
        employee_membership.manager_user_id
   AND manager_membership.active = 1
WHERE requests.request_status = 'pending'
  AND requests.approval_workflow = 'manager'
SQL,
    ],
];
