<?php

declare(strict_types=1);

return [
    'version' => '200',
    'description' =>
        'Create user-owned attendance reminder preferences',
    'statements' => [
        <<<'SQL'
CREATE TABLE attendance_user_reminders (
    reminder_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    timezone VARCHAR2(80 CHAR) NOT NULL,
    workday_mask NUMBER(3) DEFAULT 31 NOT NULL,
    check_in_enabled NUMBER(1) DEFAULT 0 NOT NULL,
    check_in_time VARCHAR2(5 CHAR)
        DEFAULT '08:30' NOT NULL,
    check_out_enabled NUMBER(1) DEFAULT 0 NOT NULL,
    check_out_time VARCHAR2(5 CHAR)
        DEFAULT '17:30' NOT NULL,
    reminder_lead_minutes NUMBER(3)
        DEFAULT 10 NOT NULL,
    browser_notifications_enabled NUMBER(1)
        DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_attendance_user_reminders
        PRIMARY KEY (reminder_id),
    CONSTRAINT uq_attendance_user_reminder
        UNIQUE (company_id, user_id),
    CONSTRAINT ck_att_reminder_workdays
        CHECK (workday_mask BETWEEN 1 AND 127),
    CONSTRAINT ck_att_reminder_check_in
        CHECK (check_in_enabled IN (0, 1)),
    CONSTRAINT ck_att_reminder_check_out
        CHECK (check_out_enabled IN (0, 1)),
    CONSTRAINT ck_att_reminder_lead
        CHECK (
            reminder_lead_minutes IN (
                0,
                5,
                10,
                15,
                30,
                60
            )
        ),
    CONSTRAINT ck_att_reminder_browser
        CHECK (
            browser_notifications_enabled
                IN (0, 1)
        ),
    CONSTRAINT fk_att_reminder_company_user
        FOREIGN KEY (company_id, user_id)
        REFERENCES company_users (
            company_id,
            user_id
        )
        ON DELETE CASCADE
)
SQL,
    ],
];
