<?php

declare(strict_types=1);

return [
    'version' => '210',
    'description' =>
        'Create workforce calendars, schedules and attendance notification outbox',
    'statements' => [
        <<<'SQL'
CREATE TABLE workforce_calendars (
    calendar_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    code VARCHAR2(40 CHAR) NOT NULL,
    name VARCHAR2(120 CHAR) NOT NULL,
    timezone VARCHAR2(80 CHAR) NOT NULL,
    country_code CHAR(2 CHAR),
    subdivision_code VARCHAR2(16 CHAR),
    week_start NUMBER(1) DEFAULT 1 NOT NULL,
    is_default NUMBER(1) DEFAULT 0 NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_workforce_calendars
        PRIMARY KEY (calendar_id),
    CONSTRAINT uq_workforce_calendar_code
        UNIQUE (company_id, code),
    CONSTRAINT uq_workforce_calendar_scope
        UNIQUE (company_id, calendar_id),
    CONSTRAINT ck_workforce_calendar_week_start
        CHECK (week_start BETWEEN 1 AND 7),
    CONSTRAINT ck_workforce_calendar_default
        CHECK (is_default IN (0, 1)),
    CONSTRAINT ck_workforce_calendar_active
        CHECK (active IN (0, 1)),
    CONSTRAINT fk_workforce_calendar_company
        FOREIGN KEY (company_id)
        REFERENCES companies(company_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_workforce_calendar_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_workforce_calendar_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
        ON DELETE SET NULL
)
SQL,
        <<<'SQL'
CREATE TABLE workforce_calendar_days (
    calendar_id NUMBER(19) NOT NULL,
    iso_weekday NUMBER(1) NOT NULL,
    working_day NUMBER(1) DEFAULT 1 NOT NULL,
    start_time VARCHAR2(5 CHAR),
    end_time VARCHAR2(5 CHAR),
    break_minutes NUMBER(3) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_workforce_calendar_days
        PRIMARY KEY (calendar_id, iso_weekday),
    CONSTRAINT ck_workforce_day_weekday
        CHECK (iso_weekday BETWEEN 1 AND 7),
    CONSTRAINT ck_workforce_day_working
        CHECK (working_day IN (0, 1)),
    CONSTRAINT ck_workforce_day_break
        CHECK (break_minutes BETWEEN 0 AND 480),
    CONSTRAINT fk_workforce_day_calendar
        FOREIGN KEY (calendar_id)
        REFERENCES workforce_calendars(calendar_id)
        ON DELETE CASCADE
)
SQL,
        <<<'SQL'
CREATE TABLE workforce_holidays (
    holiday_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    calendar_id NUMBER(19) NOT NULL,
    holiday_date DATE NOT NULL,
    name VARCHAR2(150 CHAR) NOT NULL,
    holiday_type VARCHAR2(20 CHAR)
        DEFAULT 'public' NOT NULL,
    day_portion VARCHAR2(10 CHAR)
        DEFAULT 'full' NOT NULL,
    observed NUMBER(1) DEFAULT 0 NOT NULL,
    description VARCHAR2(500 CHAR),
    created_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_workforce_holidays
        PRIMARY KEY (holiday_id),
    CONSTRAINT uq_workforce_holiday
        UNIQUE (calendar_id, holiday_date, name),
    CONSTRAINT ck_workforce_holiday_type
        CHECK (holiday_type IN ('public', 'company')),
    CONSTRAINT ck_workforce_holiday_portion
        CHECK (day_portion IN ('full', 'am', 'pm')),
    CONSTRAINT ck_workforce_holiday_observed
        CHECK (observed IN (0, 1)),
    CONSTRAINT fk_workforce_holiday_calendar
        FOREIGN KEY (company_id, calendar_id)
        REFERENCES workforce_calendars(
            company_id,
            calendar_id
        )
        ON DELETE CASCADE,
    CONSTRAINT fk_workforce_holiday_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
        ON DELETE SET NULL
)
SQL,
        <<<'SQL'
CREATE TABLE employee_work_schedules (
    schedule_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    employee_id NUMBER(19) NOT NULL,
    calendar_id NUMBER(19) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_employee_work_schedules
        PRIMARY KEY (schedule_id),
    CONSTRAINT uq_employee_work_schedule
        UNIQUE (
            company_id,
            employee_id,
            calendar_id,
            effective_from
        ),
    CONSTRAINT ck_employee_schedule_dates
        CHECK (
            effective_to IS NULL
            OR effective_to >= effective_from
        ),
    CONSTRAINT ck_employee_schedule_active
        CHECK (active IN (0, 1)),
    CONSTRAINT fk_employee_schedule_employee
        FOREIGN KEY (company_id, employee_id)
        REFERENCES hr_employees(company_id, employee_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_employee_schedule_calendar
        FOREIGN KEY (company_id, calendar_id)
        REFERENCES workforce_calendars(
            company_id,
            calendar_id
        )
        ON DELETE CASCADE,
    CONSTRAINT fk_employee_schedule_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
        ON DELETE SET NULL
)
SQL,
        <<<'SQL'
CREATE INDEX idx_employee_schedule_effective
    ON employee_work_schedules (
        company_id,
        employee_id,
        active,
        effective_from,
        effective_to
    )
SQL,
        <<<'SQL'
CREATE TABLE attendance_notifications (
    notification_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    notification_type VARCHAR2(30 CHAR) NOT NULL,
    title VARCHAR2(160 CHAR) NOT NULL,
    body VARCHAR2(500 CHAR) NOT NULL,
    scheduled_for TIMESTAMP(6) NOT NULL,
    local_date DATE NOT NULL,
    channel VARCHAR2(20 CHAR)
        DEFAULT 'in_app' NOT NULL,
    status VARCHAR2(20 CHAR)
        DEFAULT 'unread' NOT NULL,
    dedupe_key VARCHAR2(190 CHAR) NOT NULL,
    read_at TIMESTAMP(6),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_attendance_notifications
        PRIMARY KEY (notification_id),
    CONSTRAINT uq_attendance_notification_dedupe
        UNIQUE (company_id, user_id, dedupe_key),
    CONSTRAINT ck_attendance_notification_type
        CHECK (
            notification_type IN (
                'check_in',
                'check_out'
            )
        ),
    CONSTRAINT ck_attendance_notification_channel
        CHECK (channel = 'in_app'),
    CONSTRAINT ck_attendance_notification_status
        CHECK (status IN ('unread', 'read')),
    CONSTRAINT fk_attendance_notification_user
        FOREIGN KEY (company_id, user_id)
        REFERENCES company_users(company_id, user_id)
        ON DELETE CASCADE
)
SQL,
        <<<'SQL'
CREATE INDEX idx_attendance_notification_inbox
    ON attendance_notifications (
        company_id,
        user_id,
        status,
        scheduled_for
    )
SQL,
    ],
];
