<?php

declare(strict_types=1);

return [
    'version' => '230',
    'description' =>
        'Create tenant-scoped attendance Web Push subscriptions and delivery outbox',
    'statements' => [
        <<<'SQL'
CREATE TABLE attendance_push_subscriptions (
    subscription_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    endpoint VARCHAR2(2048 CHAR) NOT NULL,
    endpoint_hash CHAR(64 CHAR) NOT NULL,
    p256dh VARCHAR2(255 CHAR) NOT NULL,
    auth_secret VARCHAR2(255 CHAR) NOT NULL,
    content_encoding VARCHAR2(32 CHAR)
        DEFAULT 'aes128gcm' NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    failure_count NUMBER(5) DEFAULT 0 NOT NULL,
    last_success_at TIMESTAMP(6),
    last_failure_at TIMESTAMP(6),
    disabled_at TIMESTAMP(6),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_attendance_push_subscription
        PRIMARY KEY (subscription_id),
    CONSTRAINT uq_attendance_push_endpoint
        UNIQUE (endpoint_hash),
    CONSTRAINT ck_attendance_push_encoding
        CHECK (
            content_encoding IN (
                'aes128gcm',
                'aesgcm'
            )
        ),
    CONSTRAINT ck_attendance_push_active
        CHECK (active IN (0, 1)),
    CONSTRAINT fk_attendance_push_user
        FOREIGN KEY (company_id, user_id)
        REFERENCES company_users(company_id, user_id)
        ON DELETE CASCADE
)
SQL,
        <<<'SQL'
CREATE INDEX idx_attendance_push_owner
    ON attendance_push_subscriptions (
        company_id,
        user_id,
        active
    )
SQL,
        <<<'SQL'
CREATE TABLE attendance_push_deliveries (
    notification_id NUMBER(19) NOT NULL,
    subscription_id NUMBER(19) NOT NULL,
    delivery_status VARCHAR2(20 CHAR)
        DEFAULT 'pending' NOT NULL,
    attempts NUMBER(5) DEFAULT 0 NOT NULL,
    next_attempt_at TIMESTAMP(6),
    last_status_code NUMBER(5),
    failure_reason VARCHAR2(500 CHAR),
    delivered_at TIMESTAMP(6),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_attendance_push_delivery
        PRIMARY KEY (
            notification_id,
            subscription_id
        ),
    CONSTRAINT ck_attendance_push_delivery_status
        CHECK (
            delivery_status IN (
                'pending',
                'delivered',
                'retry',
                'failed'
            )
        ),
    CONSTRAINT fk_attendance_push_delivery_notice
        FOREIGN KEY (notification_id)
        REFERENCES attendance_notifications(notification_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_attendance_push_delivery_sub
        FOREIGN KEY (subscription_id)
        REFERENCES attendance_push_subscriptions(subscription_id)
        ON DELETE CASCADE
)
SQL,
        <<<'SQL'
CREATE INDEX idx_attendance_push_delivery_queue
    ON attendance_push_deliveries (
        delivery_status,
        next_attempt_at
    )
SQL,
    ],
];
