<?php

declare(strict_types=1);

return [
    'version' => '240',
    'description' =>
        'Create auditable multi-session attendance punches',
    'preflight' => static function (
        \PDO $connection
    ): string {
        $statement = $connection->prepare(
            'SELECT COUNT(*)
             FROM user_tables
             WHERE table_name = :table_name'
        );
        $statement->execute([
            'table_name' => 'ATTENDANCE_SESSIONS',
        ]);

        if ((int) $statement->fetchColumn() === 0) {
            return 'apply';
        }

        $columns = $connection->prepare(
            'SELECT COUNT(*)
             FROM user_tab_columns
             WHERE table_name = :table_name
               AND column_name IN (
                    \'SESSION_ID\',
                    \'ATTENDANCE_ID\',
                    \'COMPANY_ID\',
                    \'EMPLOYEE_ID\',
                    \'SEQUENCE_NO\',
                    \'CHECK_IN_AT\',
                    \'CHECK_OUT_AT\',
                    \'ACTIVE\',
                    \'OPEN_SLOT\',
                    \'SOURCE\',
                    \'INVALIDATED_AT\',
                    \'INVALIDATED_BY\',
                    \'CREATED_BY\',
                    \'UPDATED_BY\',
                    \'CREATED_AT\',
                    \'UPDATED_AT\'
               )'
        );
        $columns->execute([
            'table_name' => 'ATTENDANCE_SESSIONS',
        ]);

        if ((int) $columns->fetchColumn() === 16) {
            return 'baseline';
        }

        throw new \RuntimeException(
            'Migration 240 found a partial attendance-session schema.'
        );
    },
    'statements' => [
        <<<'SQL'
ALTER TABLE attendance_records
    ADD CONSTRAINT uq_attendance_record_identity
        UNIQUE (
            company_id,
            employee_id,
            attendance_id
        )
SQL,
        <<<'SQL'
CREATE TABLE attendance_sessions (
    session_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    attendance_id NUMBER(19) NOT NULL,
    company_id NUMBER(19) NOT NULL,
    employee_id NUMBER(19) NOT NULL,
    sequence_no NUMBER(5) NOT NULL,
    check_in_at TIMESTAMP(6) NOT NULL,
    check_out_at TIMESTAMP(6),
    active NUMBER(1) DEFAULT 1 NOT NULL,
    open_slot NUMBER(1)
        GENERATED ALWAYS AS (
            CASE
                WHEN active = 1
                    AND check_out_at IS NULL
                THEN 1
                ELSE NULL
            END
        ) VIRTUAL,
    source VARCHAR2(20 CHAR)
        DEFAULT 'self_service' NOT NULL,
    invalidated_at TIMESTAMP(6),
    invalidated_by NUMBER(19),
    created_by NUMBER(19),
    updated_by NUMBER(19),
    created_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_attendance_sessions
        PRIMARY KEY (session_id),
    CONSTRAINT uq_attendance_session_sequence
        UNIQUE (attendance_id, sequence_no),
    CONSTRAINT uq_attendance_open_session
        UNIQUE (attendance_id, open_slot),
    CONSTRAINT ck_attendance_session_time
        CHECK (
            check_out_at IS NULL
            OR check_out_at >= check_in_at
        ),
    CONSTRAINT ck_attendance_session_active
        CHECK (active IN (0, 1)),
    CONSTRAINT ck_attendance_session_source
        CHECK (
            source IN (
                'manual',
                'import',
                'device',
                'system',
                'self_service'
            )
        ),
    CONSTRAINT fk_attendance_session_record
        FOREIGN KEY (
            company_id,
            employee_id,
            attendance_id
        )
        REFERENCES attendance_records (
            company_id,
            employee_id,
            attendance_id
        )
        ON DELETE CASCADE,
    CONSTRAINT fk_attendance_session_invalid
        FOREIGN KEY (invalidated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_attendance_session_creator
        FOREIGN KEY (created_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_attendance_session_updater
        FOREIGN KEY (updated_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL
)
SQL,
        <<<'SQL'
CREATE INDEX idx_attendance_session_employee
    ON attendance_sessions (
        company_id,
        employee_id,
        check_in_at
    )
SQL,
        <<<'SQL'
CREATE INDEX idx_attendance_session_record
    ON attendance_sessions (
        attendance_id,
        active,
        sequence_no
    )
SQL,
        <<<'SQL'
INSERT INTO attendance_sessions (
    attendance_id,
    company_id,
    employee_id,
    sequence_no,
    check_in_at,
    check_out_at,
    active,
    source,
    created_by,
    updated_by
)
SELECT
    attendance_id,
    company_id,
    employee_id,
    1,
    check_in_at,
    check_out_at,
    1,
    source,
    created_by,
    updated_by
FROM attendance_records
WHERE check_in_at IS NOT NULL
SQL,
    ],
];
